### ISSUE TITLE
Question: TaskFailed ...  OpenSignalingConnectionTask got canceled while waiting to open signaling connection

### ISSUE THREAD

**Issue by MandarinConLaBarba** [aws/amazon-chime-sdk-js#2321] opened 2022-06-23 17:44 UTC
This is not a bug report but rather a request for information. I'm trying to determine the cause of the below error:

```
2022-06-20T14:45:50.061Z [ERROR] ChimeMeetingLogger - failed with status code TaskFailed and error: serial group task AudioVideoReconnect/55f8df63-c3c2-4b5d-90bf-24a22c610706/10225d30-5197-4f26-abd7-79283fbde29a was canceled due to subtask AudioVideoReconnect/55f8df63-c3c2-4b5d-90bf-24a22c610706/10225d30-5197-4f26-abd7-79283fbde29a/Timeout15000ms error: serial group task AudioVideoReconnect/55f8df63-c3c2-4b5d-90bf-24a22c610706/10225d30-5197-4f26-abd7-79283fbde29a/Timeout15000ms/Media was canceled due to subtask AudioVideoReconnect/55f8df63-c3c2-4b5d-90bf-24a22c610706/10225d30-5197-4f26-abd7-79283fbde29a/Timeout15000ms/Media/Signaling error: serial group task AudioVideoReconnect/55f8df63-c3c2-4b5d-90bf-24a22c610706/10225d30-5197-4f26-abd7-79283fbde29a/Timeout15000ms/Media/Signaling was canceled due to subtask AudioVideoReconnect/55f8df63-c3c2-4b5d-90bf-24a22c610706/10225d30-5197-4f26-abd7-79283fbde29a/Timeout15000ms/Media/Signaling/OpenSignalingConnectionTask error: OpenSignalingConnectionTask got canceled while waiting to open signaling connection
```

I can see that there seems to be a timeout attempting to establish a valid connection w/ the signaling client. This particular event happened after a chime session was already established.

**Comment by michhyun1** [comment] 2022-06-24 19:18
This can be because the Amazon Chime SDK for Javascript is trying to establish a reconnection, but cannot establish the signaling connection. Is this reproduce-able? Seems to be client network related in most cases.

**Comment by shriyajuneja** [comment] 2022-07-04 10:34
Hi team, I'm getting similar TaskFailed error. In this case Amazon Chime SDK for Javascript is unable to establish web socket connection while trying to start meeting. What could be the reason for web socket failure ?
```
will retry due to status code TaskFailed and error: serial group task AudioVideoStart/27fc8326-977d-48a3-b38d-1b43b84b0706/0c892206-723c-d3be-d520-b56a469640a6 was canceled due to subtask AudioVideoStart/27fc8326-977d-48a3-b38d-1b43b84b0706/0c892206-723c-d3be-d520-b56a469640a6/Timeout15000ms error: serial group task AudioVideoStart/27fc8326-977d-48a3-b38d-1b43b84b0706/0c892206-723c-d3be-d520-b56a469640a6/Timeout15000ms/Peer was canceled due to subtask AudioVideoStart/27fc8326-977d-48a3-b38d-1b43b84b0706/0c892206-723c-d3be-d520-b56a469640a6/Timeout15000ms/Peer/SubscribeAndReceiveSubscribeAckTask (once) error: serial group task Signaling was canceled due to subtask Signaling/Timeout15000ms (once) error: WebSocket connection failed
```
```
Start failed: The connection failed. See the error message for more details. due to error Error: serial group task AudioVideoStart/27fc8326-977d-48a3-b38d-1b43b84b0706/0c892206-723c-d3be-d520-b56a469640a6 was canceled due to subtask AudioVideoStart/27fc8326-977d-48a3-b38d-1b43b84b0706/0c892206-723c-d3be-d520-b56a469640a6/Timeout15000ms error: serial group task AudioVideoStart/27fc8326-977d-48a3-b38d-1b43b84b0706/0c892206-723c-d3be-d520-b56a469640a6/Timeout15000ms/Peer was canceled due to subtask AudioVideoStart/27fc8326-977d-48a3-b38d-1b43b84b0706/0c892206-723c-d3be-d520-b56a469640a6/Timeout15000ms/Peer/SubscribeAndReceiveSubscribeAckTask (once) error: serial group task Signaling was canceled due to subtask Signaling/Timeout15000ms (once) error: WebSocket connection failed.
```
```notifying event: WebSocketClosed
no connection requests to service
event: signalingDropped
notifying event: WebSocketFailed
stopped pinging (WebSocketFailed)
Opening signaling connection took 23 ms
```

**Comment by michhyun1** [comment] 2022-07-06 19:52
Will close this issue, as there is a duplicate: https://github.com/aws/amazon-chime-sdk-js/issues/2351#issuecomment-1176470636

**Closed by michhyun1** 2022-07-06 19:52 UTC

**Comment by phienle-valant** [comment] 2025-08-19 10:39
The issue seems has not been addressed yet. I still see > 1000 exception like this during last month 8/2025:
serial group task AudioVideoReconnect/77f0c00e-93a6-4590-b994-26e583a32713/9287f3bf-03fb-4a47-d33c-796c71310a6c was canceled due to subtask AudioVideoReconnect/77f0c00e-93a6-4590-b994-26e583a32713/9287f3bf-03fb-4a47-d33c-796c71310a6c/Timeout15000ms error: serial group task AudioVideoReconnect/77f0c00e-93a6-4590-b994-26e583a32713/9287f3bf-03fb-4a47-d33c-796c71310a6c/Timeout15000ms/Media was canceled due to subtask AudioVideoReconnect/77f0c00e-93a6-4590-b994-26e583a32713/9287f3bf-03fb-4a47-d33c-796c71310a6c/Timeout15000ms/Media/Signaling error: serial group task AudioVideoReconnect/77f0c00e-93a6-4590-b994-26e583a32713/9287f3bf-03fb-4a47-d33c-796c71310a6c/Timeout15000ms/Media/Signaling was canceled due to subtask AudioVideoReconnect/77f0c00e-93a6-4590-b994-26e583a32713/9287f3bf-03fb-4a47-d33c-796c71310a6c/Timeout15000ms/Media/Signaling/OpenSignalingConnectionTask error: WebSocket connection failed
