### ISSUE TITLE
Ideal frameRate in getUserMedia doesn't work for all cameras

### ISSUE THREAD

**Issue by hanfangAmazon** [aws/amazon-chime-sdk-js#2598] opened 2023-02-28 22:24 UTC
### What happened and what did you expect to happen?

[Default video frame rate is 15](https://github.com/aws/amazon-chime-sdk-js/blob/6fae98a9f30fe3ac7de713445fd9b94e5ae56d1f/src/devicecontroller/DefaultDeviceController.ts#L40), it's set to preserve bandwidth and CPU usage, which is fine.

When we use it in [getUserMedia with ideal keyword](https://github.com/aws/amazon-chime-sdk-js/blob/main/src/devicecontroller/DefaultDeviceController.ts#L1282), something is broken, we got blank/black video tile for some Logitech c270 cameras (not all), other camera maybe affected as well.

We tested following frameRate values with the camera:
- Values work with the camera: 3, 4, 5, 6, 7, 8, 9, 10, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 60, 120, 65535
- Values don't work with the camera: 1, 2, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20
`{"video":{"deviceId":{"exact":"xxxxx"},"width":{"ideal":960},"height":{"ideal":540},"frameRate":{"ideal": x}}}`

Reproducible in latest SDK demo.

The issue can be fixed by changing `ideal` to `max`, the only concern is, do all cameras support low frame rate (<= 15)?

### Have you reviewed our existing documentation?

- [X] GitHub [issues](https://github.com/aws/amazon-chime-sdk-js/issues)
- [X] FAQs [page](https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html)
- [X] README [page](https://github.com/aws/amazon-chime-sdk-js#amazon-chime-sdk-for-javascript)
- [X] Feature-specific [guides](https://github.com/aws/amazon-chime-sdk-js#guides)

### Reproduction steps

You will need a camera isn't compatible with certain frame rate to test it, feel free reach out to me for log.

### Amazon Chime SDK for JavaScript version

3.10.0

### What browsers are you seeing the problem on?

Chrome

### Browser version

110

### Browser console logs

Feel free reach out to me for log, it has some internal information that we are not allowed to share.

**Comment by xuesichao** [comment] 2023-03-22 20:46
Hi @hanfangAmazon. Are you able to require stream from Logitech c270 camera with vanilla JavaScript `getUserMedia` call? 

```js
const stream = await navigator.mediaDevices.getUserMedia({ video: { frameRate: { ideal: 15 } } });
// vs
const stream = await navigator.mediaDevices.getUserMedia({ video: { frameRate: { max: 15 } } });
```

Could you give it a try in this code pen?
https://codepen.io/xuesichao/pen/MWqzbzy

Our SDK simply calculates the `constraints` and eventually calls `getUserMedia` with it. This is more like a camera device hardware issue or a browser issue.

From [`getUserMedia` doc](https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/getUserMedia):
* An `ideal` value, when used, has gravity, which means that the browser will try to find the setting (and camera, if you have more than one), with the smallest [fitness distance](https://w3c.github.io/mediacapture-main/#dfn-fitness-distance) from the ideal values given.
* A `max` property specifies the maximum frame rate that the application is willing to accept from the camera. If no camera exists support a frame rate lower than 15 fps, then the returned promise will be rejected with `OverconstrainedError`, and the user will not be prompted.

So either way it's a browser behavior, nothing we can do here. And this seems weird. Because if `max 15 fps` works, `ideal 15 fps` should work too. Let us know your testing result from code pen. If you're not able to reproduce it using vanilla JS, then there should be a bug in our code, most likely an error is not handled correctly and we display the video tile without binding a valid stream to it.

**Comment by hanfangAmazon** [comment] 2023-03-22 22:24
Yes, I tested with Vanilla Javascript, code pen here: https://codepen.io/hanfangAmazon/pen/yLxQMMq

One thing to notice, using `frameRate: { ideal: 15 }` alone isn't a problem, it only happens if we combine it with `width` and `height` constraints.

It's likely related to Chromium MediaFoundation video capture, but that doesn't mean nothing we can do here.

The fix we made on our end is to remove `frameRate` constraint from `getUserMedia`, this will ensure the maximum compatibility with all cameras, the actual frame rate we are sending is still under control since it's capped by video frame processor, https://github.com/aws/amazon-chime-sdk-js/blob/f62673d21fd12977e01c6a4c0c2f1df5a1f5330b/src/videoframeprocessor/DefaultVideoFrameProcessorPipeline.ts#L11

I'm thinking if you can so something similar in SDK code, try not to limit native frame rate of the camera, but capture it at the frame rate we want.

**Comment by xuesichao** [comment] 2023-03-23 18:00
@hanfangAmazon Cool, thanks for your information, this is really helpful. It makes sense to enable maximum compatibility with all cameras and limit the frame rate later. This is really a good call.  Let us evaluate this solution and follow up on this later. Appreciate your help!

**Comment by michhyun1** [comment] 2024-11-04 22:13
Resolving this issue - as there doesnt seem to be any follow up item on our end.

**Closed by michhyun1** 2024-11-04 22:13 UTC
Labels: feature-request
