### ISSUE TITLE
Wrong stream for a split second after calling chooseRemoteVideoSources on Firefox

### ISSUE THREAD

**Issue by andreisergiu98** [aws/amazon-chime-sdk-js#1807] opened 2021-11-18 22:20 UTC
### What happened and what did you expect to happen?

We use priority based downlink policy to unsubscribe to streams that are not in view. As shown in the video below, after `chooseRemoteVideoSources` is called Firefox will render a wrong video stream for a moment, afterwards the correct stream is rendered.
There is also a similar issue where we choose remote video sources some of the streams will go blank for a couple of milliseconds.

Mentions:
Simulcast is off.

https://user-images.githubusercontent.com/11740700/142455751-22179977-3509-4e52-b802-39ddc66f510f.mp4

### Have you reviewed our existing documentation?

- [X] GitHub [issues](https://github.com/aws/amazon-chime-sdk-js/issues)
- [X] FAQs [page](https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html)
- [X] README [page](https://github.com/aws/amazon-chime-sdk-js#amazon-chime-sdk-for-javascript)
- [X] Feature-specific [guides](https://github.com/aws/amazon-chime-sdk-js#guides)

### Reproduction steps

See video.

### Amazon Chime SDK for JavaScript version

2.21.1

### What browsers are you seeing the problem on?

Firefox

### Browser version

94.0.1

### Browser console logs

[meeting-logs.txt](https://github.com/aws/amazon-chime-sdk-js/files/7566396/meeting-logs.txt)

**Comment by hensmi-amazon** [comment] 2021-11-23 21:59
Thanks for the report.  For our investigation, could you describe how you are binding the tiles? Are you reusing Video HTML elements?

**Comment by hensmi-amazon** [comment] 2021-11-24 23:17
I believe I have an easy repro, and a likely fix in https://github.com/aws/amazon-chime-sdk-js/pull/1831 .  If you have a chance could you try that branch?  It will hopefully be a part of next release.

**Comment by andreisergiu98** [comment] 2021-11-25 15:51
Hi! Thank you for your response!
We tried out your PR and while streams are rendered correctly we encountered some disconnections when we call `chooseRemoteVideoSources` multiple times in rapid succession (both on firefox and chrome).

```
2021-11-25T14:26:58.909Z [WARN] SDK - SubscribeAndReceiveSubscribeAckTask connection was terminated with code 1006 and reason:  console.js:107:15
2021-11-25T14:26:58.911Z [WARN] SDK - will retry due to status code TaskFailed and error: SubscribeAndReceiveSubscribeAckTask connection was terminated with code 1006 and reason:  console.js:107:15
2021-11-25T14:27:13.819Z [WARN] SDK - will retry due to status code TaskFailed and error: serial group task AudioVideoUpdate/ece79267-bcc6-4f24-a2ae-0be994220706/9b484ffd-aef6-7629-aaa9-ea14a146437e was canceled due to subtask AudioVideoUpdate/ece79267-bcc6-4f24-a2ae-0be994220706/9b484ffd-aef6-7629-aaa9-ea14a146437e/Timeout15000ms error: serial group task AudioVideoUpdate/ece79267-bcc6-4f24-a2ae-0be994220706/9b484ffd-aef6-7629-aaa9-ea14a146437e/Timeout15000ms/UpdateSession was canceled due to subtask AudioVideoUpdate/ece79267-bcc6-4f24-a2ae-0be994220706/9b484ffd-aef6-7629-aaa9-ea14a146437e/Timeout15000ms/UpdateSession/SubscribeAndReceiveSubscribeAckTask error: SubscribeAndReceiveSubscribeAckTask got canceled while waiting for SdkSubscribeAckFrame
```
Also I forgot to mention that streams from the upper region are paused for an instant when calling `chooseRemoteVideoSources`, this happens only on firefox with or without applying the pr.

> Thanks for the report. For our investigation, could you describe how you are binding the tiles? Are you reusing Video HTML elements?

We are not reusing video elements. We render streams in two places, the "audience" which is the scrollable list at the bottom and the "spotlight" the big streams in the upper region from the video we attached. Tiles are always bound in the audience, but sometimes we need to also render them in the spotlight. Since `bindVideoElement` doesn't support binding of more than one element we tried a couple of methods to work around this. In the audience we use `bindVideoElement`, almost identical to how the react sdk handles this. In the spotlight we use the bound video stream from the state of the tile and assign it to srcObject. Also when a video is rendered in the spotlight, it is never unbound in the audience, and it is never removed from priority provider, even when not visible. We also tried to `bindVideoElement` both in spotlight and audience and it works, but we don't know how future proof it is since it is not supported. We don't really know which method is best and we couldn't find this scenario documented.

Here is a snippet with how we handle this.

```TypeScript
import {HTMLProps, useEffect, useRef} from "react";
import {useApplyVideoObjectFit, useAudioVideo} from "amazon-chime-sdk-component-library-react";
import {AudioVideoObserver} from "amazon-chime-sdk-js";

interface Props extends Omit<HTMLProps<HTMLVideoElement>, "ref"> {
    tileId?: number | null;
    objectFit?: boolean;
    onResize?: (width: number, height: number) => void;
    copyStream?: boolean;
}

export function RemoteVideoAudience(props: Props) {
    const {className, tileId, objectFit, onResize, ...rest} = props;

    const audioVideo = useAudioVideo();

    const nullRef = useRef<HTMLVideoElement>(null);
    const videoRef = useRef<HTMLVideoElement>(null);

    useApplyVideoObjectFit(objectFit !== false ? videoRef : nullRef);

    useEffect(() => {
        if (!audioVideo || tileId == null || !videoRef.current) {
            return;
        }

        const videoEl = videoRef.current;

        audioVideo.bindVideoElement(tileId, videoEl);

        const tile = audioVideo.getVideoTile(tileId);

        const observer: AudioVideoObserver = {
            videoTileDidUpdate(state) {
                if (tileId !== state.tileId) {
                    return;
                }

                if (state.paused) {
                    tile?.unpause();
                }
            },
        };

        audioVideo.addObserver(observer);

        const onVideoResize = () => {
            const width = videoEl.videoWidth;
            const height = videoEl.videoHeight;

            if (width && height) {
                onResize?.(width, height);
            }
        };

        videoEl.addEventListener("resize", onVideoResize);

        return () => {
            audioVideo.removeObserver(observer);
            videoEl.removeEventListener("resize", onVideoResize);
            const tile = audioVideo.getVideoTile(tileId);
            if (tile) {
                audioVideo.unbindVideoElement(tileId);
            }
        };
    }, [audioVideo, tileId, onResize]);

    return (
        <video
            {...rest}
            ref={videoRef}
            muted
            autoPlay
            playsInline
            controls={false}
            disablePictureInPicture
            className={`ch-remote-video--${tileId} ${className || ""}`}
            style={{borderRadius: 10, userSelect: "none", pointerEvents: "none"}}
        />
    );
}

export function RemoteVideoSpotlight(props: Props) {
    const {className, tileId, objectFit, ...rest} = props;

    const audioVideo = useAudioVideo();

    const nullRef = useRef<HTMLVideoElement>(null);
    const videoRef = useRef<HTMLVideoElement>(null);

    useApplyVideoObjectFit(objectFit !== false ? videoRef : nullRef);

    // bind copied stream
    useEffect(() => {
        if (!audioVideo || tileId == null || !videoRef.current) {
            return;
        }

        const videoEl = videoRef.current;

        const replaceStream = (stream?: MediaStream | null) => {
            if (stream) {
                videoEl.srcObject = stream;
                videoEl.play().catch(() => {
                    // do nothing
                });
            } else {
                videoEl.srcObject = null;
            }
        };

        let stream: MediaStream | null;

        const tile = audioVideo.getVideoTile(tileId);
        if (tile) {
            stream = tile.state().boundVideoStream;
            replaceStream(stream);
        }

        const observer: AudioVideoObserver = {
            videoTileDidUpdate: (state) => {
                if (state.tileId !== tileId) {
                    return;
                }

                stream = state.boundVideoStream;
                replaceStream(stream);
            },
            videoTileWasRemoved: (removedTileId) => {
                if (tileId === removedTileId) {
                    replaceStream(null);
                }
            },
        };

        audioVideo.addObserver(observer);

        return () => {
            replaceStream(null);
            audioVideo.removeObserver(observer);
        };
    }, [audioVideo, tileId]);

    return (
        <video
            {...rest}
            ref={videoRef}
            muted
            autoPlay
            playsInline
            controls={false}
            disablePictureInPicture
            className={`ch-remote-video--${tileId} ${className || ""}`}
            style={{borderRadius: 10, userSelect: "none", pointerEvents: "none"}}
        />
    );
}

```

**Comment by hensmi-amazon** [comment] 2021-11-29 18:47
Thanks for the try, and the code snippet.  I do not think the issue is related to reusing elements (moreso just the stale transceiver issue), but just wanted to check.  I will take a look at repro, could be related to needed more effort in cleaning up stale transceivers.

**Comment by hensmi-amazon** [comment] 2021-11-30 20:40
I've updated https://github.com/aws/amazon-chime-sdk-js/pull/1831/files to use `stop` (which required some more workarounds for browser quirks).  Note that I had to make a change to backend which won't be deployed until next week, so for testing you can use https://github.com/aws/amazon-chime-sdk-js/tree/no-reuse-transceivo-with-munge (explained in PR).

**Comment by hensmi-amazon** [comment] 2022-01-24 22:41
Pardon the delay. https://github.com/aws/amazon-chime-sdk-js/pull/1831 was finally merged, will be included in 2.26 and hopefully makes this issue impossible. Please let us know if you still see it after picking up that change. I will close this issue on 2.26 release.

**Comment by hensmi-amazon** [comment] 2022-01-27 22:27
Argh...so sorry about all of this. I had finally gotten #1831 in close to us wanting to release 2.26 and it turns out there was an additional regression that I hadn't caught (or maybe some new interaction with some change over the past 2 months), so I am just reverting in #1965 to unblock. I will get it in 2.27 though.

**Comment by hensmi-amazon** [comment] 2022-02-18 23:13
Finally released.

**Closed by hensmi-amazon** 2022-02-18 23:13 UTC
Labels: video
