### ISSUE TITLE
Occasionally cannot start the meeting on Chrome

### ISSUE THREAD

**Issue by haofiltered** [aws/amazon-chime-sdk-js#2033] opened 2022-02-17 15:15 UTC
### What happened and what did you expect to happen?

Occasionally cannot start the meeting on Chrome. The `audioVideoDidStart` will never be triggered when this happened. `videoTileDidUpdate` can received `localTile` data, but local camera will not be on. And cannot join the meeting session to see other people.

I could join the meeting using Firefox or any other browsers, and restart Chrome could solve this issue, but I don't think this should be a browser issue. I tested all my hardware are working and I can join google meet without restart the Chorme. 

### Have you reviewed our existing documentation?

- [X] GitHub [issues](https://github.com/aws/amazon-chime-sdk-js/issues)
- [X] FAQs [page](https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html)
- [X] README [page](https://github.com/aws/amazon-chime-sdk-js#amazon-chime-sdk-for-javascript)
- [X] Feature-specific [guides](https://github.com/aws/amazon-chime-sdk-js#guides)

### Reproduction steps

No idea how to reproduce this, this happens occasionally to everyone.

### Amazon Chime SDK for JavaScript version

2.25.0

### What browsers are you seeing the problem on?

Chrome

### Browser version

Version 98.0.4758.80 (Official Build) (arm64)

### Browser console logs

[2022-02-17T14:57:40.582Z [INFO] MyLogger.txt](https://github.com/aws/amazon-chime-sdk-js/files/8089727/2022-02-17T14.57.40.582Z.INFO.MyLogger.txt)

**Comment by xuesichao** [comment] 2022-02-17 18:19
Hi @haofiltered. I don't think we've had similar issues so far, could you try to update your Chrome and "amazon-chime-sdk-js" to the latest version and see if it helps?

**Comment by haofiltered** [comment] 2022-02-17 19:15
@devalevenkatesh 
Yes, that's exactly the issue is. I am pretty sure that I'm under a stable and good network, I can join the meeting using firefox with the same machine under the same network when this happened on Chrome. 

Not sure what's the cause of that signaling failed to establish, but definitely worth investigating here.

@xuesichao 
Thanks for your reply, like I mentioned on the issue description, restart/update chrome will solve the problem. But this will happen again after couple days. It's would be annoying to tell customers to restart their browser whenever this happens.
There is a [reason](https://github.com/aws/amazon-chime-sdk-js/pull/1831#issuecomment-1035098345) I have to downgrade my chime version back to 2.25.0.
And this is not our first time seeing this, it's happened many times on different users' machines in the past, which means it happened for multiple chime SDK versions as well (We update our packages weekly). 

Really appreciate your time and effort to look into this issue.

**Comment by xuesichao** [comment] 2022-02-18 19:21
@haofiltered Hi, we confirmed with the team that this is same issue as #1985.
The fix (#1993) has been released in `amazon-chime-sdk-js@2.27.0`.

I think you need to wait until this [fix](https://github.com/aws/amazon-chime-sdk-js/pull/1831#issuecomment-1040761318) is deployed and upgrade your `amazon-chime-sdk-js` to `2.27.0` to solve this issue.

**Comment by OliverwengFiltered** [comment] 2022-02-18 20:00
@xuesichao 

it looks like amazon-chime-sdk-js latest public version is 2.27.0

so the fix has been included in the latest version already, is it correct ?

**Comment by xuesichao** [comment] 2022-02-18 20:07
@OliverwengFiltered Yes, the fix for this issue is already in 2.27.0.

**Closed** 2022-02-19 00:17 UTC
