### ISSUE TITLE
Incorrect check for `screenShareUnsupported`

### ISSUE THREAD

**Issue by ReneS1991** [aws/amazon-chime-sdk-js#301] opened 2020-04-23 08:59 UTC
**Detected problem**
I want to show a 'present' button when a user is able to share his/her screen. I want to use the method `screenShareUnsupported` in the DefaultBrowserBehavior, https://github.com/aws/amazon-chime-sdk-js/blob/master/src/browserbehavior/DefaultBrowserBehavior.ts#L101. However, as can be seen in the linked file, it only checks whether the browser is Safari or not, while other browsers on for example a mobile device doesn't support screen sharing either.

Next to that, when I use Safari (13.1) on MAC (10.15.4) it actually does support screen sharing, so that would mean the method is incorrect about Safari as well.

Also, on an Android device in chrome the `screenShareUnsupported` will return `true` while it should be `false`. 

**Screenshot**

As you can see in below screenshot, screen sharing is supported in Safari as this presentation is done from Safari.

![image](https://user-images.githubusercontent.com/17007821/80079596-c8257f80-8550-11ea-9c0b-36581da76f2a.png)

**Platform**
 - OS: Mac OS 10.15.4
 - Browser: Safari
 - Browser Version: 13.1

**Expected behavior**
The `screenShareUnsupported` shouldn't just check for Safari but do an actual check of whether screen sharing is supported or not on the used device/browser.

**Comment by simmkyu** [comment] 2020-04-23 17:55
Chime SDK is using `BrowserBehavior.screenShareUnsupported` only for legacy screen sharing. You will get the following warning message if you call legacy screen share and view APIs. 

```
ScreenShareFacade has been deprecated and will be removed beginning
with version 2.0.0. Instead use the startContentShareFromScreenCapture() and stopContentShare() methods on the AudioVideoFacade
```

Content-based screen sharing supports Safari too. (I guess you are using the content-share API).
https://github.com/aws/amazon-chime-sdk-js#screen-and-content-share

Chime SDK doesn't officially support mobile browsers yet, so `BrowserBehavior` doesn't check for mobile use cases. We'll update the behavior component as we support more browsers.
[Amazon Chime SDK for JavaScript Supported Browsers](https://docs.aws.amazon.com/chime/latest/dg/meetings-sdk.html#mtg-browsers)

**Comment by ltrung** [comment] 2020-05-19 19:25
Closing since this is not a bug.

**Closed by ltrung** 2020-05-19 19:25 UTC
Labels: bug

**Comment by Aarondorn2** [comment] 2021-01-10 03:19
Can this be reopened or should I open a new one?  It looks like mobile devices are now officially supported?
https://docs.aws.amazon.com/chime/latest/dg/meetings-sdk.html#mtg-browsers

I also would like to be able to detect when content sharing is available for a given browser so I can conditionally offer this.  I did not see a convenience method added to DefaultBrowserBehavior.  It does not appear that there is a conditional check in the demo application for browser support either.
