### ISSUE TITLE
I am using amazon-chime with Cordova, and camera is not working in iOS.

### ISSUE THREAD

**Issue by thedeephakani** [aws/amazon-chime-sdk-js#1055] opened 2021-02-10 14:29 UTC
**Describe the bug**
In Cordova, the android app is working fine, even if in the safari browser it's working. but for the ios app(created using Cordova), asking for permission (camera and microphone). after allowing access. 
navigator.mediaDevices.enumerateDevices() retun empty deviceId. 

**Screenshots**
![WhatsApp Image 2021-02-10 at 6 36 00 PM](https://user-images.githubusercontent.com/62884815/107522970-42a3b680-6bda-11eb-9270-fc32396d288e.jpeg)

**Comment by ltrung** [comment] 2021-02-10 18:18
@thedeephakani I am not familiar with Cordova but what iOS version are you testing on?

**Comment by thedeephakani** [comment] 2021-02-11 04:54
> @thedeephakani I am not familiar with Cordova but what iOS version are you testing on? Are you using this library by any chance https://github.com/cordova-rtc/cordova-plugin-iosrtc ? If I remember correctly, Cordova uses WKWebView which does not support webRTC.
> For iOS and Android, chime SDK also has our own native library that you can check out https://github.com/aws/amazon-chime-sdk-ios and https://github.com/aws/amazon-chime-sdk-android

i am testing in iPhone Xs,  OS 14.3,

**Comment by ltrung** [comment] 2021-02-11 05:27
Yeah, it seems the issue is with the framework. Do you use https://github.com/cordova-rtc/cordova-plugin-iosrtc?

**Comment by thedeephakani** [comment] 2021-02-11 12:13
tyred, that but it's always going into cache block. with an empty error.

**Comment by p-foucht** [comment] 2021-02-15 17:31
This sounds like an issue that needs to filed in the cordova webRTC library. If `navigator.mediaDevices.enumerateDevices` is not returning any devices, then the webRTC library seems to be failing.

I am going to close this issue, as there's no action we can take on our end. Feel free to reopen, or update this ticket with the corresponding Cordova webRTC ticket for others to follow and we can link to it for documentation purposes.

**Closed by p-foucht** 2021-02-15 17:31 UTC

**Comment by edudesouza** [comment] 2021-03-25 19:53
Hi there as far as I know, IOS uses Safari, and Safari do no not has support for webrtc. I have this problem on Zoom web sdk, so i think is the same problem here.

**Comment by michhyun1** [comment] 2021-03-25 20:46
Cordova uses the 'ios-webview' user agent, which we do not support as of now. We did recently release support for ios chrome and ios firefox, both of which now support webrtc.

**Comment by TheAnkurPanchani** [comment] 2021-03-26 06:26
This was implementation problem. `enumerateDevices` started working, once we integrated [cordova-plugin-iosrtc](https://github.com/cordova-rtc/cordova-plugin-iosrtc) properly. Though chime sdk had couple of issues. Fix of one is on master, [more info here, issue 1103](https://github.com/aws/amazon-chime-sdk-js/issues/1103), and one is being internally tracked, [more info here, issue 1116](https://github.com/aws/amazon-chime-sdk-js/issues/1116). I have implemented temporary fix of second issue on [a fork, here](https://github.com/TheAnkurPanchani/amazon-chime-sdk-js), feel free to check that out. At the moment, implementation looks stable and working without any issues.

**Comment by michhyun1** [comment] 2021-05-20 22:07
FYI - the Chime SDK for Javascript now support WKWebViews. https://aws.amazon.com/about-aws/whats-new/2021/05/wkwebview-now-supported-with-amazon-chime-sdk-for-javascript/
