### ISSUE TITLE
MeetingSessionConfiguration Case Sensitive Issue

### ISSUE THREAD

**Issue by rohitranjan1991** [aws/amazon-chime-sdk-js#469] opened 2020-06-10 12:20 UTC
**Timeline**
Outline the main actions the user performed and when:

* Create a meeting from the java backend using the AWS Java 2.0 SDK
* Send the meeting response to the browser

**Describe the bug**
The meeting configuration created from the java AWS SDK 2.0 has lower case keys while the Client SDK uses the upper case keys 

Response from the CreateMeeting API in Java 

```
    "meeting" : {
        "mediaRegion" : "us-east-1",
        "mediaPlacement" : {
            "audioHostUrl" : "12b9b7138ca200151d0d89bbafae0430.k.m1.ue1.app.chime.aws:3478",
            "audioFallbackUrl" : "wss://haxrp.m1.ue1.app.chime.aws:443/calls/397be264-8568-4b41-8378-6b0dee060ab3",
            "screenDataUrl" : "wss://bitpw.m1.ue1.app.chime.aws:443/v2/screen/397be264-8568-4b41-8378-6b0dee060ab3",
            "screenSharingUrl" : "wss://bitpw.m1.ue1.app.chime.aws:443/v2/screen/397be264-8568-4b41-8378-6b0dee060ab3",
            "screenViewingUrl" : "wss://bitpw.m1.ue1.app.chime.aws:443/ws/connect?passcode=null&viewer_uuid=null&X-BitHub-Call-Id=397be264-8568-4b41-8378-6b0dee060ab3",
            "signalingUrl" : "wss://signal.m1.ue1.app.chime.aws/control/397be264-8568-4b41-8378-6b0dee060ab3",
            "turnControlUrl" : "https://ccp.cp.ue1.app.chime.aws/v2/turn_sessions"
        },
        "meetingId" : "397be264-8568-4b41-8378-6b0dee060ab3"
    },
```

where as the client SDK requires the above keys in upper case
File: **MeetingSessionConfiguration**
"amazon-chime-sdk-js": "^1.8.0"

```
...
  this.meetingId = createMeetingResponse.MeetingId;
            this.urls = new MeetingSessionURLs_1.default();
            this.urls.audioHostURL = createMeetingResponse.MediaPlacement.AudioHostUrl;
            this.urls.screenDataURL = createMeetingResponse.MediaPlacement.ScreenDataUrl;
            this.urls.screenSharingURL = createMeetingResponse.MediaPlacement.ScreenSharingUrl;
            this.urls.screenViewingURL = createMeetingResponse.MediaPlacement.ScreenViewingUrl;
            this.urls.signalingURL = createMeetingResponse.MediaPlacement.SignalingUrl;
            this.urls.turnControlURL = createMeetingResponse.MediaPlacement.TurnControlUrl;
...
```

**Platform**
 - OS: Mac
 - Browser: Chrome
 - Browser Version: latest
 - Amazon Chime SDK GitHub Commit:

**Comment by ltrung** [comment] 2020-06-12 01:03
This is a duplicate of issue https://github.com/aws/amazon-chime-sdk-js/issues/305

**Closed by ltrung** 2020-06-12 01:03 UTC
