### ISSUE TITLE
window.alert() or window.confirm() cause sending audio to fail.

### ISSUE THREAD

**Issue by NakZMichael** [aws/amazon-chime-sdk-js#2619] opened 2023-04-04 15:38 UTC
### What happened and what did you expect to happen?

After window.alert or window.confirm were called, the audio transmission began to fail on iOS safari and mac safari(on chrome audio sending remains successful).
However, video sending remains successful.
I would like to continue sending audio data after window.alert() is executed, the same as the behavior on chrome.

Also, is there some way to detect the sendingAudioFailed event and reconnect the audio?

### Have you reviewed our existing documentation?

- [X] GitHub [issues](https://github.com/aws/amazon-chime-sdk-js/issues)
- [X] FAQs [page](https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html)
- [X] README [page](https://github.com/aws/amazon-chime-sdk-js#amazon-chime-sdk-for-javascript)
- [X] Feature-specific [guides](https://github.com/aws/amazon-chime-sdk-js#guides)

### Reproduction steps

Deploy the resources in this repository https://github.com/aws-samples/amazon-chime-sdk/tree/main/apps/meeting#to-deploy-the-serverless-device-demo.
Open the web paged deployed by scripts and execute window.alert() on console from developer menu.
Then the audio transmission began to fail on iOS safari and mac safari(on chrome audio sending remains successful).

The first time I encountered this bug was not on the developer menu, but on the actual product when a third party product called window.alert().

### Amazon Chime SDK for JavaScript version

3.10.0

### What browsers are you seeing the problem on?

safari

### Browser version

Mac safari: 14.1.2 , iOS safari: 16.1

### Browser console logs

> window.alert('hoge')
< undefined
[Info] 2023-04-04T15:22:56.745Z [INFO] ChimeComponentLibraryReactDemo - local clock skew estimate=-1ms from ping-pong time=11ms (1234567, line 2)
[Info] 2023-04-04T15:23:01.086Z [INFO] ChimeComponentLibraryReactDemo - attendeePresenceReceived: 86d26209-abaa-d602-4648-0839eae217be (1234567, line 2)
[Info] 2023-04-04T15:23:06.747Z [INFO] ChimeComponentLibraryReactDemo - local clock skew estimate=0ms from ping-pong time=12ms (1234567, line 2)
[Info] 2023-04-04T15:23:16.747Z [INFO] ChimeComponentLibraryReactDemo - local clock skew estimate=0ms from ping-pong time=11ms (1234567, line 2)
[Info] 2023-04-04T15:23:26.431Z [INFO] ChimeComponentLibraryReactDemo - API/DefaultAudioVideoFacade/d6665fe8-2694-4dd2-9530-cda5a68b2713/86d26209-abaa-d602-4648-0839eae217be/startAudioInput "4854FED1C7933A936328E7D51BFED0EFAEAB8384" (1234567, line 2)
[Info] 2023-04-04T15:23:26.435Z [INFO] ChimeComponentLibraryReactDemo - Choosing intrinsic audio input device 4854FED1C7933A936328E7D51BFED0EFAEAB8384 (1234567, line 2)
[Info] 2023-04-04T15:23:26.436Z [INFO] ChimeComponentLibraryReactDemo - reusing existing audio input device (1234567, line 2)
[Info] 2023-04-04T15:23:26.436Z [INFO] ChimeComponentLibraryReactDemo - API/DefaultDeviceController/startAudioInputDevice "4854FED1C7933A936328E7D51BFED0EFAEAB8384" -> "success" (1234567, line 2)
[Info] 2023-04-04T15:23:26.442Z [INFO] ChimeComponentLibraryReactDemo - Received meeting event in MeetingEventObserver: {"name":"audioInputSelected","attributes":{"attendeeId":"86d26209-abaa-d602-4648-0839eae217be","browserMajorVersion":"16","browserName":"Mobile Safari","browserVersion":"16.1","deviceName":"Apple iPhone","externalMeetingId":"1234567","externalUserId":"a40a6677-335a-47f7-89a4-7cfae8fefcf6","meetingHistory":[{"name":"meetingStartRequested","timestampMs":1680621742253},{"name":"audioInputSelected","timestampMs":1680621742292},{"name":"meetingStartSucceeded","timestampMs":1680621743143},{"name":"sendingAudioFailed","timestampMs":1680621746265},{"name":"audioInputSelected","timestampMs":1680621751310},{"name":"attendeePresenceReceived","timestampMs":1680621751423},{"name":"sendingAudioRecovered","timestampMs":1680621751948},{"name":"receivingAudioDropped","timestampMs":1680621757949},{"name":"audioInputSelected","timestampMs":1680621806437}],"meetingId":"d6665fe8-2694-4dd2-9530-cda5a68b2713","osName":"iOS","osVersion":"16.1.1","sdkVersion":"3.10.0","sdkName":"amazon-chime-sdk-js","timestampMs":1680621806437}} (1234567, line 2)
[Warning] 2023-04-04T15:23:26.726Z [WARN] ChimeComponentLibraryReactDemo - reconnection recommended due to: no packets received: true, missed pongs: false, bad audio delay: false (1234567, line 2)
[Info] 2023-04-04T15:23:26.726Z [INFO] ChimeComponentLibraryReactDemo - Reconnection Health value is now 0 (1234567, line 2)
[Info] 2023-04-04T15:23:26.727Z [INFO] ChimeComponentLibraryReactDemo - handling status: ConnectionHealthReconnect (1234567, line 2)
[Warning] 2023-04-04T15:23:26.728Z [WARN] ChimeComponentLibraryReactDemo - will retry due to status code ConnectionHealthReconnect (1234567, line 2)
[Warning] 2023-04-04T15:23:26.728Z [WARN] ChimeComponentLibraryReactDemo - Sending Audio is unhealthy for 2 seconds consecutively. (1234567, line 2)
[Info] 2023-04-04T15:23:26.728Z [INFO] ChimeComponentLibraryReactDemo - Sending Audio Health value is now 0 (1234567, line 2)
[Info] 2023-04-04T15:23:26.730Z [INFO] ChimeComponentLibraryReactDemo - Received meeting event in MeetingEventObserver: {"name":"sendingAudioFailed","attributes":{"attendeeId":"86d26209-abaa-d602-4648-0839eae217be","browserMajorVersion":"16","browserName":"Mobile Safari","browserVersion":"16.1","deviceName":"Apple iPhone","externalMeetingId":"1234567","externalUserId":"a40a6677-335a-47f7-89a4-7cfae8fefcf6","meetingHistory":[{"name":"meetingStartRequested","timestampMs":1680621742253},{"name":"audioInputSelected","timestampMs":1680621742292},{"name":"meetingStartSucceeded","timestampMs":1680621743143},{"name":"sendingAudioFailed","timestampMs":1680621746265},{"name":"audioInputSelected","timestampMs":1680621751310},{"name":"attendeePresenceReceived","timestampMs":1680621751423},{"name":"sendingAudioRecovered","timestampMs":1680621751948},{"name":"receivingAudioDropped","timestampMs":1680621757949},{"name":"audioInputSelected","timestampMs":1680621806437},{"name":"sendingAudioFailed","timestampMs":1680621806729}],"meetingId":"d6665fe8-2694-4dd2-9530-cda5a68b2713","osName":"iOS","osVersion":"16.1.1","sdkVersion":"3.10.0","sdkName":"amazon-chime-sdk-js","timestampMs":1680621806729,"meetingDurationMs":63585,"signalingOpenDurationMs":696,"iceGatheringDurationMs":79,"attendeePresenceDurationMs":9170,"meetingStartDurationMs":890}} (1234567, line 2)
[Info] 2023-04-04T15:23:26.748Z [INFO] ChimeComponentLibraryReactDemo - local clock skew estimate=0ms from ping-pong time=11ms (1234567, line 2)
[Warning] 2023-04-04T15:23:26.748Z [WARN] ChimeComponentLibraryReactDemo - reconnection recommended due to: no packets received: true, missed pongs: false, bad audio delay: false (1234567, line 2)
[Info] 2023-04-04T15:23:27.137Z [INFO] ChimeComponentLibraryReactDemo - transitioning from Connected to Connecting with Reconnect (1234567, line 2)
[Info] 2023-04-04T15:23:27.139Z [INFO] ChimeComponentLibraryReactDemo - running task AudioVideoReconnect/d6665fe8-2694-4dd2-9530-cda5a68b2713/86d26209-abaa-d602-4648-0839eae217be (1234567, line 2)
.
.
.
[Info] 2023-04-04T15:24:19.066Z [INFO] ChimeComponentLibraryReactDemo - peer connection state changed: connected (1234567, line 2)
[Warning] 2023-04-04T15:24:26.765Z [WARN] ChimeComponentLibraryReactDemo - Sending Audio is unhealthy for 2 seconds consecutively. (1234567, line 2)
[Warning] 2023-04-04T15:24:26.765Z [WARN] ChimeComponentLibraryReactDemo - SendingAudioFailure health policy maximum warnings breached. Falling back to reporting healthy. (1234567, line 2)
[Warning] 2023-04-04T15:24:27.765Z [WARN] ChimeComponentLibraryReactDemo - Sending Audio is unhealthy for 2 seconds consecutively. (1234567, line 2)
[Warning] 2023-04-04T15:24:27.766Z [WARN] ChimeComponentLibraryReactDemo - SendingAudioFailure health policy maximum warnings breached. Falling back to reporting healthy. (1234567, line 2)
[Warning] 2023-04-04T15:24:28.766Z [WARN] ChimeComponentLibraryReactDemo - Sending Audio is unhealthy for 2 seconds consecutively. (1234567, line 2)
[Warning] 2023-04-04T15:24:28.767Z [WARN] ChimeComponentLibraryReactDemo - SendingAudioFailure health policy maximum warnings breached. Falling back to reporting healthy. (1234567, line 2)
[Info] 2023-04-04T15:24:28.890Z [INFO] ChimeComponentLibraryReactDemo - local clock skew estimate=0ms from ping-pong time=12ms (1234567, line 2)
[Warning] 2023-04-04T15:24:28.891Z [WARN] ChimeComponentLibraryReactDemo - Sending Audio is unhealthy for 2 seconds consecutively. (1234567, line 2)
[Warning] 2023-04-04T15:24:28.891Z [WARN] ChimeComponentLibraryReactDemo - SendingAudioFailure health policy maximum warnings breached. Falling back to reporting healthy. (1234567, line 2)
[Warning] 2023-04-04T15:24:29.766Z [WARN] ChimeComponentLibraryReactDemo - Sending Audio is unhealthy for 2 seconds consecutively. (1234567, line 2)
[Warning] 2023-04-04T15:24:29.767Z [WARN] ChimeComponentLibraryReactDemo - SendingAudioFailure health policy maximum warnings breached. Falling back to reporting healthy. (1234567, line 2)
[Warning] 2023-04-04T15:24:30.768Z [WARN] ChimeComponentLibraryReactDemo - Sending Audio is unhealthy for 2 seconds consecutively. (1234567, line 2)
[Warning] 2023-04-04T15:24:30.768Z [WARN] ChimeComponentLibraryReactDemo - SendingAudioFailure health policy maximum warnings breached. Falling back to reporting healthy. (1234567, line 2)
[Warning] 2023-04-04T15:24:31.787Z [WARN] ChimeComponentLibraryReactDemo - Sending Audio is unhealthy for 2 seconds consecutively. (1234567, line 2)

**Comment by devalevenkatesh** [comment] 2023-04-06 01:14
I tested the `window.alert()` on an official WebRTC sample for audio showing volume in Safari:
https://webrtc.github.io/samples/src/content/getusermedia/volume/

And there once the `window.alert()` is called, then no audio auto plays there after showing no indication on volume bars. In Firefox and Chrome, they stop for the alert but show audio changes fine once alert is confirmed.

Thus, I believe this is not a JS SDK specific issue. Given the connection is driven using audio in JS SDK and if audio fails to be connected, JS SDK will try to reconnect. Since in Safari it seems that the audio never plays once alert is confirmed, JS SDK never reconnects.

In JS SDK, yourself may not generally need to reconnect audio. But I think you can implement `eventDidReceive` `AudioVideoObserver` and check for `sendingAudioFailed` event. Related docs: https://aws.github.io/amazon-chime-sdk-js/modules/meetingevents.html

I will check more on this from Safari side whether something can be handled in JS SDK itself but at this point it looks like Safari specific browser behavior.

Reconnection behavior in JS SDK: https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html#when-does-the-amazon-chime-sdk-retry-the-connection-can-i-customize-this-retry-behavior

**Comment by devalevenkatesh** [comment] 2023-04-06 22:05
Did some further testing and found that this is an issue only when using Web audio. If you are not using Amazon Voice Focus, I suggest toggling the Web Audio off when joining a meeting. I am checking further.

**Comment by simmkyu** [comment] 2023-04-07 00:24
As @devalevenkatesh pointed out, AudioContext nodes stop to play or route audio in Safari as soon as the `window.alert` API is invoked. We suggest disabling the Chime SDK's Web Audio feature when using the `window.alert` or `window.confirm` API. In the meantime, we will investigate the WebKit issues and provide updates.

The following example using the AudioContext API in your browser adds a button to your web application.

1. Execute the code snippet in your web application or within the browser console.
1. Click the "Play audio" button to play the sound using the browser's [OscillatorNode](https://developer.mozilla.org/en-US/docs/Web/API/OscillatorNode) API.
1. Click the "Call window.alert" button to call the `window.alert` API.

```js
(() => {
  const button = document.createElement('button');
  button.innerText = 'Play audio';
  button.style = 'position: fixed; top:0; left:0; z-index:9999';
  document.body.appendChild(button);

  let isPlaying = false;
  button.addEventListener('click', async () => {
    if (isPlaying) {
      window.alert('Alert!');
    } else {
      isPlaying = true;
      button.innerText = 'Call window.alert';
      const audioContext = new (window.AudioContext || window.webkitAudioContext)();
      const oscillator = audioContext.createOscillator();
      oscillator.type = 'square';
      oscillator.frequency.setValueAtTime(440, audioContext.currentTime); // value in hertz
      oscillator.connect(audioContext.destination);
      oscillator.start();
    }
  });
})();

```

## Observed behaviors

Browser | Behaviors
--|--
Chrome 111.0.5563.146 | The audio continues to play without any pauses.
Firefox 111.0.1 | The audio stops while the dialogue is visible, but resumes playing after the dialogue is closed.
Safari 16.4 | The audio stops playing as soon as the dialogue appears.

**Comment by simmkyu** [comment] 2023-04-07 02:17
I submitted a ticket to the WebKit Bugzilla, as I was unable to find any relevant bugs:
https://bugs.webkit.org/show_bug.cgi?id=255134

**Comment by NakZMichael** [comment] 2023-04-07 14:58
@devalevenkatesh 
Thanks for your response.
On the sample code, I was able to confirm that disabling the WebAudio feature no longer causes this problem.
But if VideoFocus is not used, the sound quality goes down 😢 
We also use WebAudio in our product, so I will try turning it off and see if that solves the problem.

**Comment by NakZMichael** [comment] 2023-04-07 15:09
@simmkyu 
Thanks for your research and submission of a ticket to the WebKit Bugzilla.
Even if Apple fixes this bug, it will only affect users of the latest OS version, right?
Or could we work around this problem by using the amazon-chime-sdk-js API properly?

**Comment by devalevenkatesh** [comment] 2023-04-08 00:21
After further checking on no audio, I found that the Web Audio context basically goes into the `suspended` state, the moment you call `window.alert()` and due to Safari's autoplay policies, the audio context is never resumed (back to `running` state).

The current workaround would be to programmatically resume the audio context after the `window.alert` completes:
```
const  audioContext = DefaultDeviceController.getAudioContext();
audioContext.addEventListener('statechange', async () => {
  console.log(`Audio context state change: ${audioContext.state}`);
  // Additionally check for user action for window confirmation or clicking Ok.
  if (audioContext.state === 'suspended') {
    await audioContext.resume();
  }
});
```

I suggest to do this in your application for following reasons:
1. Generally it is best practice to resume or start the audio context based on user control. It would not be ideal to do this in SDK given we do not know why the `audioContext.state` may go into `suspended` state. In this case, its a `window.alert` which is actually application action. https://udn.realityripple.com/docs/Web/API/Web_Audio_API/Best_practices
2. Safari itself should be actually resuming audio context, but, since its not happening @simmkyu has already filed the Webkit bug. If Safari suggests a workaround we will check on implementing it in JS SDK.

A simple demo where the audio context state is printed in console is attached here (found while checking `statechange` event in MDN), you can call `window.alert()` in console and see the audio context state changes:
https://mdn.github.io/webaudio-examples/audiocontext-states/

**Comment by NakZMichael** [comment] 2023-04-09 02:53
@devalevenkatesh 
Thanks for your solution.

I added the button below in App component of the meeting app(https://github.com/aws-samples/amazon-chime-sdk/tree/main/apps/meeting).

```tsx
<button onClick={() => {
  const  audioContext = DefaultDeviceController.getAudioContext();
  audioContext.addEventListener('statechange', async () => {
    console.log(`Audio context state change: ${audioContext.state}`);
    // Additionally check for user action for window confirmation or clicking Ok.
    if (audioContext.state === 'suspended') {
      await audioContext.resume();
    }
  });
}}>Audio</button>
```

I choose these options below and entered meeting.
<img width="482" alt="image" src="https://user-images.githubusercontent.com/61081351/230751653-a3d38e22-e3b4-4828-a936-303310f6d293.png">


Then I clicked this button and called window.alert('hello, world'), logs below are shown.

> [Log] Audio context state change: suspended (meeting-bundle.js, line 196113)
> [Log] Audio context state change: running (meeting-bundle.js, line 196113)
> [Log] Audio context state change: suspended (meeting-bundle.js, line 196113)

However, audio connection was still failed.
Additionally, I clicked the button I added and called window.alert several times and the audio connection was sometimes success and sometimes not.

**Comment by devalevenkatesh** [comment] 2023-04-10 18:56
In your code, on each button you are adding observer for the single `audioContext` so each click is adding many observers and that may be affecting. I suggest to add/remove the observer when the meeting view component mounts.

Looks like, you are using the Amazon Chime SDK component library for React meeting demo. I pushed a remote branch which does that:
https://github.com/aws-samples/amazon-chime-sdk/blob/resume-audio-context/apps/meeting/src/views/Meeting/index.tsx#L27-L44

Make sure that that you enable Web audio as well as enable Voice focus in a meeting. Otherwise, the attendee will drop when `audioContext` suspends due to `window.alert`.

Testing steps:
1. Run the meeting demo and  check "Enable web audio"
2. When joined in a meeting, click "Enable Voice Focus" for the selected audio input device.
3. Then in Safari browser console, execute `window.alert()` and then click "close", you should see the audio context state going from `suspended` to `running` and then the audio also going fine.

Note that, if you do not enable Voice focus, then, the attendee will just drop. So suggest enabling web audio for Amazon Chime SDK meeting only if you want to use Amazon Voice focus.

Overall, I think with Safari probably its better to have your own custom UI for `window.alert` like mechanism. And yes, the audio sending will fail until the popup is closed.

**Comment by NakZMichael** [comment] 2023-04-15 18:15
Thank you for your responses.

Libraries developed by other companies use window.alert, which is difficult for us to control.

So that, finally we decided to set enableWebAudio to false.

Thanks.

**Comment by devalevenkatesh** [comment] 2023-06-29 21:37
Since this is outside Amazon Chime SDK for JavaScript's control, I am resolving this issue. The best way to handle this is implementing a custom UI for window.alert like mechanism and we have already a open ticket with Webkit team: https://bugs.webkit.org/show_bug.cgi?id=255134

**Closed by devalevenkatesh** 2023-06-29 21:37 UTC
Labels: Browser Bug
