### ISSUE TITLE
Chime's reconnect behaviour causing AudioJoinedFromAnotherDevice?

### ISSUE THREAD

**Issue by brondibur** [aws/amazon-chime-sdk-js#2784] opened 2023-10-23 12:42 UTC
### What happened and what did you expect to happen?

Got _AudioJoinedFromAnotherDevice_ errors. 
It seems to occur when we have _SignalChannelClosedUnexpectedly_ errors due to network issues and Chime tries to reconnect.

### Have you reviewed our existing documentation?

- [X] GitHub [issues](https://github.com/aws/amazon-chime-sdk-js/issues)
- [X] FAQs [page](https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html)
- [X] README [page](https://github.com/aws/amazon-chime-sdk-js#amazon-chime-sdk-for-javascript)
- [X] Feature-specific [guides](https://github.com/aws/amazon-chime-sdk-js#guides)

### Reproduction steps

Not sure how to reproduce, but we're seeing _SignalChannelClosedUnexpectedly_ errors due to network issues. Chime tries to reconnect but seems to sometimes cause _AudioJoinedFromAnotherDevice_ errors. In the attached logs, it occurs at 14:08. I can share more examples as well.

### Amazon Chime SDK for JavaScript version

3.18.0

### What browsers are you seeing the problem on?

Google Chrome

### Browser version

117.0.0

### Meeting and Attendee ID Information.

Meeting ID: 862fffe2-c523-4c0b-8925-081764852713
Attendee IDs:
  - f5d665d4-fe1a-0ea4-22b1-e4ca3354d7a3
  - f5d665d4-fe1a-0ea4-22b1-e4ca3354d7a3#content

### Browser console logs

[ChimeMeetingLogs2.csv](https://github.com/aws/amazon-chime-sdk-js/files/13191964/ChimeMeetingLogs2.csv)

**Comment by brondibur** [comment] 2023-10-27 18:15
### What happened and what did you expect to happen?

The _AudioJoinedFromAnotherDevice_ errors are happening on Chrome as well, even when the device is open and working. It seems to occur when we have _SignalChannelClosedUnexpectedly_ errors due to network issues. 

### Reproduction steps

We're seeing _SignalChannelClosedUnexpectedly_ errors due to network issues. Chime tries to reconnect but seems to sometimes cause _AudioJoinedFromAnotherDevice_ errors.
In the attached logs, it occurs at 14:08.

### Amazon Chime SDK for JavaScript version

3.18.0

### What browsers are you seeing the problem on?

Google Chrome

### Browser version

117.0.0

### Meeting and Attendee ID Information.

Meeting ID: 862fffe2-c523-4c0b-8925-081764852713
Attendee IDs:
  - f5d665d4-fe1a-0ea4-22b1-e4ca3354d7a3
  - f5d665d4-fe1a-0ea4-22b1-e4ca3354d7a3#content

### Browser console logs

[ChimeMeetingLogs2.csv](https://github.com/aws/amazon-chime-sdk-js/files/13191964/ChimeMeetingLogs2.csv)

**Comment by brondibur** [comment] 2023-11-07 12:06
@hensmi-amazon @pracheth @dinmin-amzn Can someone please look into this?

**Comment by Yadukrish** [comment] 2023-12-12 11:25
Any update on this issue? We are experiencing the same issue.

**Comment by PaulGobin** [comment] 2023-12-12 15:08
Hey Team- Our customers are experiencing this issue quite often and support tickets keep coming in.
Any eta on this would be much appreciate.

**Comment by Yadukrish** [comment] 2023-12-12 15:37
Getting this issue after getting reconnected from meeting(more than 15 sec timeout i think).

Issue only occurs for sdk versions > 16.0.0.

**Comment by hensmi-amazon** [comment] 2023-12-12 17:35
Sorry for the delay. `SignalChannelClosedUnexpectedly` was a new event added in 17.x to make the client reconnect faster in case of irrecoverable network disconnection. `AudioJoinedFromAnotherDevice` can occur if the connection occurs too quickly before the other, but I'm not sure how that would reach the client since it's connection was closed already. I think there may be some edge cases during long network disconnections to iron out.

For now I will just revert that change so I can get it out in a release we have planned this week.

Since I wish to eventually reroll that commit, can you clarify the experience? Were clients disconnected longer then they expected? Or were they just receiving that event unexpectedly. Did this occur while content was being shared? While video was being shared? I can see in the provided logs but any more patterns would be helpful.

**Comment by brondibur** [comment] 2023-12-12 19:39
@hensmi-amazon Our clients share audio, video, and content. The issue occurs regularly, and can be caused by network errors due to actual connectivity issues or if they lock their device mid-meeting.
Basically anything that causes `WebSocketClosed` and triggers Chime's retries.
This isn't reproducible on will, but I was able to reproduce it sometimes by briefly turning off wifi during a meeting. I can share more logs if needed.

**Comment by Yadukrish** [comment] 2023-12-13 06:48
Usually this happens when clients disconnected more than 15-20 sec. It occurs even without content sharing and video.  A single audio attendee is enough to reproduce the issue.

**Comment by 4take** [comment] 2023-12-13 16:37
There is a simple method to reproduce this issue. You can use the `Network Link Conditioner,` an extension component in Xcode. Start a call and then change the setting to `Very Bad Network.` Within 15-30 seconds, switch to `Wi-Fi` and wait for a few lines. By doing this, the issue can be reproduced.


<img width="856" alt="image" src="https://github.com/aws/amazon-chime-sdk-js/assets/16110532/ee5bdf36-bf67-428c-aa77-199697a93a51">

**Comment by dylonChime** [comment] 2024-11-04 23:48
This bug has been fixed in version v3.19.0. Please reopen or submit a support case if this is still an issue.

**Closed by dylonChime** 2024-11-04 23:48 UTC
