### ISSUE TITLE
Multiple Content Share doesn't work

### ISSUE THREAD

**Issue by kubiksamek** [aws/amazon-chime-sdk-js#1727] opened 2021-10-27 12:44 UTC
### What happened and what did you expect to happen?

When two attendees are in a meeting and both start content share, only the first one is displayed.

### Have you reviewed our existing documentation?

- [X] GitHub [issues](https://github.com/aws/amazon-chime-sdk-js/issues)
- [X] FAQs [page](https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html)
- [X] README [page](https://github.com/aws/amazon-chime-sdk-js#amazon-chime-sdk-for-javascript)
- [X] Feature-specific [guides](https://github.com/aws/amazon-chime-sdk-js#guides)

### Reproduction steps

1. UserA joins meeting
2. UserB joins meeting
3. UserA starts content share (`audioVideo.startContentShareFromScreenCapture(undefined, 30);`)
 => `const contentShareState = useContentShareState();` return same object for both users
4. UserB sees content share from UserA
5. UserB starts content share (`audioVideo.startContentShareFromScreenCapture(undefined, 30);`)
 => `const contentShareState = useContentShareState();` return new object (new `tileId`) for UserB
 => UserA did not receive new object

**Expected:**
UserA sees content share from UserB => UserA gets new object from `useContentShareState` hook.

### Amazon Chime SDK for JavaScript version

2.19.0

### What browsers are you seeing the problem on?

Google Chrome

### Browser version

95

### Browser console logs

Nothing to see in console log.

**Comment by kubiksamek** [comment] 2021-11-01 10:09
@ltrung Hello, I tried it today again and it works as expected, no code change. We believe that it had to be regression in AWS, because we also noticed different problem on Wednesdey previous week (27/10/2021) that `useRosterState` hook did not return my attendee. This is also fixed now.

Anyway, now when the second user starts content share, it will automatically stop content share in the first user's browser.

**Comment by kubiksamek** [comment] 2021-11-01 13:51
@ltrung Little update: I see this in the console log
```
DefaultDeviceController.js?66c1:1594 The AudioContext was not allowed to start. It must be resumed (or created) after a user gesture on the page. https://goo.gl/7K7WLu
getAudioContext | @ | DefaultDeviceController.js?66c1:1594
```
When I see this, then `useRosterState` returns `{}` without my attendee, same as here https://github.com/aws/amazon-chime-sdk-js/issues/624.

I will create new issues for this.

**Comment by ltrung** [comment] 2021-11-01 15:51
It seems like the issue is that the content share attendee was not be able to connect for the second attendee?

**Comment by kubiksamek** [comment] 2021-11-01 15:56
When I allow Sound in Site settings (second issue), both connect and see each other. But even then, the second user is not able to "steal" content share. It will start a new content share, but only he (the second user) sees it. When the first user stops sharing, he (the first user) will see the content share from the second user.

**Comment by ltrung** [comment] 2021-11-01 16:25
Could you try to reproduce the issue in our [React meeting demo app](https://github.com/aws-samples/amazon-chime-sdk/tree/main/apps/meeting) and [JS SDK meeting demo](https://github.com/aws/amazon-chime-sdk-js/tree/master/demos/browser)?
Also could you try to reproduce it in your app and upload the console log for A and B? If the log contains sensitive information, please open an AWS Support case.

**Comment by kubiksamek** [comment] 2021-11-01 17:48
@ltrung I tried the React meeting demo app and it works as expected. I will investigate more indepth in our app.

**Comment by kubiksamek** [comment] 2021-11-05 16:51
@ltrung So I found out the root cause. We use `VideoPriorityBasedPolicy` to set specific video quality by priorities. But I found out that when the second user starts content share, I receive callback using `AudioVideoObserver.remoteVideoSourcesDidChange` but I do not receive new `sharingAttendeeId` from `useContentShare` hook. After I change my video policy to include new `attendeeId#content` (received from callback) and set it, the hook is updated and I receive new `sharingAttendeeId`.

Is this behavior intended? When I set policy only once (for example to one focused camera user) and someone other starts content share. Even I set my policy to display only that one camera user I would still like to know that `sharingAttendeeId` changed.

In my case, I have a workaround that I include all `#content` attendeeId's to a new policy, set it, after that Chime automatically disables my content share and now I see share from the second user.

**Comment by ltrung** [comment] 2021-11-05 17:34
Nice find. Yes, once you manually set `chooseRemoteVideoSources` you will have to keep updating it to change your preference list. This is the same as when a new user turn on video then you need to manually add him to the list.
The expected workflow is whenever you receive `remoteVideoSourcesDidChange` you will determine your preference using `chooseRemoteVideoSources`.
Closing this issue for now.

**Closed by ltrung** 2021-11-05 17:34 UTC

**Comment by kubiksamek** [comment] 2021-11-05 17:46
I see, Thank you.

**Comment by xuesichao** [comment] 2021-11-05 17:49
Hi @kubiksamek , you check our [video layout guide](https://aws.github.io/amazon-chime-sdk-js/modules/videolayout.html#video-lifecycle-management-apis) to get a high level idea about how the remote video source are rendered.

In general, the steps are:
1. Whenever someone else starts sharing a video stream, the local attendee will receive the callback from `AudioVideoObserver.remoteVideoSourcesDidChange`. 
2. SDK subscribes to these `remoteVideoSources`.
   * By default all the `remoteVideoSources` are subscribed automatically. Since you are using the `VideoPriorityBasedPolicy`, which give you the maximum ability to manage the `VideoSource`, you need to handle the subscription yourself by calling `chooseRemoteVideoSources`.
3. The subscribed `remoteVideoSources` become `VideoTiles`, the update notified by `videoTileDidUpdate`, `  videoTileWasRemoved` callbacks.
4.  Bind these `VideoTiles` to HTML `video` element then they are rendered in the page.

So, `remoteVideoSources` are the remote video sources that are available to be viewed, while `remoteVideoTiles` are the videos that are actually being seen. `useContentShareState` hooks is based on the latter. That's why you didn't see the `sharingAttendeeId` updated when second user starts sharing the content at the first time. Yes, it is intended.

**Comment by kubiksamek** [comment] 2021-11-05 17:52
@xuesichao Thanks for the info.
