### ISSUE TITLE
Preview Local Video Without Creating a Session

### ISSUE THREAD

**Issue by adambyer** [aws/amazon-chime-sdk-js#923] opened 2020-12-03 02:03 UTC
Is it possible to test the local video/audio without creating a meeting session? I see `startVideoPreviewForVideoInput` but that seems to require a session. I would like to allow my users to test their camera and microphone at any time, even days before the meeting. It would be ideal if that could all happen on the client side so that creating a session wasn't needed.

I am considering Chime SDK for a possible replacement for OpenTok in my product. They allow testing video/audio without creating/joining a session. It would be awesome if I could do that with Chime SDK too.

**Comment by bradmanAWS** [comment] 2020-12-03 02:39
Hi @adambyer, have you seen the Meeting Readiness Checker demo application? You can start it up in our demo folder by running `npm run start --app=meetingReadinessChecker` described in this readme. https://github.com/aws/amazon-chime-sdk-js/tree/master/demos/browser

Users can test their browser capabilities here before joining a real session.

**Comment by adambyer** [comment] 2020-12-03 03:33
Thanks @bradmanAWS. It looks like that actually creates a meeting which is what I was hoping to avoid. I was hoping for something that doesn't involve the server at all... just to make sure their camera and microphone are working. I want to make this functionality always available in my app without worrying about charges. I assume if I do something similar to that demo I will incur charges because my app is creating an actual meeting with an attendee.

The way OpenTok and OpenVidu do it is pretty handy because you can go through the process of publishing video/audio without joining a session. So it's all happening on the client side... just making sure the camera/mic are accessible, etc. I suppose I could roll my own solution but it's better when it goes through the same process that the users will ultimately go through when they do join an actual meeting.

Is there any reason that `startVideoPreviewForVideoInput` has to depend on joining a session first?

**Comment by irothschild** [comment] 2020-12-10 14:38
You can create a `DefaultDeviceController` and use that or use `MediaDevices.getUserMedia()` directly.

**Comment by ltrung** [comment] 2020-12-11 03:31
@adambyer Hi Adam, it is possible to use startVideoPreviewForVideoInput without creating a meeting session or hit the back end.
As Brad mentioned in the [meeting readiness checker demo](https://github.com/aws/amazon-chime-sdk-js/blob/4ac2b02c7ef6118de425a486d764ba7221773f15/demos/browser/app/meetingReadinessChecker/meetingReadinessChecker.ts#L414), you can initialize the DefaultDeviceController without initialize the meeting session.

After that you can call chooseVideoInputDevice and startVideoPreviewForVideoInput to show video preview.
```
//Initialize DefaultDeviceController
const deviceController = new DefaultDeviceController(this.logger, { enableWebAudio: true });

//List the video device list
deviceList = await deviceController.listVideoInputDevices();

//Choose video device
deviceController.chooseVideoInputDevice(deviceList[0].deviceId);

//Grab the video element
const videoElement = document.getElementById('video-preview') as HTMLVideoElement;

//Start video preview
deviceController.startVideoPreviewForVideoInput(videoElement);
```

**Comment by ltrung** [comment] 2020-12-11 17:02
Close the issue. Please reopen it if you have any additional questions

**Closed by ltrung** 2020-12-11 17:02 UTC
Labels: Documentation, Question

**Comment by adambyer** [comment] 2020-12-11 17:33
Thanks @ltrung! That is exactly what I needed. I didn't see that in the demos so didn't realize those methods were available directly from the device controller.

Is there also a way to access `realtimeSubscribeToVolumeIndicator` without a session? That one doesn't seem to be available directly from the device controller.

**Comment by adambyer** [comment] 2020-12-23 00:41
Hi @ltrung. Checking in to see if you saw my follow-up question about `realtimeSubscribeToVolumeIndicator`. I'd like to be able to use that to present a volume indicator so the user knows their mic is working. I'm not seeing an option to do that without a session.

**Comment by ltrung** [comment] 2020-12-23 00:51
Sorry I missed your previous comment. Unfortunately `realtimeSubscribeToVolumeIndicator` is intended to be used with meeting session. If you want to do mic check, you can use DefaultDeviceController.createAnalyserNodeForAudioInput as in this demo https://github.com/aws/amazon-chime-sdk-js/blob/2ca3976c99992285954b33755dc617aa3aa0e2cf/demos/browser/app/meetingV2/meetingV2.ts#L1824

**Comment by adambyer** [comment] 2020-12-23 19:30
Thanks @ltrung. That's working well. Is there any event I can use to know when `createAnalyserNodeForAudioInput` will succeed? It fails if I call it immediately after instantiating `DefaultDeviceController`. But it works if I pause for a second. Is there any event I can subscribe to that indicates the video is ready and it's safe to call `createAnalyserNodeForAudioInput`?

**Comment by adambyer** [comment] 2021-01-05 18:00
Hi @ltrung just checking to see if you saw my last question.

**Comment by ltrung** [comment] 2021-01-05 18:12
Is there any error you receive when it fails?

**Comment by adambyer** [comment] 2021-01-05 20:43
@ltrung sorry that was my fault. I was calling `chooseAudioInputDevice` after `createAnalyserNodeForAudioInput`.

**Comment by hungnguyen1412** [comment] 2021-09-30 15:33
@ltrung sorry, can we run the readiness checker without creating a Session?

**Comment by ltrung** [comment] 2021-09-30 15:35
@hungnguyen1412 You can run checker for local audio, video, and speaker without creating an actual session (by passing in a dummy meeting join info).

**Comment by hungnguyen1412** [comment] 2021-10-01 01:42
@ltrung thank you but how the dummy meeting join info? Cause i tried but it's not working.
And we can't run the checker for the content share, network, bandwidth without creating an actual session, right?

**Comment by maruware** [comment] 2022-01-20 04:02
Hi, @ltrung , I wanted to do the same thing, so I followed the instructions below, but the first time the preview shows up as intended, but when I switch devices using deviceController.chooseVideoInputDevice, the preview shows up completely black https://github.com/aws/amazon-chime-sdk-js/issues/923#issuecomment-742943700

I've also tried running stopVideoPreviewForVideoInput after deviceController.chooseVideoInputDevice, and then running startVideoPreviewForVideoInput again, but " I got a warning that says "cannot bind video preview since video input device has not been chosen" and the preview is still black.

Is there any additional steps I need to take?

**Comment by ltrung** [comment] 2022-01-20 21:52
>I've also tried running stopVideoPreviewForVideoInput after deviceController.chooseVideoInputDevice, and then running startVideoPreviewForVideoInput again, but " I got a warning that says "cannot bind video preview since video input device has not been chosen" and the preview is still black.

I think you want to call `stopVideoPreviewForVideoInput` first before calling `deviceController.chooseVideoInputDevice`. `stopVideoPreviewForVideoInput` will release the current video stream (which undo what you just select in `chooseVideoInputDevice`.

**Comment by maruware** [comment] 2022-01-21 00:48
@ltrung I fixed it as you said, and it works as intended. Thanks!

**Comment by ashirkhan94** [comment] 2023-10-19 08:08
Hi @ltrung 
How can I implement it for React Native
Could you please check
[https://github.com/aws-samples/amazon-chime-react-native-demo/issues/198](url)
Thanks
