### ISSUE TITLE
iOS Safari Mobile WebApp permissions not asked (Camera & Microphone)

### ISSUE THREAD

**Issue by JacobWWHosking** [aws/amazon-chime-sdk-js#3013] opened 2024-12-05 00:07 UTC
### What happened and what did you expect to happen?

Expected Outcome: 
1. Safari loads web app. 
2. Safari requests access to Camera & Microphone
3. Safari loads user options
4. User selects
5. User connects

Experienced Outcome:
1. Safari loads web app
2. Safari loads user options
3. User selects
4. User tries to connect but is unable as permissions were never requested and accepted

### Have you reviewed our existing documentation?

- [X] GitHub [issues](https://github.com/aws/amazon-chime-sdk-js/issues)
- [X] FAQs [page](https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html)
- [X] README [page](https://github.com/aws/amazon-chime-sdk-js#amazon-chime-sdk-for-javascript)
- [X] Feature-specific [guides](https://github.com/aws/amazon-chime-sdk-js#guides)

### Reproduction steps

1. Enter domain on Mobile Safari (version 18.1.0)
2. Page loads
3. User selects connection options
4. User trys to connect
5. User is unable as camera and mic permissions never requested or granted

### Amazon Chime SDK for JavaScript version

amazon-chime-sdk-component-library-react@3.9.0 | amazon-chime-sdk-js@3.25.0

### What browsers are you seeing the problem on?

Safari

### Browser version

18.1.0

### Meeting and Attendee ID Information.

N/A

### Browser console logs

N/A

**Comment by ltrung** [comment] 2024-12-06 18:13
Sorry what is the web app are you referring to here?

**Comment by JacobWWHosking** [comment] 2024-12-10 23:55
Hi Trung,

Web app refers to the product's online web implementation on a live demo
server.

Please see response from devs below:

__________________________________________________________________________

Reasons why we were unable to collect all browser logs
1. AWS API Gateway Payload Limits
If you're invoking the Lambda function through API Gateway, note the
following:
REST API: Maximum payload size is 10 MB.
2. Cloudwatch Size limit
 - 1 MB limit for the entire batch of log events
 - 256 KB limit for each individual log event

__________________________________________________________________________


*Jacob Hosking*Head of Product & Development

PADLOKTGLOBAL

(AUS) +61 439 532 646

56 Bowman St | Pyrmont NSW 2009 | Australia

Email: ***@***.***

**Comment by hensmi-amazon** [comment] 2024-12-11 00:39
If you can connect your phone to a MacOS device and get logs by following the steps in this blog: https://www.lifewire.com/activate-the-debug-console-in-safari-445798 . I usually have luck if all devices involved are updated to latest version. But we cannot investigate further without some client side logs, since we cannot reproduce ourselves.

**Comment by JacobWWHosking** [comment] 2024-12-12 03:37
Hi Henry,

This issue only existed with 18.1.0

18.0.1 faced a different issue and 18.1.1 did not have any issues at all

This is more a flagging to let it be known that there were issues
experienced with a certain version number of iOS/Safari.

However, I will have the team follow the steps and use for tests
moving forward.

Regards,


*Jacob Hosking*Head of Product & Development

PADLOKTGLOBAL

(AUS) +61 439 532 646

56 Bowman St | Pyrmont NSW 2009 | Australia

Email: ***@***.***

**Comment by hensmi-amazon** [comment] 2024-12-12 16:31
Got it, I appreciate the call out and this will be useful if we get similar reports in the future! Unfortunately it will be unlikely to be investigated further on our end because it has already been fixed by Apple, and likely is a OS level regression that we would not be able to circumvent. I will close this GH issue for now but will still be able to answer any further questions. Thanks!

**Closed by hensmi-amazon** 2024-12-12 16:31 UTC
Labels: Needs More Information
