### ISSUE TITLE
Audio/Video lag in meeting Sessions

### ISSUE THREAD

**Issue by gmonn** [aws/amazon-chime-sdk-js#1402] opened 2021-06-30 15:39 UTC
We are testing our application before goLive and we are starting to see issues where the audio streams are lagging behind the video streams for meetings. While this appears to be random, we are seeing some of the lag when connecting to the meetings from Chromebooks, Safari 13.1.2 and then some on Chrome as well. 

We have looked through our logs and don't see anything that really sticks out, we have turned on logged from the AudioVideoObserver, and cannot see the callbacks that are being made for suggesting to turn off video, or connection becoming poor.

I have looked over the internet for posts, looked through the SDK FAQs and cannot find anything related.

Has anyone experienced this in using the SDK to host meetings with multiple attendees?

**Comment by devalevenkatesh** [comment] 2021-06-30 16:10
Hello @gmonn ,

Could you please help us with below details to look into the issue:
1. Console logs for the affected meetings with `meetingId`, `attendeeId`. You can follow [this](https://aws.github.io/amazon-chime-sdk-js/modules/apioverview.html#1a-create-a-logger) guide to create and pass the logger while creating the meeting session.
2. Version of JS SDK you are using.
3. Is this same observation reproducible with or without VPN?

**Comment by gmonn** [comment] 2021-06-30 16:32
I don't have the logs for these four meetings, but we have changed the logger level and will try and reproduce in our load testing meeting this afternoon in our staging environment.

(1)
However we have seen the lag in these four meetings so far:
MeetingId - 454c4b34-2774-4944-b866-cd336b590706 ( Meeting on 6/24 )
AttendeeId - 7f36d125-9a27-414f-6dec-00467e11f559
Browser - MacOS - Safari - 13.1.2

MeetingId - 8616a8cc-40d7-4c28-8da4-3dc1cd9d0706 ( meeting on 6/24 )
AttendeeId - 8616a8cc-40d7-4c28-8da4-3dc1cd9d0706
Browser - ChromeOS - 91.0.4472

MeetingId - db3b48b3-2208-499d-87fd-f0308a5d0706 ( Meeting on 6/29 )
AttendeeId - 69738ee6-d84b-5e40-bb9e-3e5383286394
Browser - ChromeOS - 91.0.4472

Meetingid - e1d1e99a-5a37-4a5c-8a9f-ca5e64190706 ( Meeting on 6/29)
AttendeeId - ca83d345-e2f2-e203-bd6d-6d47ad855c08
Browser - MacOS  Chrome - 91.0.4472

(2)
We are using amazon-chime-sdk-js version 2.10.0 from and Angular 10 application

(3)
We are not on VPN at all for these meetings, not behind a corporate firewall, all participants are testing from the home computers and WiFi.

Thanks for the quick response, if we see the lag this afternoon, I can repost with more information.

**Comment by devalevenkatesh** [comment] 2021-07-08 17:43
Hello,

Checking if you found logs for other occurrences if any? Those will help us understand the issue more. 

Few more suggestions:
1. We have a guide around quality, bandwidth and connectivity. Could you please go through it and implement the explained observers to understand or get logs if there is some issue in bandwidth estimation pointing to network issues.
[Quality, Bandwith and Connectivity guide](https://aws.github.io/amazon-chime-sdk-js/modules/qualitybandwidth_connectivity.html)

2. We have a serverless demo which you can deploy and check if that is also running into this same issue in your environment to rule out if any implementation issues to check further.
[Serverless Demo README link](https://github.com/aws/amazon-chime-sdk-js/tree/master/demos/serverless)

**Comment by devalevenkatesh** [comment] 2021-08-04 00:55
We are closing this issue due to in-activity, please feel free to create a new if you need more help.

**Closed by devalevenkatesh** 2021-08-04 00:55 UTC
Labels: video
