### ISSUE TITLE
Unhandled Rejection (TypeError): Cannot read property 'audiohosturl' of undefined

### ISSUE THREAD

**Issue by RalphLincoln** [aws/amazon-chime-sdk-js#804] opened 2020-10-22 09:22 UTC
```
const startCall = async () => {
            const response = await axios.get('http://localhost:3000/join')
            // console.log(response.data.meeting.meetingResponse);
            this.setState({
                meetingResponse: response.data.meeting.meetingResponse,
                attendeeResponse: response.data.meeting.attendeeResponse
            })
            // setCallCreated(true)
        }

const joinVideoCall = async () => {
            const logger = new ConsoleLogger('ChimeMeetingLogs', LogLevel.INFO);
            const deviceController = new DefaultDeviceController(logger);
            const configuration = new MeetingSessionConfiguration(meetingResponse, attendeeResponse);
            const meetingSession = new DefaultMeetingSession(configuration, logger, deviceController);

            return meetingSession;
        }
```

I keep getting the errors above. When I console log meetingResponse, all is intact. But when I try to use it, it crashes

**Comment by devalevenkatesh** [comment] 2020-10-22 16:40
Hello, Can you please provide us the error trace you are getting as well as which version of `amazon-chime-sdk-js` you are using?

**Comment by devalevenkatesh** [comment] 2020-10-22 16:44
Can you please also check [this closed issue](https://github.com/aws/amazon-chime-sdk-js/issues/795) if you are facing a similar issue or this is a different one.

**Comment by RalphLincoln** [comment] 2020-10-22 20:28
```
DefaultAudioVideoController.ts:112 Uncaught (in promise) TypeError: Cannot read property 'attendeeId' of null
    at new DefaultAudioVideoController (DefaultAudioVideoController.ts:112)
    at new DefaultMeetingSession (DefaultMeetingSession.ts:52)
    at Page1.connectToChimeMeeting (Page1.js:76)
    at Page1.getReady (Page1.js:115)
```
This is the current error code it's throwing now. The version of amazon-chime-sdk-js am using is ^1.20.0

**Comment by devalevenkatesh** [comment] 2020-10-22 20:40
Ok, also can you confirm if you are getting valid `meetingResponse` and `attendeeResponse` objects before creating the `MeetingSessionConfiguration` in `joinVideoCall`?

Basically I want to check whether the `joinVideoCall` is taking place before your `setState` is completed successfully with valid objects.

```js
const joinVideoCall = async () => {
            const logger = new ConsoleLogger('ChimeMeetingLogs', LogLevel.INFO);
            const deviceController = new DefaultDeviceController(logger);
            // Console log meetingResponse and attendeeResponse here, are they valid here with attendeeId and all?
            const configuration = new MeetingSessionConfiguration(meetingResponse, attendeeResponse);
            const meetingSession = new DefaultMeetingSession(configuration, logger, deviceController);

            return meetingSession;
        }
```

**Comment by RalphLincoln** [comment] 2020-10-22 22:15
When it gets there, it now undefined..........

**Comment by devalevenkatesh** [comment] 2020-10-22 22:37
Sorry I did not understand you correctly.

Do you mean you are getting `undefined` for `meetingResponse` and `attendeeResponse` before `const configuration = new MeetingSessionConfiguration(meetingResponse, attendeeResponse);` in `joinVideoCall` ?

Also I think you have to write `this.state.meetingResponse` (similarly `this.state.attendeeResponse`) while creating the `MeetingSessionConfiguration`.

**Comment by RalphLincoln** [comment] 2020-10-24 16:22
Fixed.....Thanks. It was a fault from my end.

But I've got a question. I created an api to create a meeting. Inside the body of the api, I also included the create attendee.

```
`router.get('/', async (req, res, next) => {

    try {
        const meetingResponse = await chime.createMeeting({
            ClientRequestToken: uuidv4(),
            MediaRegion: 'us-west-2',
            ExternalMeetingId: 'MyMeeting'
        }).promise();

        const attendeeResponse = await chime.createAttendee({
            MeetingId: meetingResponse.Meeting.MeetingId,
            ExternalUserId: uuidv4()
        }).promise();

        const payload = { meetingResponse, attendeeResponse };
        res.status(201).json({
            message: 'You have successfully created a class',
            meeting: payload
        })
        // console.log(meetingResponse, attendeeResponse);
    } catch (err) {
        res.send(err)
    }

})`
```
I saved the meetingId somewhere then use it to create another attendee

```
router.get('/:ExternalMeetingId', (req, res, next) => {
    try {
        const getAttendee = async (meetingId) => {
            const attendeeResponse = await chime.createAttendee({
                MeetingId: meetingId,
                ExternalUserId: uuidv4() // Link the attendee to an identity managed by your application.
            }).promise();
            return attendeeResponse;
        }
        const id = req.params.ExternalMeetingId;
        console.log(id);
        LiveClass.find({ meetingId: id })
            .exec()
            .then(async doc => {
                console.log(doc[0].useMeetId)
                const attendee = await getAttendee(doc[0].useMeetId)
                res.status(200).json({ docs: doc, attendee: attendee })
            })
    } catch (err) {
        console.log(err)
        res.status(500).json({ error: err })
    }
})
```
Now when I try to join the meeting from the other api, I keep getting results like this.

```
hime Logs - serial group task AudioVideoStart/ef745b5e-2f2e-422c-b443-433bbd07d4a6/undefined/Timeout15000ms/Media/Signaling completed subtask AudioVideoStart/ef745b5e-2f2e-422c-b443-433bbd07d4a6/undefined/Timeout15000ms/Media/Signaling/OpenSignalingConnectionTask
ConsoleLogger.ts:81 2020-10-24T16:20:56.862Z [INFO] Chime Logs - serial group task AudioVideoStart/ef745b5e-2f2e-422c-b443-433bbd07d4a6/undefined/Timeout15000ms/Media/Signaling running subtask AudioVideoStart/ef745b5e-2f2e-422c-b443-433bbd07d4a6/undefined/Timeout15000ms/Media/Signaling/ListenForVolumeIndicatorsTask
ConsoleLogger.ts:81 2020-10-24T16:20:56.862Z [INFO] Chime Logs - running task AudioVideoStart/ef745b5e-2f2e-422c-b443-433bbd07d4a6/undefined/Timeout15000ms/Media/Signaling/ListenForVolumeIndicatorsTask
ConsoleLogger.ts:81 2020-10-24T16:20:56.862Z [INFO] Chime Logs - AudioVideoStart/ef745b5e-2f2e-422c-b443-433bbd07d4a6/undefined/Timeout15000ms/Media/Signaling/ListenForVolumeIndicatorsTask took 0 ms
ConsoleLogger.ts:81 2020-10-24T16:20:56.863Z [INFO] Chime Logs - serial group task AudioVideoStart/ef745b5e-2f2e-422c-b443-433bbd07d4a6/undefined/Timeout15000ms/Media/Signaling completed subtask AudioVideoStart/ef745b5e-2f2e-422c-b443-433bbd07d4a6/undefined/Timeout15000ms/Media/Signaling/ListenForVolumeIndicatorsTask
```

Please why is this so??

**Comment by regisfoucault** [comment] 2020-11-01 18:18
@RalphLincoln what is your fix for the above problem because I also have " Cannot read property 'audiohosturl' of undefined"
Best

**Comment by RalphLincoln** [comment] 2020-11-02 00:45
You have to make sure that you properly put in the createMeeting and createAttendee data gotten from the server here....
`const configuration = new MeetingSessionConfiguration(meetingResponse, attendeeResponse);`
Also check to see if you have the Meeting Session Object
```
const meetingSession = new DefaultMeetingSession(configuration, logger, deviceController);
console.log(meetingSession)
```

**Comment by RalphLincoln** [comment] 2020-11-02 00:46
Am currently trying to get the videos to show up from my end. It's really killing me.

**Comment by regisfoucault** [comment] 2020-11-02 08:36
@RalphLincoln I had a typo, problem fixed !  Thx

**Comment by vidya-mohan** [comment] 2020-11-05 19:14
Closed as the issue is resolved per report

**Closed by vidya-mohan** 2020-11-05 19:14 UTC
Labels: Minor Issue, Question
