### ISSUE TITLE
Local video goes black after reopening SDK from the iOS lock screen

### ISSUE THREAD

**Issue by simmkyu** [aws/amazon-chime-sdk-js#442] opened 2020-06-02 23:48 UTC
**Important:** Please attach INFO-level logs with timestamps to the report from *before* the session started up until the point at which the unexpected behavior occured. For multi-participant calls, attach a log file for each participant if possible.

**Meeting and attendee IDs:**
List the meeting and attendee IDs that the attached logs apply to.
N/A

**Timeline**
Outline the main actions the user performed and when:
N/A

**Describe the bug**
Describe the bug and the timestamp at which it happened relative to the timestamp in the log file.

Your video tile becomes black if you reopen the SDK demo from the iOS lock screen. Other remote users can still view your video.

### Repro steps in SDK demo
1. UserA joins a meeting in iOS Safari and starts a video.
2. UserB joins the same meeting in a desktop browser and starts a video.
3. In the UserA's iPhone, press the side button to lock iPhone. In the UserB's demo, UserA's video will become black. This is an expected behavior.
4. In the UserA's iPhone, reopen the demo app. For example, in iPhone 11 Pro, swipe up to unlock the phone. **UserA sees that the local video tile goes black.**
5. In the UserB's app, UserA's video appears again.

### Notes
- You can resume your video by pasuing and resuming it. e.g. Clicking pause/resume button in the SDK demo video tile.
- Once resumed, the video doesn't become black even after coming from the lock screen.

**Screenshots**
If applicable, add screenshots to help explain the problem.

**Platform**
 - OS: iOS 13.5
 - Browser: Safari
 - Browser Version: 13.1.1
 - Amazon Chime SDK GitHub Commit: fa0245a9a502ac4a8ccd3bcaf86d1deeaad0de0a

**Comment by michhyun1** [comment] 2020-09-28 22:23
I just tried to repro this in iOS 14, and I didnt see any issue. When the user locks the phone and then unlocks the phone again, the video stream seems to unpause as expected.

**Comment by shanepadgett** [comment] 2021-02-16 16:55
@vidya-mohan Hey Vidya. Is this still being investigated? We are still seeing this issue in iOS safari with 2.4.1 version of SDK alongside 1.6.1 version of the Chime React Library. I saw [here](https://github.com/aws/amazon-chime-sdk-js/issues/957#issuecomment-766496217) that you are using this issue to track the second case you mentioned in that thread.

**Comment by devalevenkatesh** [comment] 2021-11-24 04:11
Re-tested on iOS Safari 15.1.1 with JS SDK 2.23.0 and could not reproduce the issue.

Request you to please re-open the issue if this is still an issue with latest SDK versions for you. We also could not repro this issue in iOS 14 as per last check. Closing this issue now if still reproducible with latest version. Also request you to upgrade to newer versions.

**Closed by devalevenkatesh** 2021-11-24 04:11 UTC
Labels: Bug, Mobile, Triaged, video
