### ISSUE TITLE
serial group task AudioVideoStart

### ISSUE THREAD

**Issue by JannikSt** [aws/amazon-chime-sdk-js#483] opened 2020-06-16 13:10 UTC
Hi, 
we're running **chime 1.7** in production and use Google stackdriver to catch our frontend issues. 

An issue that came up quite frequently is the following:  

```
Error: serial group task AudioVideoStart/beee6853-894d-4910-9f2f-761d4725df76/7209b253-bbfd-4975-9161-8973dd10f690/Timeout15000ms/Media/Setup/Signaling was canceled due to subtask AudioVideoStart/beee6853-894d-4910-9f2f-761d4725df76/7209b253-bbfd-4975-9161-8973dd10f690/Timeout15000ms/Media/Setup/Signaling/OpenSignalingConnectionTask error: WebSocket connection failed

        at SerialGroupTask.BaseTask.logAndThrow (BaseTask.ts:66)
        at SerialGroupTask.eval (webpack://app_meeting/./amazon-chime-sdk-js-master/src/task/SerialGroupTask.ts:128)
        at step (webpack://app_meeting/./amazon-chime-sdk-js-master/src/task/SerialGroupTask.ts:48)
        at Object.eval (webpack://app_meeting/./amazon-chime-sdk-js-master/src/task/SerialGroupTask.ts:29)
        at rejected (webpack://app_meeting/./amazon-chime-sdk-js-master/src/task/SerialGroupTask.ts:21)
``` 

I have not found this issue using search and do not find release notes mentioning a fix. We will update to version 1.9 shortly. 

Also, are there release notes explaining the changes made? I have not found them yet. 

Stackdriver currently reports that 55 users are having this issue. 

All the best 

Jannik

**Comment by simmkyu** [comment] 2020-06-16 19:00
```
AudioVideoStart/beee6853-894d-4910-9f2f-761d4725df76/7209b253-bbfd-4975-9161-8973dd10f690
// represents AudioVideoStart/meetingId/attendeeId
```

SDK throws the `WebSocket connection failed` error usually when
- you attempt to join an ended meeting, or
- you attempt to join a meeting in a slow Internet connection.

The Chime SDK server logs indicate that the attendee `7209b253` attempted to join an ended meeting. Here's a timeline.

1. You created a meeting in the server application.
2. Another attendee, say *AttendeeA*, has joined a meeting.
3. *AttendeeA* left a meeting after 20 minutes.
4.  No one was present in the meeting for more than 5 minutes, so the meeting automatically ended. Note that a meeting will automatically end if no audio connection is present for 5 minutes.
     - Developer guide: https://docs.aws.amazon.com/chime/latest/dg/mtgs-sdk-mtgs.html
     - Example: https://github.com/aws/amazon-chime-sdk-js#stopping-a-session
5. A new attendee `7209b253` tried to join an auto-ended meeting, so this attendee received the WebSocket error.

Could you make sure your attendees join an active meeting?

---

> Also, are there release notes explaining the changes made? I have not found them yet.

[CHANGELOG.md](https://github.com/aws/amazon-chime-sdk-js/blob/master/CHANGELOG.md) includes the changes for a new NPM version.

**Comment by simmkyu** [comment] 2020-06-16 21:53
I confirmed that SDK was trying to reconnect multiple times when joining a finished meeting. Per each attempt, SDK threw the "WebSocket connection failed" error.

For now, please ensure that your attendees are joining an active meeting. We'll work on a fix for this issue.  [`AudioVideoObserver.audioVideoDidStop`](https://github.com/aws/amazon-chime-sdk-js/blob/dc98c59d65330cae6d789c12dc987ed46867ac75/src/audiovideoobserver/AudioVideoObserver.ts#L26) should be called immediately if an attendee joins a finished meeting.

**Comment by yusufali2205** [comment] 2020-07-09 19:59
@simmkyu is this issue fixed? 
Does the SDK call `AudioVideoObserver.audioVideoDidStop` if an attendee joins a finished meeting?

**Comment by anuranduttaroy** [comment] 2020-07-09 20:58
Currently, due to WebRTC restrictions, it is not possible for the JS SDK to catch the `410` error which we are getting while trying to establish a connection to the backend media servers for a meeting which has already ended. 

We have identified another possible solution for this issue though. Initial investigation shows that we receive a `403 - Forbidden` for the [ReceiveTURNCredentialsTask](https://github.com/aws/amazon-chime-sdk-js/blob/master/src/audiovideocontroller/DefaultAudioVideoController.ts#L321), but that happens approx. 30 seconds after it starts getting  the 410 error. We are trying to throw the 403 error earlier which will result the SDK to stop reconnecting which should solve this problem.

**Comment by yusufali2205** [comment] 2020-07-10 15:57
Thanks @anuranduttaroy 
I waited 30 seconds and I could reconnect after that.

This is what I am doing:
```
  audioVideoDidStop(meetingSessionStatus) {
    if (meetingSessionStatus.statusCode() === 22) {
      myReconnectLogic();
    }
  }
```

Any idea if the another possible solution will require change in this implementation?

**Comment by anuranduttaroy** [comment] 2020-07-21 17:23
@JannikSt @yusufali2205 the reconnection issue while trying to join a meeting which has ended should be solved with the latest PR https://github.com/aws/amazon-chime-sdk-js/pull/575

Summary: We introduced a new error code [`TURNMeetingEnded = 24`](https://github.com/aws/amazon-chime-sdk-js/blob/master/src/meetingsession/MeetingSessionStatusCode.ts#L135) and marked it a `terminal` error which prevents the reconnection attempt. 

Feel free to re-open if you still see the issue happening on your end.

**Closed by anuranduttaroy** 2020-07-21 17:23 UTC
Labels: Bug, Triaged

**Comment by yusufali2205** [comment] 2020-07-21 22:08
Thanks @anuranduttaroy. I verified and this works fine. The callback was executed instantly with TURNMeetingEnded and I could reconnect with new Meeting details successfully.

**Comment by chuckntaylor** [comment] 2020-11-20 16:27
In case it helps someone else down the line, I was working today using `"aws-sdk": "^2.796.0"` on my nodejs backend, and `"amazon-chime-sdk-js": "^2.0.0"` on the frontend, and was receiving the exact same errors @JannikSt described at the beginning of this thread.

To jump to the end, my nodejs app is using express to handle the http requests, along with the [Helmet](https://www.npmjs.com/package/helmet) middleware package to help with security. My problem was caused by the current version `"helmet": "^4.2.0"` enabling `Content Security Policy` by default.

To fix it, I adjusted the Helmet implementation as follows:
```
const express = require('express')
const app = express()
const helmet = require('helmet')

app.use(helmet({ contentSecurityPolicy: false })
) 
```

For more context: my frontend is a Vue SPA. I had no issues when I was serving the frontend and backend separately. For example the Vue app on port 8080, and the backend on port 3000. This issue popped up for me when I was serving my frontend build `dist` folder statically via express on the backend. So once everything was being served through the one port (3000), this problem came up.
