### ISSUE TITLE
Chime media capture pipeline records the video with a black screen.

### ISSUE THREAD

**Issue by injuk** [aws/amazon-chime-sdk-js#1880] opened 2021-12-15 03:04 UTC
### What happened and what did you expect to happen?

Hi guys!

We have a React-based web application for non-contact online lectures.
Our application uses Chime's meeting for lectures, and all of the teacher's lectures must be recorded. Whereas the students do not need to be recorded.

Unfortunately, during the meeting two days ago, while the teacher's video and audio shown to other attendees during the meeting were normal, all of the chunk files stored in the /audio folder were recorded with a black screen.

The media capture pipeline settings we used to record lecture are as follows:
```
const response = await chime.createMediaCapturePipeline({ 
    SinkArn: sinkArn,
    SinkType: 'S3Bucket',
    SourceArn: sourceArn,
    SourceType: 'ChimeSdkMeeting',
    ChimeSdkMeetingConfiguration: {
        ArtifactsConfiguration: {
            Audio: { MuxType: 'AudioWithActiveSpeakerVideo' },
            Video: { State: 'Enabled', MuxType: 'VideoOnly', },
            Content: { State: 'Enabled', MuxType: 'ContentOnly' },
        },
        SourceConfiguration: {
            SelectedVideoStreams: { ExternalUserIds: externalUserIds }
        }
}}).promise();
```

The logs recorded in the /media-event folder are as follows:
```
// I think this event came from 'create media capture pipeline'.
{"Timestamp":"2021-12-13T14:16:07.695+00:00","EventType":"CaptureStarted"}
{"Timestamp":"2021-12-13T14:16:07.892+00:00","EventType":"AttendeeJoined","EventParameters":{"AttendeeId":"0b897405-0c55-7250-ad10-4c6e561d7f02","MediaModality":""}}
{"Timestamp":"2021-12-13T14:16:07.892+00:00","EventType":"AttendeeMute","EventParameters":{"AttendeeId":"0b897405-0c55-7250-ad10-4c6e561d7f02","MediaModality":""}}

// Teacher joined by mobile phone, but left because of a mobile phone issue.
{"Timestamp":"2021-12-13T14:16:07.893+00:00","EventType":"AttendeeJoined","EventParameters":{"AttendeeId":"553a0c82-34fa-17f7-d71e-6bfa9d89bca1","MediaModality":""}}
{"Timestamp":"2021-12-13T14:16:11.592+00:00","EventType":"AttendeeVideoLeft","EventParameters":{"AttendeeId":"553a0c82-34fa-17f7-d71e-6bfa9d89bca1","MediaModality":"Video"}}
{"Timestamp":"2021-12-13T14:16:11.612+00:00","EventType":"ActiveSpeaker","EventParameters":{"AttendeeId":"","MediaModality":""}}
{"Timestamp":"2021-12-13T14:16:11.612+00:00","EventType":"AttendeeLeft","EventParameters":{"AttendeeId":"553a0c82-34fa-17f7-d71e-6bfa9d89bca1","MediaModality":""}}

// Teacher joined again with a laptop.
{"Timestamp":"2021-12-13T14:16:13.432+00:00","EventType":"AttendeeJoined","EventParameters":{"AttendeeId":"553a0c82-34fa-17f7-d71e-6bfa9d89bca1","MediaModality":""}}
{"Timestamp":"2021-12-13T14:16:13.472+00:00","EventType":"ActiveSpeaker","EventParameters":{"AttendeeId":"553a0c82-34fa-17f7-d71e-6bfa9d89bca1","MediaModality":""}}
{"Timestamp":"2021-12-13T14:16:13.872+00:00","EventType":"AttendeeVideoJoined","EventParameters":{"AttendeeId":"553a0c82-34fa-17f7-d71e-6bfa9d89bca1","MediaModality":"Video"}}

// The teacher was the only active speaker in the meeting.
{"Timestamp":"2021-12-13T14:16:43.952+00:00","EventType":"ActiveSpeaker","EventParameters":{"AttendeeId":"553a0c82-34fa-17f7-d71e-6bfa9d89bca1","MediaModality":""}}
{"Timestamp":"2021-12-13T14:16:48.972+00:00","EventType":"ActiveSpeaker","EventParameters":{"AttendeeId":"553a0c82-34fa-17f7-d71e-6bfa9d89bca1","MediaModality":""}}
{"Timestamp":"2021-12-13T14:17:10.632+00:00","EventType":"ActiveSpeaker","EventParameters":{"AttendeeId":"553a0c82-34fa-17f7-d71e-6bfa9d89bca1","MediaModality":""}}
{"Timestamp":"2021-12-13T14:17:15.652+00:00","EventType":"ActiveSpeaker","EventParameters":{"AttendeeId":"553a0c82-34fa-17f7-d71e-6bfa9d89bca1","MediaModality":""}}
{"Timestamp":"2021-12-13T14:17:17.672+00:00","EventType":"ActiveSpeaker","EventParameters":{"AttendeeId":"553a0c82-34fa-17f7-d71e-6bfa9d89bca1","MediaModality":""}}
{"Timestamp":"2021-12-13T14:18:15.672+00:00","EventType":"ActiveSpeaker","EventParameters":{"AttendeeId":"553a0c82-34fa-17f7-d71e-6bfa9d89bca1","MediaModality":""}}
{"Timestamp":"2021-12-13T14:18:22.692+00:00","EventType":"ActiveSpeaker","EventParameters":{"AttendeeId":"553a0c82-34fa-17f7-d71e-6bfa9d89bca1","MediaModality":""}}
{"Timestamp":"2021-12-13T14:19:01.692+00:00","EventType":"ActiveSpeaker","EventParameters":{"AttendeeId":"553a0c82-34fa-17f7-d71e-6bfa9d89bca1","MediaModality":""}}
{"Timestamp":"2021-12-13T14:19:07.712+00:00","EventType":"ActiveSpeaker","EventParameters":{"AttendeeId":"553a0c82-34fa-17f7-d71e-6bfa9d89bca1","MediaModality":""}}
{"Timestamp":"2021-12-13T14:19:12.652+00:00","EventType":"ActiveSpeaker","EventParameters":{"AttendeeId":"553a0c82-34fa-17f7-d71e-6bfa9d89bca1","MediaModality":""}}
{"Timestamp":"2021-12-13T14:19:14.772+00:00","EventType":"ActiveSpeaker","EventParameters":{"AttendeeId":"553a0c82-34fa-17f7-d71e-6bfa9d89bca1","MediaModality":""}}
{"Timestamp":"2021-12-13T14:19:36.692+00:00","EventType":"ActiveSpeaker","EventParameters":{"AttendeeId":"553a0c82-34fa-17f7-d71e-6bfa9d89bca1","MediaModality":""}}
{"Timestamp":"2021-12-13T14:20:25.552+00:00","EventType":"ActiveSpeaker","EventParameters":{"AttendeeId":"553a0c82-34fa-17f7-d71e-6bfa9d89bca1","MediaModality":""}}
{"Timestamp":"2021-12-13T14:20:57.552+00:00","EventType":"ActiveSpeaker","EventParameters":{"AttendeeId":"553a0c82-34fa-17f7-d71e-6bfa9d89bca1","MediaModality":""}}
{"Timestamp":"2021-12-13T14:22:43.372+00:00","EventType":"ActiveSpeaker","EventParameters":{"AttendeeId":"553a0c82-34fa-17f7-d71e-6bfa9d89bca1","MediaModality":""}}
{"Timestamp":"2021-12-13T14:23:14.052+00:00","EventType":"ActiveSpeaker","EventParameters":{"AttendeeId":"553a0c82-34fa-17f7-d71e-6bfa9d89bca1","MediaModality":""}}
{"Timestamp":"2021-12-13T14:23:56.872+00:00","EventType":"ActiveSpeaker","EventParameters":{"AttendeeId":"553a0c82-34fa-17f7-d71e-6bfa9d89bca1","MediaModality":""}}
{"Timestamp":"2021-12-13T14:24:54.772+00:00","EventType":"ActiveSpeaker","EventParameters":{"AttendeeId":"553a0c82-34fa-17f7-d71e-6bfa9d89bca1","MediaModality":""}}
{"Timestamp":"2021-12-13T14:25:03.792+00:00","EventType":"ActiveSpeaker","EventParameters":{"AttendeeId":"553a0c82-34fa-17f7-d71e-6bfa9d89bca1","MediaModality":""}}
{"Timestamp":"2021-12-13T14:25:09.112+00:00","EventType":"ActiveSpeaker","EventParameters":{"AttendeeId":"553a0c82-34fa-17f7-d71e-6bfa9d89bca1","MediaModality":""}}
{"Timestamp":"2021-12-13T14:26:58.112+00:00","EventType":"ActiveSpeaker","EventParameters":{"AttendeeId":"553a0c82-34fa-17f7-d71e-6bfa9d89bca1","MediaModality":""}}
{"Timestamp":"2021-12-13T14:27:26.032+00:00","EventType":"ActiveSpeaker","EventParameters":{"AttendeeId":"553a0c82-34fa-17f7-d71e-6bfa9d89bca1","MediaModality":""}}
{"Timestamp":"2021-12-13T14:28:44.892+00:00","EventType":"ActiveSpeaker","EventParameters":{"AttendeeId":"553a0c82-34fa-17f7-d71e-6bfa9d89bca1","MediaModality":""}}
{"Timestamp":"2021-12-13T14:28:55.912+00:00","EventType":"ActiveSpeaker","EventParameters":{"AttendeeId":"553a0c82-34fa-17f7-d71e-6bfa9d89bca1","MediaModality":""}}
{"Timestamp":"2021-12-13T14:30:42.332+00:00","EventType":"ActiveSpeaker","EventParameters":{"AttendeeId":"553a0c82-34fa-17f7-d71e-6bfa9d89bca1","MediaModality":""}}
{"Timestamp":"2021-12-13T14:31:14.412+00:00","EventType":"ActiveSpeaker","EventParameters":{"AttendeeId":"553a0c82-34fa-17f7-d71e-6bfa9d89bca1","MediaModality":""}}
{"Timestamp":"2021-12-13T14:33:54.732+00:00","EventType":"ActiveSpeaker","EventParameters":{"AttendeeId":"553a0c82-34fa-17f7-d71e-6bfa9d89bca1","MediaModality":""}}
{"Timestamp":"2021-12-13T14:34:12.832+00:00","EventType":"ActiveSpeaker","EventParameters":{"AttendeeId":"553a0c82-34fa-17f7-d71e-6bfa9d89bca1","MediaModality":""}}
{"Timestamp":"2021-12-13T14:36:54.692+00:00","EventType":"ActiveSpeaker","EventParameters":{"AttendeeId":"553a0c82-34fa-17f7-d71e-6bfa9d89bca1","MediaModality":""}}
{"Timestamp":"2021-12-13T14:37:25.992+00:00","EventType":"ActiveSpeaker","EventParameters":{"AttendeeId":"553a0c82-34fa-17f7-d71e-6bfa9d89bca1","MediaModality":""}}
{"Timestamp":"2021-12-13T14:40:01.012+00:00","EventType":"ActiveSpeaker","EventParameters":{"AttendeeId":"553a0c82-34fa-17f7-d71e-6bfa9d89bca1","MediaModality":""}}
{"Timestamp":"2021-12-13T14:41:00.172+00:00","EventType":"ActiveSpeaker","EventParameters":{"AttendeeId":"553a0c82-34fa-17f7-d71e-6bfa9d89bca1","MediaModality":""}}
{"Timestamp":"2021-12-13T14:41:23.272+00:00","EventType":"ActiveSpeaker","EventParameters":{"AttendeeId":"553a0c82-34fa-17f7-d71e-6bfa9d89bca1","MediaModality":""}}
{"Timestamp":"2021-12-13T14:41:52.172+00:00","EventType":"ActiveSpeaker","EventParameters":{"AttendeeId":"553a0c82-34fa-17f7-d71e-6bfa9d89bca1","MediaModality":""}}
{"Timestamp":"2021-12-13T14:44:13.052+00:00","EventType":"ActiveSpeaker","EventParameters":{"AttendeeId":"553a0c82-34fa-17f7-d71e-6bfa9d89bca1","MediaModality":""}}
{"Timestamp":"2021-12-13T14:44:14.072+00:00","EventType":"ActiveSpeaker","EventParameters":{"AttendeeId":"553a0c82-34fa-17f7-d71e-6bfa9d89bca1","MediaModality":""}}
{"Timestamp":"2021-12-13T14:45:30.272+00:00","EventType":"ActiveSpeaker","EventParameters":{"AttendeeId":"553a0c82-34fa-17f7-d71e-6bfa9d89bca1","MediaModality":""}}
{"Timestamp":"2021-12-13T14:47:13.572+00:00","EventType":"ActiveSpeaker","EventParameters":{"AttendeeId":"553a0c82-34fa-17f7-d71e-6bfa9d89bca1","MediaModality":""}}
{"Timestamp":"2021-12-13T14:47:35.052+00:00","EventType":"ActiveSpeaker","EventParameters":{"AttendeeId":"553a0c82-34fa-17f7-d71e-6bfa9d89bca1","MediaModality":""}}
{"Timestamp":"2021-12-13T14:47:56.032+00:00","EventType":"ActiveSpeaker","EventParameters":{"AttendeeId":"553a0c82-34fa-17f7-d71e-6bfa9d89bca1","MediaModality":""}}
{"Timestamp":"2021-12-13T14:50:30.632+00:00","EventType":"ActiveSpeaker","EventParameters":{"AttendeeId":"553a0c82-34fa-17f7-d71e-6bfa9d89bca1","MediaModality":""}}
{"Timestamp":"2021-12-13T14:51:15.512+00:00","EventType":"ActiveSpeaker","EventParameters":{"AttendeeId":"553a0c82-34fa-17f7-d71e-6bfa9d89bca1","MediaModality":""}}
{"Timestamp":"2021-12-13T14:56:18.012+00:00","EventType":"ActiveSpeaker","EventParameters":{"AttendeeId":"553a0c82-34fa-17f7-d71e-6bfa9d89bca1","MediaModality":""}}
{"Timestamp":"2021-12-13T14:56:37.152+00:00","EventType":"ActiveSpeaker","EventParameters":{"AttendeeId":"553a0c82-34fa-17f7-d71e-6bfa9d89bca1","MediaModality":""}}
{"Timestamp":"2021-12-13T14:56:56.732+00:00","EventType":"ActiveSpeaker","EventParameters":{"AttendeeId":"553a0c82-34fa-17f7-d71e-6bfa9d89bca1","MediaModality":""}}

// When the lecture was over, teacher left the meeting.
{"Timestamp":"2021-12-13T15:03:04.437+00:00","EventType":"AttendeeVideoLeft","EventParameters":{"AttendeeId":"553a0c82-34fa-17f7-d71e-6bfa9d89bca1","MediaModality":"Video"}}

// I think this event came from 'delete media capture pipeline'.
{"Timestamp":"2021-12-13T15:03:04.453+00:00","EventType":"CaptureEnded"}
```

We want to know the cause of this problem. 
I know that the black screen is recorded because if there is not enough audio volume, the attendees are not selected as active speaker, but the teacher was the only active speaker in the meeting, and the audio volume was sufficient. In fact, it was a music lecture.

Is there anything else to consider besides the small audio volume of the attendees?

### Have you reviewed our existing documentation?

- [X] GitHub [issues](https://github.com/aws/amazon-chime-sdk-js/issues)
- [X] FAQs [page](https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html)
- [X] README [page](https://github.com/aws/amazon-chime-sdk-js#amazon-chime-sdk-for-javascript)
- [X] Feature-specific [guides](https://github.com/aws/amazon-chime-sdk-js#guides)

### Reproduction steps

This is the order in which we applied to the application, but the reproduction of the issue has failed. ;(
1. Create meeting.
2. Create attendees.
2. Capture start(create media capture pipeline).
3. Join meeting.
4. Left from meeting when lecture's end.
5. Capture end(delete media capture pipeline).

### Amazon Chime SDK for JavaScript version

aws-sdk 2.1021.0

### What browsers are you seeing the problem on?

Google Chrome

### Browser version

Chrome 96 (Not sure)

### Meeting and Attendee ID Information.

- Lecture's Chime meeting Id : 48f674d1-325b-4dc6-ad54-1aae1b4b0706
- Teacher's Chime attendee Id : 553a0c82-34fa-17f7-d71e-6bfa9d89bca1

- Lecture's external meeting Id: 04197607RKuCOv
- Teacher's external user Id: 04197642pXvGpj
- Lecture's Chime media capture pipeline Id: c3cf1996-5caf-465d-a3c2-486ca8033389

### Browser console logs

N / A

**Comment by devalevenkatesh** [comment] 2021-12-28 23:54
@tenge-amzn Could you please look into this issue? We have labelled the issue as capture service so it should have created a ticket internally, but since we see no update request you to please check once into this.

**Comment by niborkar** [comment] 2022-01-05 02:02
Hi injuk@ 

Is this issue reproducible consistently? 

Also, for the meeting above, can you check-
1) If the teacher's individual video chunk files were captured correctly in the /video folder?
2) Was the audio content in the chunk files stored in the /audio folder as expected?

**Comment by injuk** [comment] 2022-01-05 06:01
Hi niborkar@ !

Unfortunately, the same issue has not been reproduced since that case.

1. No. We do not want all individual attendee's video files to be saved without voice. We wanted both ActiveSpeaker’s screen and voice to be recorded, not the screen of a specific attendee's.
2. Yes. We expected a chunk file that integrated the video and voice of ActiveSpeaker. Chunk files have been saved in the /audio folder. However, there was no problem with the teacher's screen and voice during the lecture, and she was also selected for ActiveSpeaker, but a black screen with only voice was recorded in the /audio folder. 

We want to know why the screen was not recorded in the chunk file in the /audio folder, although only the teacher was selected for ActiveSpeaker.

**Comment by michhyun1** [comment] 2022-01-11 20:41
@niborkar do you have any more guidance for @injuk?

**Comment by MingcongQi** [comment] 2022-01-14 17:53
We found an issue on our backend side that would have caused it and we are fixing it.

**Comment by MingcongQi** [comment] 2022-02-12 00:26
The fix has been fully deployed in our backend

**Closed** 2022-02-23 21:52 UTC
Labels: capture-service

**Comment by CustomHH** [comment] 2022-07-11 20:49
This issue is still existing. We are using the same mediaCapturePipeline and getting the black screen :The configuration used is as below and the issue is with the AudioWithActiveSpeakerVideo where the recored contents are stored under audio folder. 

const response = await chime.createMediaCapturePipeline({ 
    SinkArn: sinkArn,
    SinkType: 'S3Bucket',
    SourceArn: sourceArn,
    SourceType: 'ChimeSdkMeeting',
    ChimeSdkMeetingConfiguration: {
        ArtifactsConfiguration: {
            Audio: { MuxType: 'AudioWithActiveSpeakerVideo' },
            Video: { State: 'Enabled', MuxType: 'VideoOnly', },
            Content: { State: 'Enabled', MuxType: 'ContentOnly' },
        },
        SourceConfiguration: {
            SelectedVideoStreams: { ExternalUserIds: externalUserIds }
        }
}}).promise();

**Comment by hajime-goshima** [comment] 2023-01-12 07:16
We have a similar problem.
