### ISSUE TITLE
The remote video is hidden in a meeting of 2 participants with simulcast

### ISSUE THREAD

**Issue by CastriOnlive** [aws/amazon-chime-sdk-js#2198] opened 2022-05-03 09:23 UTC
### What happened and what did you expect to happen?

When having 2 participants (me and a remote) with simulcast enabled the remote video stops emitting for a few seconds when the local connection is low
I expected that on poor connection to decrease bitrate but not to hide the remote video.

### Have you reviewed our existing documentation?

- [X] GitHub [issues](https://github.com/aws/amazon-chime-sdk-js/issues)
- [X] FAQs [page](https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html)
- [X] README [page](https://github.com/aws/amazon-chime-sdk-js#amazon-chime-sdk-for-javascript)
- [X] Feature-specific [guides](https://github.com/aws/amazon-chime-sdk-js#guides)

### Reproduction steps

I created a meeting session with simulcast enabled:
`configuration.enableSimulcastForUnifiedPlanChromiumBasedBrowsers = true;`
When the meeting reaches 2 participants, me and a remote (I have tested both local and one on my pc and the other in another pc, the same problem happens)
stress the local computer and see that the remote video hides for a few seconds.
before it happens
<img width="1047" alt="Screenshot 2022-05-03 at 11 14 01" src="https://user-images.githubusercontent.com/85135004/166429767-247a0eff-feb4-418f-bc00-5c2c5afbc9f6.png">

after it happens
<img width="991" alt="Screenshot 2022-05-03 at 11 15 08" src="https://user-images.githubusercontent.com/85135004/166429837-9dc0cd29-cbc8-449d-8371-a9ef5d5f929a.png">

### Amazon Chime SDK for JavaScript version

3.1.0

### What browsers are you seeing the problem on?

Chrome

### Browser version

Version 101.0.4951.41 (Official Build) (arm64)

### Browser console logs

[logs.LOG](https://github.com/aws/amazon-chime-sdk-js/files/8609558/logs.LOG)

**Comment by nainkunal933** [comment] 2022-05-03 21:15
Hey @CastriOnlive,

Thank you for opening this issue. 

I would like to know how are you stressing the computer? I tried to reproduce this issue in Chrome but I could not. I used network throttling from DevTools and dropped the speed down to Slow 3G.

**Comment by CastriOnlive** [comment] 2022-05-03 21:19
Hi @nainkunal933 tanks for your answer, I use fast.com for that on an up to 200 mbit/s connection. The fast.com oocupies all the bandwidth almost.

**Comment by CastriOnlive** [comment] 2022-05-03 21:25
I would also like to add that when using throttling it is not possible to reproduced since it is not working really with WebrRTC as a real bad connection, that should be why you were not able to reproduce ir, can you try to connect with a real bad connection or occupy the bandwidth in something else such as fast.com or a huge download

**Comment by ltrung** [comment] 2022-05-05 20:37
@CastriOnlive I think the default downlink policy for simulcast is `VideoAdaptiveProbePolicy` which will drop a video if bandwidth is low. Could you try to use [VideoPriorityBasedPolicy](https://aws.github.io/amazon-chime-sdk-js/classes/videoprioritybasedpolicy.html) for downlink policy?
```
configuration.videoDownlinkBandwidthPolicy = new VideoPriorityBasedPolicy(logger);
```

**Comment by nainkunal933** [comment] 2022-05-06 00:40
When using simulcast for Chrome the remote attendee's video is dropping. I am able to confirm this on mac by throttling the network using network link conditioner.

**Comment by nainkunal933** [comment] 2022-05-06 00:49
@CastriOnlive Can you try @ltrung's suggestion? `VideoPriorityBasedDownlinkPolicy` is working with a very bad connection while simulcast is dropping the video.

**Comment by CastriOnlive** [comment] 2022-05-06 07:41
I have to turn off simulcast then by setting
`configuration.enableSimulcastForUnifiedPlanChromiumBasedBrowsers = false;`
or not setting it at all
In this case is it possible to make chime work with simulcast without dropping on low bandwidth?

**Comment by CastriOnlive** [comment] 2022-05-06 13:41
By the way with simulcast enabled and VideoPriorityBasedDownlinkPolicy i still have the same video dropped problem

**Comment by CastriOnlive** [comment] 2022-05-11 07:35
Hello sorry for the delay here are the logs with simulcast and VideoPriorityBasedDownlinkPolicy
[chimelogs.LOG](https://github.com/aws/amazon-chime-sdk-js/files/8667676/chimelogs.LOG)

**Comment by CastriOnlive** [comment] 2022-05-17 10:15
Is it possible that simulcast and either video adaptive or video priority policies do not drop the video when bandwidth is a bit low, maybe displaying a 180p stream on a two participants meeting?

**Comment by hensmi-amazon** [comment] 2022-05-17 18:57
@CastriOnlive unfortunately we do not have that option available in the SDK, and it would likely lead to issues; if your network is estimated to be below the bitrate of even a 180p stream (which the lower simulcast stream is already configured to be around), continuing to send that stream will overuse the network and lead to audio issues. 

Perhaps you are interested in [`MeetingSessionConfiguration.keepLastFrameWhenPaused`](https://github.com/aws/amazon-chime-sdk-js/blob/main/src/meetingsession/MeetingSessionConfiguration.ts#L101) which will keep the last frame up on the receiver until the network recovers?

**Comment by CastriOnlive** [comment] 2022-05-18 07:32
[MeetingSessionConfiguration.keepLastFrameWhenPaused](https://github.com/aws/amazon-chime-sdk-js/blob/main/src/meetingsession/MeetingSessionConfiguration.ts#L101)
I will try this, but @hensmi-amazon I also see that the dropping of the video happens many times even it is possible to consume a 180p video, i think there is a bandwidth calculation issue, and it happens also in meetings with several participants. I have tested for example same scenario with jitsi meet low level api enabling simulcast and we do not have the dropping video issue.

**Comment by CastriOnlive** [comment] 2022-05-18 07:36
> @CastriOnlive unfortunately we do not have that option available in the SDK, and it would likely lead to issues; if your network is estimated to be below the bitrate of even a 180p stream (which the lower simulcast stream is already configured to be around), continuing to send that stream will overuse the network and lead to audio issues.
> 
> Perhaps you are interested in [`MeetingSessionConfiguration.keepLastFrameWhenPaused`](https://github.com/aws/amazon-chime-sdk-js/blob/main/src/meetingsession/MeetingSessionConfiguration.ts#L101) which will keep the last frame up on the receiver until the network recovers?

BTW when there are only two participants i never receive a 180p video, only the high quality video, i saw that on the docs, that for a meeting of 2 participants there was only 1 video resolution available, that should be why it is dropping so frequently.

**Comment by hensmi-amazon** [comment] 2022-05-18 15:56
Oh thanks for the clarification. We disable simulcast in 1-1 calls because we forward the estimate from the receiver to the sender, and the sender will take the minimum of its estimation and the receiver estimation. The browser may or may not down res the sent frame correspondingly, but the bitrate will reduce to 150 kbps, which is about the same quality as 180p regardless of the actual resolution.

If you apply a constraint to the receive side you should see the send bitrate reduce as low as 150kbps (technically it can go lower if there are send side issues). However if a heavy constraint is applied quickly as is here, the sender will not have time to respond and the receiver will choose to just drop the stream temporarily instead. When the estimate recovers to 150kbps it will resubscribe to the send stream.

**Comment by CastriOnlive** [comment] 2022-05-19 07:45
My main worry is that it is a bit unsteady, since it drops the video from time to time instead of the normal freeze that should happen in that case.

**Comment by hensmi-amazon** [comment] 2022-05-20 02:07
You can technically modify the downlink policy to not pause by making this loop not account for https://github.com/aws/amazon-chime-sdk-js/blob/main/src/videodownlinkbandwidthpolicy/VideoPriorityBasedPolicy.ts#L835 `targetDownlinkBitrate`. However we do not really want to release an API like that given that it endangers the audio stream which is usually much more important then video to end users, and we do not want builders to accidentally enable it without knowing the significant risks involved. Unfortunately I think this is less of a bug and more of a feature request.

**Comment by CastriOnlive** [comment] 2022-05-20 07:50
@hensmi-amazon I understand this might seem more of a feature than a bug, but when enabled the simulcast on other Apis we have used even for 2 participants each one has more than 1 stream available, so if connection gets really bad the 180p (lowest simulcast layer) video is used without stopping/pausing the video, is there any way of setting up chime to work like that?

**Comment by hensmi-amazon** [comment] 2022-05-24 17:58
You can copy the simulcast policy and remove the branch here: https://github.com/aws/amazon-chime-sdk-js/blob/main/src/videouplinkbandwidthpolicy/DefaultSimulcastUplinkPolicy.ts#L160 . But what will happen is on congestion, the uplink will drop the top simulcast stream, and send 150kbps on the bottom steam, effectively the same behavior as before, except there may be video freezing when the receiver switches from the disabled top stream to the lower stream.

Again I think you may be interested in the modification to the downlink policy above that I mentioned we do not want to risk making publicly availabe (in those other APIs, if that simulcast stream is 150 kbps, and your downlink is 50-100kbps you will see heavy audio packet loss). In our experience end users are much more forgiving to video pauses/freezing then broken audio.

**Comment by hensmi-amazon** [comment] 2022-06-01 00:51
Closing due to lack of action items on our end. If the solutions are not satisfactory, feel free to open a new issue as a feature request, and you can link this one for context.

**Closed by hensmi-amazon** 2022-06-01 00:51 UTC
Labels: Needs More Information, video
