### ISSUE TITLE
Webcam stream from inactive tab freezes on viewer side if virtual background is applied 

### ISSUE THREAD

**Issue by ArtemZakharchuk** [aws/amazon-chime-sdk-js#1543] opened 2021-08-26 08:54 UTC
### What happened and what did you expect to happen?

When the user turns on his webcam with "Virtual effects" and switches to another browser tab, viewers will see a freezing webcam stream. Sometimes it happens instantly after go out from the tab, sometimes it took about 30 seconds to start freeze (maybe depend on is user muted or no). Also, this issue is reproducing in demo/browse/app example from amazon-chime-sdk-js. There is any workaround for this problem?

### Have you reviewed our existing documentation?

- [X] GitHub [issues](https://github.com/aws/amazon-chime-sdk-js/issues)
- [X] FAQs [page](https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html)
- [X] README [page](https://github.com/aws/amazon-chime-sdk-js#amazon-chime-sdk-for-javascript)
- [X] Feature-specific [guides](https://github.com/aws/amazon-chime-sdk-js#guides)

### Reproduction steps

(Using application example from SDK)
Join at least two users to a meeting.
Mute both of them. 
User1 starts his webcam, applies one of the video effects (e.g. Segmentation), and switches to another tab.
User2 will observe that the webcam stream from User1 is freezing.  

### Amazon Chime SDK for JavaScript version

2.16.1

### What browsers are you seeing the problem on?

Chrome, Safari

### Browser version

92.0.4515.159, 14.1.2 

### Browser console logs

[freezing webcam.log](https://github.com/aws/amazon-chime-sdk-js/files/7055573/freezing.webcam.log)

**Comment by nainkunal933** [comment] 2021-08-28 07:24
Hi @ArtemZakharchuk,

Thank you for using Chime JS SDK and for opening this issue. I have been able to verify this issue. I will do some more investigation and keep you updated here.

**Comment by nainkunal933** [comment] 2021-09-22 00:19
Hi @ArtemZakharchuk,

Thank you for your patience. It seems like the root cause for this issue is that when the user switches the tab, chrome is reducing CPU allocation for that tab. I was able to verify the reduction in CPU allocation for the tab using Chrome's task manager.

Chrome added this behavior first in Chrome 57 under [optimising an application for background](https://developers.google.com/web/updates/2017/03/background_tabs#optimising_an_application_for_background). Also, it seems like further changes were made to tab's background behavior in 2020. Check out this [blog](https://blog.chromium.org/2020/11/tab-throttling-and-more-performance.html). It seems like Chrome is using page visibility api to reduce CPU allocation.

I will recommend that you do not update chrome://flags/. Doing that will affect every customer of your application and it may cause side effects as other browser tabs might also start high CPU usage on the customer's device.

One workaround for this issue might be the usage of web workers to process the video stream. I have not tried this myself but please feel free to give it a shot. Refer to this article: [Image processing in web worker](https://www.kevinhoyt.com/2018/10/23/image-processing-in-a-web-worker/).

Please let me know if you have any further questions or concerns. Thank you for using Chime JS SDK.

**Comment by nainkunal933** [comment] 2021-09-27 18:03
Hi @ArtemZakharchuk,

Does the above response answer your question? Should I close this issue?

Thank you.

**Closed** 2021-09-29 16:46 UTC

**Comment by ArtemZakharchuk** [comment] 2021-10-12 12:09
Hi, @nainkunal933 Thanks for your answer!  I will take a look at your workaround, is it suitable for me.
