### ISSUE TITLE
The demo app crashes, kicking an attendee out

### ISSUE THREAD

**Issue by simmkyu** [aws/amazon-chime-sdk-js#129] opened 2020-02-20 18:37 UTC
**Important:** Please attach INFO-level logs with timestamps to the report from *before* the session started up until the point at which the unexpected behavior occured. For multi-participant calls, attach a log file for each participant if possible.

[Chrome demo crash logs.txt](https://github.com/aws/amazon-chime-sdk-js/files/4232381/Chrome.demo.crash.logs.txt)

**Meeting and attendee IDs:**
List the meeting and attendee IDs that the attached logs apply to.

- Meeting ID: 4e4e6504-4d0e-401a-b524-7b1cedce8bd3
- Attendee ID: 3da4c6c3-3c97-4bd8-93f6-69fc08dabeef

**Timeline**
Outline the main actions the user performed and when:

```
2020-02-20T18:23:20.536Z [ERROR] SDK - realtime error: TypeError: Cannot read property 'style' of null: TypeError: Cannot read property 'style' of null
2020-02-20T18:23:20.537Z [ERROR] SDK - connection failed with status code: RealtimeApiFailed
```

**Describe the bug**
Describe the bug and the timestamp at which it happened relative to the timestamp in the log file.

A demo app's bug causes Chime SDK to stop the session because SDK does not catch an error in its real-time callback.

Steps to reproduce
1. Attendee A joins a meeting and does not mute audio.
2. Attendee B joins the same meeting and does not mute audio.
3. Attendee A clicks the screen viewing button.
4. After a few seconds, in the Attendee B browser's roster, Attendee A is removed from the meeting.
5. In the Attendee A's browser, Attendee A cannot hear any audio or click control buttons at the top.

**Screenshots**
If applicable, add screenshots to help explain the problem.

**Platform**
 - OS: macOS Mojave
 - Browser: Chrome
 - Browser Version: 79.0
 - Amazon Chime SDK GitHub Commit: 9720363625a16fb702b8edd53b8efaa3a63a5f03

**Comment by ltrung** [comment] 2020-02-21 00:40
The issue is caused by commit 9720363625a16fb702b8edd53b8efaa3a63a5f03 that added resume and pause button to video tiles in the demo app except tile 17 which is reserved for screen sharing.
When active speaker is on and there are umute audio, DefaultActiveSpeakerDetector updateActiveSpeakers will trigger callback updateTilePlacement in the demo app which error out when accessing the pausing button in video tile 17, which is enabled after clicking on screenviewing (https://github.com/aws/amazon-chime-sdk-js/commit/9720363625a16fb702b8edd53b8efaa3a63a5f03#diff-23750892c041f9027d1827b108ff9ee7R1280)
Tile 17 is updated with the new PR #132 which should resolve this issue

**Comment by vidya-mohan** [comment] 2020-02-24 16:44
Resolving as code push completed

**Closed by vidya-mohan** 2020-02-24 16:44 UTC
Labels: bug
