### ISSUE TITLE
Video from mobile chrome browser freezes when other participant joins. 

### ISSUE THREAD

**Issue by Rambarani** [aws/amazon-chime-sdk-js#1736] opened 2021-10-29 06:29 UTC
### What happened and what did you expect to happen?

I am having desktop application (electron, react js) and web app (react js).

When i connect meeting from desktop app and desktop web app means, everything working fine.

When i join meeting from Android chrome browser means, this video alone **freezes.**  Other participants from desktop electron and web app sees only freeze video of mobile participant or sometime black screen alone.

**This is only happening when participant join from mobile chrome browser.** I also tested joining from mobile firefox. that case is working fine. 

### Have you reviewed our existing documentation?

- [x] GitHub [issues](https://github.com/aws/amazon-chime-sdk-js/issues)
- [X] FAQs [page](https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html)
- [X] README [page](https://github.com/aws/amazon-chime-sdk-js#amazon-chime-sdk-for-javascript)
- [X] Feature-specific [guides](https://github.com/aws/amazon-chime-sdk-js#guides)

### Reproduction steps

1. 1st Participant join from desktop 
2. 2nd Participant join from mobile chrome browser
3. 3rd Participant join from desktop 

Means the mobile participant video is freezes. 1st and 3rd participant sees only freeze video. if 2nd participant leaves and again joins means also video is not showing to other 2 participants only black screen shows to them.

 I used 
 
 `amazon-chime-sdk-component-library-react: 2.11.1`
 `amazon-chime-sdk-js: 2.20.0`
 
 Mobile: android
 Browser: chrome
 version: 87.0.4280.101
 

### Amazon Chime SDK for JavaScript version

2.20.0

### What browsers are you seeing the problem on?

Chrome

### Browser version

87.0.4280.101

### Browser console logs

Since i am facing issues in mobile chrome browser alone. i did;t take any log from mobile.

**Comment by BC-Mikey** [comment] 2021-11-01 18:58
Hello,

This sounds a lot like an issue we're experiencing. I've logged a couple of scenarios where we experience issues broadcasting video from an Android to the <video> tags:

1. One or Two users with their camera on - one of them is an Android User
  a. Presenter begins screen sharing…
    i. Android User’s Attendee Tile will become frozen to all other users.
    ii. The Android User will continue to see themselves in the Users List as though everything was working fine.
  b. Presenter stops screen sharing…
    i. Android User’s Attendee Tile automatically starts presenting again.
3. Three or more people (including Android User) sharing cameras at the same time.
  a. When three or more people turn on their cameras at the same time, then the Android User’s AttendeeTile will freeze.
  b. Once the Meeting goes down to 2 Users sharing their camera (including the Android User) then the Android User will resume broadcasting their camera
4. Android User’s Tile turns black if the state changes while the video is frozen
  a. For example, if the video is currently frozen and we attempt to update the roster list, then that Tile will turn black because upon re-render of the <video> tag there will be no video broadcasting.
  b. Another example is when a new user joins the meeting. They will be rendering the list of Tiles for the first time and though a video tag is rendering, there is no video broadcasting to it.

Unfortunately, I didn't find much inside of the logs to gather more information.

Android Version: 10
Browser: Chrome 94.0.4606.85
Device: Google Pixel 4

`amazon-chime-sdk-component-library-react`: v2.9.1
`amazon-chime-sdk-js`: v2.16.1

**Comment by Rambarani** [comment] 2021-11-02 07:13
@ltrung  Still we stuck with this issue. can you help me on this !!

**Comment by ltrung** [comment] 2021-11-03 01:31
@Rambarani @BC-Mikey We have been able to reproduce the issue on our side and I am working on a fix https://github.com/aws/amazon-chime-sdk-js/commit/eb072ced5f731f445cd238e420cc2942c23df60c. Could you pull the change here and see whether it fixes it for your Android devices (I think in some Pixel devices, it can be pixelated).

**Comment by Rambarani** [comment] 2021-11-03 01:57
Great ! thanks @ltrung . and how can i test this commit in my react project. can you guide me on that

**Comment by ltrung** [comment] 2021-11-03 17:01
You can pull the changes in my branch locally and run `npm run build` and `npm pack` to create a tar ball. You can then run npm install <tar ball location> to update `amazon-chime-sdk-js` dependency in your project.

**Comment by BC-Mikey** [comment] 2021-11-03 18:31
Hi @ltrung,

We've just completed some testing on our end. Here is what we found:

1) There was improved performance for 1 Android user sharing their camera when more than 2 attendees were also sharing their cameras inside of the same meeting. We only tested up to 5 cameras at the same time, along with 1 Android User, but their camera never froze, which is an improvement to what we were experiencing.

2) However, we did notice that two Android Users could not share camera at the same time. As soon as a second Android User would begin sharing their camera, both Android Users tiles became frozen or black (if they were the new user initiating a camera). When one turned their camera off, the other would come on.

3) Screen sharing appeared to be broken. Desktop users attempting to screen share were not able to start a screen share with this build. They were prompted to select a screen to share and begin sharing, however, the screen would flicker and then no screen sharing occurred.

The user who tried to screen share received these SDK errors in the browser console log:

```
react_devtools_backend.js:2540 2021-11-03T18:24:39.738Z [WARN] SDK - release media stream called
overrideMethod  @   react_devtools_backend.js:2540
log @   DefaultMeetingReadinessChecker.js:468
warn    @   DefaultMeetingReadinessChecker.js:432
releaseMediaStream  @   DefaultDeviceController.js:856
(anonymous) @   BreakoutRoom.js:103870
(anonymous) @   VideoPreference.js:11
./node_modules/amazon-chime-sdk-js/build/task/ReleaseMediaStreamsTask.js.__awaiter  @   VideoPreference.js:7
run @   VideoPreference.js:23
(anonymous) @   ReceiveVideoStreamIndexTask.js:25
(anonymous) @   ReceiveVideoInputTask.js:80
./node_modules/amazon-chime-sdk-js/build/task/BaseTask.js.__awaiter @   ReceiveVideoInputTask.js:76
baseRun @   ReceiveVideoStreamIndexTask.js:12
(anonymous) @   VideoPreferences.js:189
fulfilled   @   VideoPreferences.js:151
Promise.then (async)        
step    @   VideoPreferences.js:153
(anonymous) @   VideoPreferences.js:154
./node_modules/amazon-chime-sdk-js/build/task/SerialGroupTask.js.__awaiter  @   VideoPreferences.js:150
run @   VideoPreferences.js:181
(anonymous) @   ReceiveVideoStreamIndexTask.js:25
(anonymous) @   ReceiveVideoInputTask.js:80
./node_modules/amazon-chime-sdk-js/build/task/BaseTask.js.__awaiter @   ReceiveVideoInputTask.js:76
baseRun @   ReceiveVideoStreamIndexTask.js:12
(anonymous) @   DefaultAudioVideoController.js:538
fulfilled   @   DefaultAudioVideoController.js:12
Promise.then (async)        
step    @   DefaultAudioVideoController.js:14
(anonymous) @   DefaultAudioVideoController.js:15
./node_modules/amazon-chime-sdk-js/build/audiovideocontroller/DefaultAudioVideoController.js.__awaiter  @   DefaultAudioVideoController.js:11
actionDisconnect    @   DefaultAudioVideoController.js:522
(anonymous) @   DefaultAudioVideoController.js:512
perform @   SignalingProtocol.js:604
performDeferredAction   @   SignalingProtocol.js:658
perform @   SignalingProtocol.js:612
(anonymous) @   DefaultAudioVideoController.js:424
fulfilled   @   DefaultAudioVideoController.js:12
Promise.then (async)        
step    @   DefaultAudioVideoController.js:14
(anonymous) @   DefaultAudioVideoController.js:15
./node_modules/amazon-chime-sdk-js/build/audiovideocontroller/DefaultAudioVideoController.js.__awaiter  @   DefaultAudioVideoController.js:11
actionConnect   @   DefaultAudioVideoController.js:319
(anonymous) @   DefaultAudioVideoController.js:237
perform @   SignalingProtocol.js:604
(anonymous) @   DefaultAudioVideoController.js:236
startReturningPromise   @   DefaultAudioVideoController.js:235
start   @   DefaultAudioVideoController.js:216
(anonymous) @   DefaultDeviceController.js:993
(anonymous) @   DefaultDeviceController.js:946
./node_modules/amazon-chime-sdk-js/build/contentsharecontroller/DefaultContentShareController.js.__awaiter  @   DefaultDeviceController.js:942
startContentShare   @   DefaultDeviceController.js:983
(anonymous) @   DefaultDeviceController.js:1002
fulfilled
```

**Comment by ltrung** [comment] 2021-11-03 20:45
@BC-Mikey Thanks for testing. I think this is due to our video uplink bandwidth policy tries to scale the resolution down based on the number of attendees and Android H.264 video encoding has issue with it. We could reproduce the 2nd issue when there are 5 or more videos in the call (so it is not about how many android video on the call).

We could not reproduce the 3rd issue though and it does not seem to be related to the main issue. Could you try using new release version 2.21 and see if you could reproduce it?

**Comment by nmonasterio** [comment] 2021-11-04 01:13
@ltrung Thank you for this as well. We've done some testing on our end as well. Findings:

- Android users (when there are three or more users on a call, and at least one Android user) seem to be staying on the call more reliably. And the video does not freeze or disappear as often. (Though it sometimes did).
- We're still experiencing some echo issues with certain Android devices. Is that something you may have experienced as well, @BC-Mikey?)

Also, for context, we've been implementing `VideoAdaptiveProbePolicy` as our `videoDownlinkBandwidthPolicy` as well as `multicast`. This seems to be the most reliable combination for Android users to get a quality feed.

Happy to share logs as well as needed.

Thank you!

**Comment by BC-Mikey** [comment] 2021-11-04 20:56
@ltrung the screenshare issue may have been unrelated. We pulled the latest "amazon-chime-sdk-component-library-react" &  "amazon-chime-sdk-js" libraries and weren't able to reproduce.

@nmonasterio we did do some more testing this afternoon and I did not notice any echoing issues with my Google Pixel 4. Our other team member on a Galaxy S21 did not notice anything out of the ordinary.

**Comment by nmonasterio** [comment] 2021-11-05 01:10
@BC-Mikey / @ltrung Interesting. I think it's unrelated, but it's quite easy to replicate on a Motorola G Power. We've been able to replicate it both our environment as on the Chime React demo app. I'll open up a new issue on it. It does go away when implementing Voice Focus, however.

**Comment by ltrung** [comment] 2021-11-05 01:13
@BC-Mikey Can you pull the PR #1751 and verify if it fixes the issue for you when you are enable more than 4 videos?

**Comment by BC-Mikey** [comment] 2021-11-05 15:55
@ltrung we just tested with the following devices on in the same meeting:
- Google Pixel 4, Android 10
- Galaxy A8+, Android 9
- Galaxy S21, Android 11
- iPad, OS 15.1
- iPhone OS 15.0.2
- Three Chrome Web browsers

The Google Pixel 4 & Galaxy S21 had no issues broadcasting video on the latest build. Even when all other attendees had their cameras on.

The Galaxy A8+ was a new device we hadn't tested previously. It looked like this device experienced the same freezing issue even when no other attendees were broadcasting. All in all, I'd say this is a huge improvement and I am wondering if you are aware of any known issues involving the Galaxy A8 device or Android 9?

**Comment by ltrung** [comment] 2021-11-05 18:32
@BC-Mikey Thanks for testing. It seems like the issue with Galaxy A8+ is not the same issue (since there is only one video on the call there is no downscaling happens). Could you create a different issue to track that?

**Comment by ltrung** [comment] 2021-11-29 23:53
Close this as the fix has been relesed.

**Closed by ltrung** 2021-11-29 23:53 UTC
Labels: Bug
