### ISSUE TITLE
Video stream doesn't show up on the web when connected from Android App (Chime Android SDK) on the cellular network 

### ISSUE THREAD

**Issue by ashrafhere** [aws/amazon-chime-sdk-js#1990] opened 2022-02-04 17:18 UTC
### What happened and what did you expect to happen?

Video stream doesn't show up on the web when connected from Android App (Chime Android SDK) on the cellular network.  It works when the android app is connected with wifi, video streaming stops the moment I switch to the cellular network. It seems like it has to do something with the bandwidth, but there is no place in the API to connect with the lower bandwidth. Need help urgently. The person with the web browser cannot see the person with the Android App, but the person on the Android app can see the person from the web browser.

### Have you reviewed our existing documentation?

- [X] GitHub [issues](https://github.com/aws/amazon-chime-sdk-js/issues)
- [X] FAQs [page](https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html)
- [X] README [page](https://github.com/aws/amazon-chime-sdk-js#amazon-chime-sdk-for-javascript)
- [X] Feature-specific [guides](https://github.com/aws/amazon-chime-sdk-js#guides)

### Reproduction steps

Video stream doesn't show up on the web when connected from Android App (Chime Android SDK) on the cellular network.  It works when the android app is connected with wifi, video streaming stops the moment I switch to the cellular network. It seems like it has to do something with the bandwidth, but there is no place in the API to connect with the lower bandwidth. Need help urgently. The person with the web browser cannot see the person with the Android App, but the person on the Android app can see the person from the web browser.

### Amazon Chime SDK for JavaScript version

2.0.0

### What browsers are you seeing the problem on?

Chrome

### Browser version

Chrome, Version 97.0.4692.99 (Official Build) (x86_64)

### Meeting and Attendee ID Information.

One attendee is on the web using Chime JS SDK on chrome browser
The other one is on Android App using Chime SDK 

### Browser console logs

-

**Comment by ltrung** [comment] 2022-02-04 17:44
@ashrafhere Sorry but the version 2.0.0 is very old. Can you try to update to 2.26.0 and see if it resolves your issue?
Also is there any error thrown in console? A log would be great.

**Comment by ashrafhere** [comment] 2022-02-05 22:09
I mistyped it, we are using the latest version of 2.26.0. Please see attached the log files.
[Verbose Logs.log](https://github.com/aws/amazon-chime-sdk-js/files/8009002/Verbose.Logs.log)

**Comment by ashrafhere** [comment] 2022-02-05 22:10
Still can't get it to work, please help. 
Thank you.

**Comment by ashrafhere** [comment] 2022-02-06 14:15
More logs.
[Verbose (1).log](https://github.com/aws/amazon-chime-sdk-js/files/8010339/Verbose.1.log)

**Comment by ashrafhere** [comment] 2022-02-07 06:10
Here are more logs with my analysis and notes.
[More logs with notes.log](https://github.com/aws/amazon-chime-sdk-js/files/8012787/More.logs.with.notes.log)

**Comment by ricksonmenezes** [comment] 2022-02-07 09:05
I am working with @ashrafhere  on the same issue. Some insights on this issue. We have subscription policy adaptive for chromium set as true. This issue does not take place if android browser connects to PC chrome browser nor does it take place during a android app to android app or even the mobile app in WIFI <-> PC browser. It only takes place android app with mobile data internet  to web browser. 

We receive unmute event and a new stream index but  we don't get the "optimal rceiveSet {} in the logs. And it then prints resubscribe: false. after which chimelogs show: received a mute event fror title =2 and stream=10. At this moment, the tile goes blank.  

On the browser side where tile goes blank, we have in the JS, the following configuration

configuration.enablesimulcastforinifiedchromiumbasedbrowser = true;
configuration.videodownlinkbandwithpolicy = new ChimeSDK.VideoAdaptiveProbePolicy(logger)

then we pass the configuration to the meeting object. 

In the positive cases, it prints the entire optimalReceiveSet and the bwe: new StreamSelectionp[10] after which the should resubscribe is always true and the tile is never blank. But this is for positive conditions. What is the problem with mobile data. Is the subscription policy causing it not to subscribe? 

Are these configuration parameters working well in wifi for web <-> web meeting but causing the tile to go blank for web wifi <-> meeting with android app on mobile data connectin?

**Comment by ricksonmenezes** [comment] 2022-02-09 10:30
update: downgrading to Android SDK to 0.13x fixes the issue. So the issue persists in version that we had; 0.14.2

**Comment by xuesichao** [comment] 2022-02-09 19:21
@ashrafhere @ricksonmenezes Hi, I forwarded your updates to the same issue you opened in Chime Android SDK repo. Our Android SDK team will be working on a hotfix and keep you posted there.

Close this issue as duplicate.

**Closed by xuesichao** 2022-02-09 19:21 UTC

**Comment by rixiang-dev** [comment] 2022-08-03 20:52
@ricksonmenezes @ashrafhere as mentioned in https://github.com/aws/amazon-chime-sdk-android/issues/379, we have another back-end fix to address the root cause. If possible, could you validate this most-recent fix with same testing procedures to see if issue still persists, with the old version 0.14.2(https://github.com/aws/amazon-chime-sdk-android/releases/tag/v0.14.2)?  Thank you!
