### ISSUE TITLE
Video stream from Google Pixel 4XL distorted on receiving end.

### ISSUE THREAD

**Issue by shriyajuneja** [aws/amazon-chime-sdk-js#1846] opened 2021-12-02 18:18 UTC
### What happened and what did you expect to happen?

Remote video stream from Google Pixel 4XL is distorted for other participants

![image](https://user-images.githubusercontent.com/14612003/144477444-4e1a4fff-c3da-4fd7-b38c-7befd8151013.png)

### Have you reviewed our existing documentation?

- [X] GitHub [issues](https://github.com/aws/amazon-chime-sdk-js/issues)
- [X] FAQs [page](https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html)
- [X] README [page](https://github.com/aws/amazon-chime-sdk-js#amazon-chime-sdk-for-javascript)
- [X] Feature-specific [guides](https://github.com/aws/amazon-chime-sdk-js#guides)

### Reproduction steps

Connect meeting with Google Pixel 4XL and windows device, stream from Google Pixel 4XL will get distorted for windows user.

### Amazon Chime SDK for JavaScript version

2.17.0

### What browsers are you seeing the problem on?

windows chrome 

### Browser version

96

### Meeting and Attendee ID Information.

NA

### Browser console logs

NA

**Comment by ltrung** [comment] 2021-12-11 01:33
I think this issue happens to other pixel devices such as Pixel 3 and Pixel 3 XL too.

**Comment by beta-alpha001** [comment] 2021-12-21 12:34
Hi @ltrung, thanks for your response.

We do not have Pixel 3 or Pixel 3 XL to verify. Is this due to encoder issue with size not in 16's multiples or something else.

<img width="808" alt="Screenshot 2021-12-21 at 5 59 41 PM" src="https://user-images.githubusercontent.com/91276454/146930505-82927fb9-9e5e-4da4-a6e6-53e1a3de60b8.png">

**Comment by devalevenkatesh** [comment] 2021-12-29 01:39
I have a Pixel 3a XL and I can reproduce the pixelated video on the remote side in my device using our meetingV2 demo which uses the `amazon-chime-sdk-js`. To test further, I found that this is also reproducible in WebRTC official samples (You may try testing in below apps once):
- https://webrtc.github.io/samples/src/content/peerconnection/constraints/
- https://webrtc.github.io/samples/src/content/peerconnection/change-codecs/
- appr.tc

This is due to the video encoding issue in Android 12 Chrome. I am not sure if this is affecting lot of devices or some or other Android (Chrome) versions. In Android 12 Chrome I found that the "Hardware-accelerated video encoding" is enabled by default. One workaround is to manually disabling "Hardware-accelerated video encode" flag under `chrome://flags` on the affected device's Chrome. Disabling "Hardware-accelerated video encode" worked fine for me and video appeared as expected on the remote side on above samples + JS SDKs meetingV2 demo as well.

I found below Chromium bug for this:
https://bugs.chromium.org/p/chromium/issues/detail?id=1237677.

Hence, tagging this as a browser bug. Recent comments say that this is fixed in Chrome 97 to be released January 4, 2022. I also tested the resolution of 640 * 360 but that did not help in my case and still resulted in the pixelated video. I have updated the [Known browser compatibility issues list](https://github.com/aws/amazon-chime-sdk-js/issues/1059) with the chromium bug and unfortunately I could not found any programmatic workaround for this issue.

**Comment by devalevenkatesh** [comment] 2021-12-29 01:55
I just tested this with my Pixel 3a XL on the Chrome Beta App on Android 12 and could see the video coming through fine on the remote side.

Version details:
Chrome Beta App Version: 97.0.4692.56 (Installed from PlayStore).
Android 12 (beta) build number S2B1.211112.006.

**Comment by devalevenkatesh** [comment] 2022-01-13 23:28
i am closing this issue since Chrome 97 is released now and the video from my pixel 3a Xl appeared as expected on the remote attendee side in Android Chrome 97.

**Closed by devalevenkatesh** 2022-01-13 23:28 UTC
Labels: Browser Bug
