### ISSUE TITLE
Meeting not automatically ending

### ISSUE THREAD

**Issue by monique-sti** [aws/amazon-chime-sdk-js#2454] opened 2022-09-23 03:40 UTC
### What happened and what did you expect to happen?

A meeting is created using 1 attendee that shares their screen and webcam and a media capture pipeline is created to record this attendee. 

Usually, when ending a meeting, the audio and video are disconnected from the meeting (no webcam or screen share) and the media capture pipeline delete is triggered in an event that will then trigger post-processing of the media recorded with the following event pattern:

```
{
  "detail-type": ["Chime Media Pipeline State Change"],
  "source": ["aws.chime"],
  "detail": {
    "eventType": ["chime:MediaPipelineDeleted"]
  }
}
```

 

After a meeting of about 25 seconds, the meeting was forced to close "incorrectly", meaning that audio and video were disconnected but the media capture pipeline delete was never triggered. 

Following the [documentation](https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html#when-does-an-amazon-chime-sdk-meeting-end), using the Amazon Chime SDK Meetings namespace, the meeting now currently contains only the media capture pipeline that is not an audio connection. Chunks for the screen are no longer being generated but black screen chunks for the webcam are still generated, because the attendee is no longer there.

This results in the [final webcam video](https://drive.google.com/file/d/1lboHHCvytuKfnvaAwaJ_v30X3zm_8wCz/view?usp=sharing) (chunks stitched together) with a duration of ~6 hours only showing 25 seconds of webcam image and the rest is in black. The media capture pipeline should have detected inactivity after 5 minutes and trigger the deletion of the media capture pipeline. 

### Have you reviewed our existing documentation?

- [X] GitHub [issues](https://github.com/aws/amazon-chime-sdk-js/issues)
- [X] FAQs [page](https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html)
- [X] README [page](https://github.com/aws/amazon-chime-sdk-js#amazon-chime-sdk-for-javascript)
- [X] Feature-specific [guides](https://github.com/aws/amazon-chime-sdk-js#guides)

### Reproduction steps

Using the [AWS Media Capture Pipeline Demo](https://github.com/aws-samples/amazon-chime-media-capture-pipeline-demo):

1. Create a recorded meeting with 1 attendee and share webcam and screen 
2. Stay on the meeting for about 1 minute.
3. Close the meeting browser tab WITHOUT leaving the meeting session. (Abruptly closing)

  

### Amazon Chime SDK for JavaScript version

3.5.0

### What browsers are you seeing the problem on?

Electron (Chromium)

### Browser version

Electron v15.3.1 / Chromium v94.0.4606.81

### Meeting and Attendee ID Information.

Meeting ID: 55a385fd-0893-467a-8e57-e5b717062713

### Browser console logs

N/A

**Comment by devalevenkatesh** [comment] 2022-09-26 20:27
Hello thanks for reporting this issue. Looks like you might be using the `ChimeSDKMeetings` namespace for creating the meetings. There are different auto-ending policies for `ChimeSDKMeetings` namespace:
https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html#when-does-an-amazon-chime-sdk-meeting-end

Also, closing meeting tab would not actually end/leave the meeting on its own. Builders will have to listen on to [Page visibility](https://developer.mozilla.org/en-US/docs/Web/API/Page_Visibility_API) and related browser events to know of the tab getting close and leave the meeting when that happens.

Please let us know if that helps and you have any further questions.

**Comment by devalevenkatesh** [comment] 2022-09-27 01:43
You may be right that the audio connections should get snapped when the tab is closed. Internally JS SDK falls back to an empty audio device if a connection audio device is disconnected. If that is the case, then, that empty audio will be the audio connection present in the meeting.

Could you provide browser console logs from this case to see whether that  empty audio fallback is the reason why the meeting did not auto-end?

**Comment by monique-sti** [comment] 2022-09-27 15:09
> 55a385fd-0893-467a-8e57-e5b717062713

We do not have browser console logs, but we do have meeting events. 

{"Timestamp":"2022-09-05T16:40:02.991+00:00","EventType":"CaptureStarted"}

{"Timestamp":"2022-09-05T16:40:03.575+00:00","EventType":"AttendeeJoined","EventParameters":{"AttendeeId":"6869080f-d028-d9ae-c015-38882089c696","MediaModality":""}}
{"Timestamp":"2022-09-05T16:40:03.575+00:00","EventType":"AttendeeMute","EventParameters":{"AttendeeId":"6869080f-d028-d9ae-c015-38882089c696","MediaModality":""}}


{"Timestamp":"2022-09-05T16:40:03.854+00:00","EventType":"AttendeeJoined","EventParameters":{"AttendeeId":"753f5461-8073-eaa5-af41-f920de367732#content","MediaModality":""}}
{"Timestamp":"2022-09-05T16:40:03.854+00:00","EventType":"AttendeeMute","EventParameters":{"AttendeeId":"753f5461-8073-eaa5-af41-f920de367732#content","MediaModality":""}}
{"Timestamp":"2022-09-05T16:40:04.334+00:00","EventType":"AttendeeUnmute","EventParameters":{"AttendeeId":"753f5461-8073-eaa5-af41-f920de367732#content","MediaModality":""}}
{"Timestamp":"2022-09-05T16:40:04.334+00:00","EventType":"ActiveSpeaker","EventParameters":{"AttendeeId":"","MediaModality":""}}
{"Timestamp":"2022-09-05T16:40:04.654+00:00","EventType":"AttendeeJoined","EventParameters":{"AttendeeId":"753f5461-8073-eaa5-af41-f920de367732","MediaModality":""}}
{"Timestamp":"2022-09-05T16:40:04.694+00:00","EventType":"ActiveSpeaker","EventParameters":{"AttendeeId":"753f5461-8073-eaa5-af41-f920de367732","MediaModality":""}}
{"Timestamp":"2022-09-05T16:40:04.733+00:00","EventType":"AttendeeVideoJoined","EventParameters":{"AttendeeId":"753f5461-8073-eaa5-af41-f920de367732#content","MediaModality":"ContentShare"}}
{"Timestamp":"2022-09-05T16:40:05.201+00:00","EventType":"AttendeeVideoJoined","EventParameters":{"AttendeeId":"753f5461-8073-eaa5-af41-f920de367732","MediaModality":"Video"}}


{"Timestamp":"2022-09-05T16:40:23.414+00:00","EventType":"ActiveSpeaker","EventParameters":{"AttendeeId":"","MediaModality":""}}
{"Timestamp":"2022-09-05T16:40:23.934+00:00","EventType":"ActiveSpeaker","EventParameters":{"AttendeeId":"753f5461-8073-eaa5-af41-f920de367732","MediaModality":""}}


{"Timestamp":"2022-09-05T16:40:29.676+00:00","EventType":"AttendeeVideoLeft","EventParameters":{"AttendeeId":"753f5461-8073-eaa5-af41-f920de367732","MediaModality":"Video"}}
{"Timestamp":"2022-09-05T16:40:29.686+00:00","EventType":"AttendeeVideoLeft","EventParameters":{"AttendeeId":"753f5461-8073-eaa5-af41-f920de367732#content","MediaModality":"ContentShare"}}

{"Timestamp":"2022-09-05T16:40:29.718+00:00","EventType":"ActiveSpeaker","EventParameters":{"AttendeeId":"753f5461-8073-eaa5-af41-f920de367732","MediaModality":""}}
{"Timestamp":"2022-09-05T16:40:29.718+00:00","EventType":"AttendeeLeft","EventParameters":{"AttendeeId":"753f5461-8073-eaa5-af41-f920de367732#content","MediaModality":""}}
{"Timestamp":"2022-09-05T16:40:29.719+00:00","EventType":"ActiveSpeaker","EventParameters":{"AttendeeId":"","MediaModality":""}}
{"Timestamp":"2022-09-05T16:40:29.719+00:00","EventType":"AttendeeLeft","EventParameters":{"AttendeeId":"753f5461-8073-eaa5-af41-f920de367732","MediaModality":""}}

{"Timestamp":"2022-09-05T22:40:28.857+00:00","EventType":"CaptureEnded"}

As a side note, the Attendee Id of the user is 753f5461-8073-eaa5-af41-f920de367732.

**Comment by monique-sti** [comment] 2022-09-30 16:15
Hi @devalevenkatesh! Just wanted to check if there is an update/follow-up on this?

**Comment by devalevenkatesh** [comment] 2022-09-30 22:26
So, I checked the [client meeting events](https://aws.github.io/amazon-chime-sdk-js/modules/meetingevents.html) as well which JS SDK sends and could not see any `audioInputUnselected` events. Thus, I think you have to explicitly stop the audio and leave the meeting to stop the meeting in such cases. If not, JS SDK will fallback to empty audio input device and that sends a audio frequency which will keep the connection with the meeting alive.

Can you try that see this behavior is not reproduced?

**Comment by ltrung** [comment] 2022-09-30 23:14
@monique-sti Sorry for the confusion but right now we need audio connection for all attendees to know who connects to meeting. For media pipeline attendee, it is a muted empty audio stream but it is still counted as an attendee. So in your case you would need to listen to event where all attendee leaves then stop the media pipeline meeting manually.

**Comment by monique-sti** [comment] 2022-10-03 14:26
Thanks @devalevenkatesh @ltrung!

We were not aware that its still considered an audio stream! Understood. 

Would it be optimal to check with the **AttendeeLeft** event, compare it with the Attendee Id, see if its the actual user attendee and then manually stop the media pipeline? Or is there a better way to stop it?

**Comment by devalevenkatesh** [comment] 2022-10-10 20:18
May be better to handle the tab leave / window close as well first and then do the meeting leave explicitly first, and then track attendees in the meeting as well to see whether all are dropped/left and then stop it?

**Comment by dbish** [comment] 2023-04-19 17:32
Just to add one other customer voice here, this is a bit confusing. I stumbled upon this issue when trying to figure out why all my meetings were running for the max time of 24hrs (and why I was being charged for transcription over a very long meeting instead of the actual 10-20 minute meetings that were happening). This feels like unexpected and undocumented behavior since all the docs talk about a meeting auto-ending after 5 minutes when no one is in the meeting.

**Comment by CodySchaaf** [comment] 2023-08-01 19:13
We also have run into this, hard to determine when to call the `deleteMediaCapturePipeline` in order to initiate the `MediaConcatenationPipeline`.

**Comment by sarthakbaweja148** [comment] 2023-11-14 14:20
@devalevenkatesh @ltrung : We have faced this same issue, where the meeting keeps on going for hours (and we keep on getting charged for it ) without any actual attendee, when media pipeline is active.

We have bypassed this for now by checking continuously through a 10 minute cron, if there is any actual attendee present in the meeting besides the media pipeline user, and deleting the meeting if that is the case. But this still feels like a hack/workaround to the core issue, that the behavior is not same as documented (i.e. meeting auto-ending after 5 minutes when no one is in the meeting ). 

I would strongly suggest the Chime team to handle this at their end [ or at the very least, document it ] and not expect the customers to handle this, as this directly impacts cost, that too exponentially.

**Comment by v2okimochi** [comment] 2023-12-10 03:01
Maybe I have same issue. I started a Chime Meeting using `Amazon Chime SDK live transcription` and `Media Capture Pipeline` for about 2 minutes, but there is weird log at transcription-messages:

```
"LimitExceededException: Your audio stream has been running for too long. It exceeded the 4 hour limit."
```

I'm confused about getting large billing of Amazon Transcribe (I guess there are increased by transcription for 4 hour).

Also I saw this post. https://repost.aws/questions/QU-2wJ7bAFSiSgwQ_ay0cO9Q/transcribe-cost-enablement-with-chime-sdk

Need help us to solve it :( Should I delete Chime Meeting when attendees except for MediaPipeline are leaved? (is this only way now?)

**Comment by dbish** [comment] 2023-12-10 03:58
@v2okimochi what we do now(and we're managing this in python in the server side) is keep track of the number of attendees in the session, and when the last one disconnects/leaves we stop transcription and end the meeting. There isn't a working automatic shut down for chime sdk meetings if you're using transcription, which is too bad, but not that hard to work around. My main complaint is that the docs aren't clear on that.

Here's some code we use if it's helpful. End + shutdown after we know the last person left:

```

async def end_meeting(meeting_id):
    log("stopping transcription on meeting")
    try:
        result = await asyncify(chime_sdk_client.stop_meeting_transcription)(
            MeetingId=meeting_id
        )
        if result["ResponseMetadata"]["HTTPStatusCode"] != 200:
            log("failed to stop transcription for meeting " + meeting_id)
            log(result)
    except Exception:
        util.logger.exception("Couldn't stop transcription")

    log("deleting meeting")
    try:
        result = await asyncify(chime_sdk_client.delete_meeting)(MeetingId=meeting_id)
        if result["ResponseMetadata"]["HTTPStatusCode"] != 204:
            log("failed to delete meeting " + meeting_id)
            log(result)
    except Exception:
        util.logger.exception("Couldn't delete meeting")

```

This is based on us tracking users server side in an object kept in memory. We're using websockets to keep a connection and know if the connection is lost and update this object on connect and disconnect (and for error cases where we lose a connection), but you could do this in a few different ways:

```
...
        self.conference_call = {
            'meetingId': None,
            'attendees': set()
        }
        # If a meeting is in process of being created, this allows awaiting that meeting creation
        self.pending_meeting_future = None

    # returns false if the call is now empty
    def remove_user_from_call(self, user_id: str) -> bool:
        self.conference_call['attendees'].remove(user_id)
        if len(self.conference_call['attendees']) == 0:
            return False
        return True

    def add_user_to_call(self, user_id: str):
        if user_id in self.conference_call['attendees']:
            return False
        self.info.activity_registered = True
        self.info.is_empty_recording = False
        self.conference_call['attendees'].add(user_id)
        return True
        ...
```

**Comment by v2okimochi** [comment] 2023-12-10 08:28
@dbish Thanks for your kindness. Probably I can choose similar way on our use case of serverless application.
I will consider to watch Chime Meeting status using as reference this plan.

**Comment by ltrung** [comment] 2023-12-11 17:20
Thank everyone. This is something we are looking into and will post back once we have a plan.

**Comment by lvillacin** [comment] 2024-04-27 15:58
Hi! Are there any updates here?

**Comment by yochum** [comment] 2024-11-14 20:47
Closing this issue as it does not directly pertain to the Chime SDK for JavaScript. Please do reach out through your AWS account team or contact us in AWS Console for further help on this topic. Much appreciated.

**Closed by yochum** 2024-11-14 20:47 UTC
Labels: feature-request, Triaged, meeting-service
