### ISSUE TITLE
Video Tile Scaling

### ISSUE THREAD

**Issue by mlboudreau** [aws/amazon-chime-sdk-js#2955] opened 2024-09-11 18:50 UTC
Have noticed that sometimes a user's video tile slowly scales to size.  It's possible this only happens when someone has a higher resolution camera.  Are there any suggestions for how to handle this so the user doesn't see the gradual scaling?

**Comment by hensmi-amazon** [comment] 2024-09-19 17:28
Can you provide more detail or a video? Is this reproducible in the SDK demo app?

**Comment by hensmi-amazon** [comment] 2024-11-05 20:43
Resolving due to age

**Closed by hensmi-amazon** 2024-11-05 20:43 UTC
Labels: Question, video

**Comment by hensmi-amazon** [comment] 2024-11-06 01:57
Also should be fixed by https://github.com/aws/amazon-chime-sdk-js/pull/2987 I think!
