### ISSUE TITLE
Cannot release microphone after disconnection since upgrade from 2.4 to 2.9.0

### ISSUE THREAD

**Issue by massimo-bortolamei-hegias** [aws/amazon-chime-sdk-js#1305] opened 2021-05-20 12:59 UTC
I am working on a custom porting of the chime-sdk version 2.9 into AFRAME (webVR framework). Since updating from 2.4 to 2.9 I had troubles with choosing the audioInputDevice.
Before, the following was working

     this.audioInput = await navigator.mediaDevices.getUserMedia({ audio: true, video: false });
     await this.audioVideo.chooseAudioInputDevice(this.audioInput);

after the update to 2.9, I run into a connection loop due to chooseAudioInputDevice not accepting a MediaStream anymore.
In order to solve this, and be consistent with my application where we don't show a custom UI for choosing the microphone, but rely on the one chosen via browser's permission request, I ended up with the following script.
```
this.listAudioInputDevices = await this.audioVideo.listAudioInputDevices();
this.audioInput = await navigator.mediaDevices.getUserMedia({
  audio: true,
  video: false,
});
this.audioTracks = this.audioInput.getAudioTracks();
this.chosenAudioInput;
this.listAudioInputDevices.some((audioInputDevice) => {
  var found = this.audioTracks.some((audioTrack) => {
    if (audioTrack.getSettings().deviceId === audioInputDevice.deviceId) {
      this.chosenAudioInput = audioInputDevice;
      return true;
    }
  });
  if (found) {
    return true;
  }
});
if (this.chosenAudioInput) {
  await this.audioVideo.chooseAudioInputDevice(this.chosenAudioInput);
}
```
Which basically cycles through all the AudioInputDevices and tries to match their deviceId with the one chosen via the browser's permission UI.
Incidentally, if you have a better way to do it, I would be elated to hear you out.

The problem is, since doing all this, whenever I disconnect from the meeting with
```
if(this.audioVideo){
      await this.audioVideo.chooseAudioInputDevice(null);
      this.audioVideo.stop();
    }
    this.audioVideo = null;
    this.listAudioInputDevices = null;
    this.audioInput = null;
    this.audioTracks = null;
    this.chosenAudioInput = null;
}
```
**the microphone icon (Firefox) or the recording dot (Chrome) stays red as if the tab was still using it .**

I tried looking at various documentation where everybody concurs that using chooseAudioInputDevice(null) is the method to release the microphone, I also experimented by manually calling

```
this.audioVideo.unbindAudioElement();
this.activeDevice = this.audioVideo.deviceController.activeDevices["audio"];
this.audioVideo.deviceController.releaseActiveDevice(this.activeDevice);
```

but everything to no vail.
I suspect this error comes from the abnormal way in which I choose the audioInput, but in the end I still feed a MediaDeviceInfo to chooseAudioInputDevice, therefore I don't get what I'm doing wrong.
Any help would be appreciated. Thanks
    
Attached you may find INFO-level logs during connection and disconnection. Apologies for the plain format (we have a custom logger) and for possible other logs mixed inbetween, coming from our application.
[loginfo - connection.txt](https://github.com/aws/amazon-chime-sdk-js/files/6515796/loginfo.-.connection.txt)
[loginfo - disconnection.txt](https://github.com/aws/amazon-chime-sdk-js/files/6515928/loginfo.-.disconnection.txt)

**Platform**
 - OS: Windows 10
 - Browser: Firefox v89.0b14
 - Browser 2: Chrome v90.0.44
 - Amazon Chime SDK: v2.9.0

**Comment by ltrung** [comment] 2021-05-20 18:27
@massimo-bortolamei-hegias Thanks for a detailed issue.
For the first issue, the `chooseAudioInputDevice` requires to call `listAudioInputDevices` beforehand. I am not sure why do you need to call getUserMedia yourselves. `listAudioInputDevices` already calls `getUserMedia` internally to retrieve the device labels https://github.com/aws/amazon-chime-sdk-js/blob/master/src/devicecontroller/DefaultDeviceController.ts#L140
After calling `const audioDevices = await audioVideo.listAudioInputDevices()`, you can just call chooseAudioInputDevice(audioDevices[0]) to select the first audio device for example.

For the second issue, i do not think you have to manually clean up the audio stream as seen in our meeting demo https://github.com/aws/amazon-chime-sdk-js/blob/master/demos/browser/app/meetingV2/meetingV2.ts#L1433

AudioVideoController should try to release all media stream upon disconnecting https://github.com/aws/amazon-chime-sdk-js/blob/master/src/audiovideocontroller/DefaultAudioVideoController.ts#L671

**Comment by massimo-bortolamei-hegias** [comment] 2021-05-21 12:13
Hi @ltrung thanks for helping!
yes I saw that `listAudioInputDevices` already calls `getUserMedia` internally to retrieve the device labels, (and I also wanted to write another issue about that, given that calling it makes the webcam blink briefly due to ` { audio: true, video: true }`.
Anyways, selecting the correct audio device is not as simple as `chooseAudioInputDevice(audioDevices[0])`, because one could have multiple devices attached. In my simple use case I have oculus virtual microphone, HTC vive's microphone, webcam's microphone, and possibly another external mic. 
That is why I came up with that script which fetches (in my understanding) the userMedia the user gave permissions to, and then matches it against the list of audioinput devices, to find the corresponding MediaDeviceInfo.
If the result of  `getUserMedia` could be more than one input device, then I might have a problem with that script as well. But form me it was always only one, even with multiple microphones attached.

As for releasing the media manually, I don't know what to say. I also saw that it should be automatic but that was not the case for me. I'll try to remove the manual call to getUserMedia , fetch a random MediaDeviceInfo from the list of devices and then see if it gets correctly released. I'll come back with an answer by next week. 

For now, thank you very much for you interest and help!

**Comment by ltrung** [comment] 2021-05-21 18:57
> yes I saw that listAudioInputDevices already calls getUserMedia internally to retrieve the device labels, (and I also wanted to write another issue about that, given that calling it makes the webcam blink briefly due to { audio: true, video: true }.

You can define your own deviceLabelTrigger without video (See how to define your own trigger in our meeting demo for example https://github.com/aws/amazon-chime-sdk-js/blob/master/demos/browser/app/meetingV2/meetingV2.ts#L1739).

> Anyways, selecting the correct audio device is not as simple as chooseAudioInputDevice(audioDevices[0]), because one could have multiple devices attached. In my simple use case I have oculus virtual microphone, HTC vive's microphone, webcam's microphone, and possibly another external mic.

So in the usual workflow, we just use `listAudioInputDevices` to list all audio devices and let user select which devices. Then we can pass the corresponding deviceId to `chooseAudioInputDevices`. Thus, we do not need a special handling like your case.

**Comment by massimo-bortolamei-hegias** [comment] 2021-05-26 08:31
Hello, sorry for delay.
I tested removing the call to `getUserMedia` and the release of the mic worked.
I tried to implement my own `deviceLabelTrigger`, calling a custom `{ audio: true, video: false}` not to have the webcam blink and also keeping track of the user chosen media, so that i could later on match it with the ones from `listAudioInputDevices` and understand which `MediaDeviceInfo` pass to `chooseAudioInputDevices`.
Unfortunately, whenever labels are already present for some reasons (a bad cleanup-disconnection of chime or even more frequently the user checking the 'remember this' flag when giving permissions), the custom labelTrigger would obviously not trigger, and in order to understand which media he chose I can only call `getUserMedia`, which circles back to the problem with releasing the mic.
I believe that depends on the fact that `getUserMedia` does something strange internally and returns a MediaStream with different id each time it gets called. 
Anyways, I had to go back to my solution of calling it once everytime, manually, before listing the audioInputDevices, so I don't have the camera flickering, the labels get assigned, and I can save a reference to the track to later disable when disconnecting.

My takeaway is that it would be nice to have the ability to reuse firefox UI for chosing the input mic, and (in case the user flagged 'remember this') match the chosen `MediaStream `with the corresponding `MediaDeviceInfo`.

**Comment by ltrung** [comment] 2021-05-28 01:42
> Unfortunately, whenever labels are already present for some reasons (a bad cleanup-disconnection of chime or even more frequently the user checking the 'remember this' flag when giving permissions), the custom labelTrigger would obviously not trigger, and in order to understand which media he chose I can only call getUserMedia, which circles back to the problem with releasing the mic.

Can you clarify this? I do not think the issue is with users remember the permission but is because we cache device list and thus do not trigger your custom label Trigger again.
If you could clarify the scenario that you ran into, we can see if we could fix it :)

**Comment by ltrung** [comment] 2021-06-04 00:49
@massimo-bortolamei-hegias #1328 allows you to reset the device cache by passing in forceUpdate so closing the issue for now. Feel free to reopen or open new issues if you still have issues.

**Closed** 2021-06-10 23:31 UTC
Labels: device
