### ISSUE TITLE
Screen Share started but not streaming the contents

### ISSUE THREAD

**Issue by Sagar1219** [aws/amazon-chime-sdk-js#1511] opened 2021-08-15 09:19 UTC
Hi @devalevenkatesh ,

I am implementing screen share module, this is the console.log from which I think the req. screen share functions seems to be working fine but I am unable to stream the screen share contents :

``` 2021-08-15T08:57:57.661Z [INFO] ChimeMeetingLogs - timeout task AudioVideoUpdate/b5253761-0677-42a7-970e-a9ff32220706/b353e94c-0600-cd5d-54f7-4312553cb04e#content/Timeout15000ms completed
ConsoleLogger.js:68 

2021-08-15T08:57:57.661Z [INFO] ChimeMeetingLogs - AudioVideoUpdate/b5253761-0677-42a7-970e-a9ff32220706/b353e94c-0600-cd5d-54f7-4312553cb04e#content/Timeout15000ms took 313 ms
ConsoleLogger.js:68 

2021-08-15T08:57:57.662Z [INFO] ChimeMeetingLogs - serial group task AudioVideoUpdate/b5253761-0677-42a7-970e-a9ff32220706/b353e94c-0600-cd5d-54f7-4312553cb04e#content completed subtask AudioVideoUpdate/b5253761-0677-42a7-970e-a9ff32220706/b353e94c-0600-cd5d-54f7-4312553cb04e#content/Timeout15000ms
ConsoleLogger.js:68 

2021-08-15T08:57:57.662Z [INFO] ChimeMeetingLogs - serial group task AudioVideoUpdate/b5253761-0677-42a7-970e-a9ff32220706/b353e94c-0600-cd5d-54f7-4312553cb04e#content completed
ConsoleLogger.js:68 

2021-08-15T08:57:57.662Z [INFO] ChimeMeetingLogs - AudioVideoUpdate/b5253761-0677-42a7-970e-a9ff32220706/b353e94c-0600-cd5d-54f7-4312553cb04e#content took 322 ms
ConsoleLogger.js:68 

2021-08-15T08:57:57.662Z [INFO] ChimeMeetingLogs - transitioning from Updating to Connected with FinishUpdating
ConsoleLogger.js:68 

2021-08-15T08:57:57.665Z [INFO] ChimeMeetingLogs - updated audio-video session
ConsoleLogger.js:68 

2021-08-15T08:57:57.666Z [INFO] ChimeMeetingLogs - peer connection state changed: connected
cq_bi_articles_ac80_chime.js:367 

Attendee ID: b353e94c-0600-cd5d-54f7-4312553cb04e#content Present: true Position: 1
cq_bi_articles_ac80_chime.js:404 

You called startContentShareFromScreenCapture
cq_bi_articles_ac80_chime.js:408 

Screen share started cq_bi_articles_ac80_chime.js:408  ```

This is the HTML for the video element of screen share module : 

```<div id="tile-1" class="video-tile"  style="height: -webkit-fill-available; height: -moz-fit-content">
          <video id="video-1" class="video-tile-video"></video>
          <div id="attendeeid-1" class="video-tile-attendeeid"></div>
          <div id="nameplate-1" class="video-tile-nameplate"></div>
          <div id="pause-state-1"></div>
</div>
```

I have referenced the JS from [here](https://github.com/aws/amazon-chime-sdk-js#screen-and-content-share) but anyways will be good to have a look at what I have in my file. 

```
$('#screen-share-start').on('click',function(e){
        let executeScreenShare = async() => {
            try {
                const observer = {
                    videoTileDidUpdate: tileState => {
                        // Ignore a tile without attendee ID and videos.
                        if (!tileState.boundAttendeeId || !tileState.isContent) {
                            return;
                        }
                    
                        const yourAttendeeId = meetingSession.configuration.credentials.attendeeId;
                    
                        // tileState.boundAttendeeId is formatted as "attendee-id#content".
                        const boundAttendeeId = tileState.boundAttendeeId;
                    
                        // Get the attendee ID from "attendee-id#content".
                        const baseAttendeeId = new ChimeSDK.DefaultModality(boundAttendeeId).base();
                        if (baseAttendeeId === yourAttendeeId) {
                            console.log('You called startContentShareFromScreenCapture');
                        }
                    },
                    contentShareDidStart: () => {
                        console.log('Screen share started');
                    },
                    contentShareDidStop: () => {
                        // Chime SDK allows 2 simultaneous content shares per meeting.
                        // This method will be invoked if two attendees are already sharing content
                        // when you call startContentShareFromScreenCapture or startContentShare.
                        console.log('Screen share stopped');
                    }
                };                    
                meetingSession.audioVideo.addContentShareObserver(observer);
                meetingSession.audioVideo.addObserver(observer);
                    
                const contentShareStream = await audioVideo.startContentShareFromScreenCapture();
                DefaultVideoTile.connectVideoStreamToVideoElement(contentShareStream, 'video-1', false);
            } catch (error) {
                console.log("executeScreenShare : ",error);
            }
        };
        executeScreenShare();
    }); 
```

Let me know what I am missing here or what is going wrong?

**Comment by devalevenkatesh** [comment] 2021-08-17 01:49
Hi @Sagar1219 ,

Thanks for filing the issue. We request you to please use our [bug-report template](https://github.com/aws/amazon-chime-sdk-js/issues/new?assignees=&labels=&template=bug-report.yaml) while creating issues as it helps us to gather more information in first check and solve the issue better.

I checked the code snippet and the problematic line is this:
```js
// You are passing string 'video-1' where the API expects a HTML Video Element.
DefaultVideoTile.connectVideoStreamToVideoElement(contentShareStream, 'video-1', false);
```

Could you please check and pass the video element instead?
```js
const videoEl = document.getElementById('video-1');
DefaultVideoTile.connectVideoStreamToVideoElement(contentShareStream, videoEl, false);
```
Please check API parameters [here](https://github.com/aws/amazon-chime-sdk-js/blob/master/src/videotile/DefaultVideoTile.ts#L18).

You can also use `bindVideoElement` API inside the `videoTileDidUpdate` to bind the video element.
```js
videoTileDidUpdate: tileState => {
  // Ignore a tile without attendee ID and videos.
  if (!tileState.boundAttendeeId || !tileState.isContent) {
    return;
  }

  const yourAttendeeId = meetingSession.configuration.credentials.attendeeId;

  // tileState.boundAttendeeId is formatted as "attendee-id#content".
  const boundAttendeeId = tileState.boundAttendeeId;

  // Get the attendee ID from "attendee-id#content".
  const baseAttendeeId = new ChimeSDK.DefaultModality(boundAttendeeId).base();
  if (baseAttendeeId === yourAttendeeId) {
    console.log('You called startContentShareFromScreenCapture');
    // Bind the video element here, this will be you own local content share as you are comparing the 
    // attendee IDs.
    const videoEl = document.getElementById('video-1');
    meetingSession.audioVideo.bindVideoElement(tileState.tileId, videoEl);
  }
}
```
This way you wont need the `DefaultVideoTile.connectVideoStreamToVideoElement` API.

Please let us know if this fixes your issue.

**Comment by Sagar1219** [comment] 2021-08-23 07:17
Hi @devalevenkatesh, this did resolve the issue but now it's streaming infinite videos, how to stop this?

![Screenshot (224)](https://user-images.githubusercontent.com/14037958/130406218-c12d3662-ae43-4a4d-a64d-7d56f79702df.png)

**Comment by devalevenkatesh** [comment] 2021-08-23 16:26
Hi @Sagar1219 ,

So, this infinite loop is actually the behavior when you share your screen where the application is running and show the content share tile in your application. I think you will find the same behavior on other WebRTC browser screen share based demos. You can check the official WebRTC screen sharing sample [here](https://webrtc.github.io/samples/src/content/getusermedia/getdisplaymedia/).

This is not a bug in JS SDK but a general behavior. This would not be the behavior when you share a different screen and not the one where you are running your application.

We are glad the issue is fixed for you and as we cannot do more further I am closing this issue. Please feel free to file new issues for any questions you have.

**Closed by devalevenkatesh** 2021-08-23 16:26 UTC
Labels: Question, chime-setup
