### ISSUE TITLE
The left edge of the camera footage is cut off on Google Pixel

### ISSUE THREAD

**Issue by hajime-goshima** [aws/amazon-chime-sdk-js#2545] opened 2023-01-11 07:23 UTC
### What happened and what did you expect to happen?

Although I had hoped that the camera footage would be displayed normally without any parts being cut off, it seems that the left side of the camera footage is being cut off.

The problem occurs only in the video displayed on the sender side, and the video displayed on the receiver side is displayed without any problem.

![image](https://user-images.githubusercontent.com/13103747/211745056-b201b0f0-fe81-414e-856e-5e136bcdb326.png)

### Have you reviewed our existing documentation?

- [X] GitHub [issues](https://github.com/aws/amazon-chime-sdk-js/issues)
- [X] FAQs [page](https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html)
- [X] README [page](https://github.com/aws/amazon-chime-sdk-js#amazon-chime-sdk-for-javascript)
- [X] Feature-specific [guides](https://github.com/aws/amazon-chime-sdk-js#guides)

### Reproduction steps

You will join the meeting using Google Pixel.

Pixel 6(android13):NG
Pixel 6a(android13):NG
Xperia 5 IV SO-54C(android13)：OK
Galaxy S22 SC-51C(android13)：OK

### Amazon Chime SDK for JavaScript version

3.6.0, 3.10.0

### What browsers are you seeing the problem on?

Google Chrome(Android default browser)

### Browser version

chrome 108.0.5359.128

### Meeting and Attendee ID Information.

Meeting ID: 43d6c6dc-f318-436a-ac53-551d5c272713
Attendee ID: 1b87374d-7403-b0da-dfe2-462fceeb01f0

### Browser console logs

[console.log](https://github.com/aws/amazon-chime-sdk-js/files/10389689/demo.dev.biz.thumva.com-1673418663132.log)

**Comment by hajime-goshima** [comment] 2023-01-26 02:18
We have confirmed that it does not reproduce on chrome 109.0.5414.118.

It may have been a chrome108 specific issue.
We could not determine the cause.

**Comment by ltrung** [comment] 2023-01-26 02:26
Does that mean you can reproduce it still in Chrome 108? If so can you try the webRTC sample I mentioned above?

**Comment by hajime-goshima** [comment] 2023-01-26 02:33
Sorry.
We already do not have any Chrome108 devices.
We have not been able to check with webRTC Samples.

At the time I submitted the Issue, I only checked with ChimeDemo.

**Comment by ltrung** [comment] 2023-01-26 02:35
I double check the test our QA run and it is Pixel 6 with Chrome 108 so it might not be the case then.
Since the issue is no longer reproducible, i will close it for now. Feel free to reopen it if you find additional information.

**Closed by ltrung** 2023-01-26 02:35 UTC
Labels: device
