### ISSUE TITLE
Cannot read property 'toLowerCasePropertyNames' of undefined

### ISSUE THREAD

**Issue by gsudhanshu** [aws/amazon-chime-sdk-js#1052] opened 2021-02-09 13:05 UTC
Description: I get meeting Response from server as json object as shown below in after createMeeting. and I get attendee response in json object format as shown below. When I try to instantiate a MeetingSessionConfiguration using these responses, I get error ERROR TypeError: Cannot read property 'toLowerCasePropertyNames' of undefined
    at toLowerCasePropertyNames (MeetingSessionConfiguration.js:157)

after createMeeting :
meetings.service.ts:19 
{Meeting: {…}, @metadata: {…}}@metadata: {statusCode: 201, effectiveUri: "https://chime.us-east-1.amazonaws.com/meetings", headers: {…}, transferStats: {…}}Meeting: ExternalMeetingId: "Meeting1"MediaPlacement: {AudioHostUrl: "79f1ea3279da5e1eb710020f92578ae5.k.m3.as1.app.chime.aws:3478", AudioFallbackUrl: "wss://haxrp.m3.as1.app.chime.aws:443/calls/9f8e3030-7d32-42d9-b425-efaee9ef2766", ScreenDataUrl: "wss://bitpw.m3.as1.app.chime.aws:443/v2/screen/9f8e3030-7d32-42d9-b425-efaee9ef2766", ScreenSharingUrl: "wss://bitpw.m3.as1.app.chime.aws:443/v2/screen/9f8e3030-7d32-42d9-b425-efaee9ef2766", ScreenViewingUrl: "wss://bitpw.m3.as1.app.chime.aws:443/ws/connect?pa…tHub-Call-Id=9f8e3030-7d32-42d9-b425-efaee9ef2766", …}MediaRegion: "ap-southeast-1"MeetingId: "9f8e3030-7d32-42d9-b425-efaee9ef2766"__proto__: Object__proto__: Objectconstructor: ƒ Object()hasOwnProperty: ƒ hasOwnProperty()isPrototypeOf: ƒ isPrototypeOf()propertyIsEnumerable: ƒ propertyIsEnumerable()toLocaleString: ƒ toLocaleString()toString: ƒ ()valueOf: ƒ valueOf()__defineGetter__: ƒ __defineGetter__()__defineSetter__: ƒ __defineSetter__()__lookupGetter__: ƒ __lookupGetter__()__lookupSetter__: ƒ __lookupSetter__()get __proto__: ƒ __proto__()set __proto__: ƒ __proto__()

meetings.service.ts:32 after createAttendee

meetings.service.ts:33 {Attendee: {…}, @metadata: {…}}@metadata: {statusCode: 201, effectiveUri: "https://chime.us-east-1.amazonaws.com/meetings/9f8e3030-7d32-42d9-b425-efaee9ef2766/attendees", headers: {…}, transferStats: {…}}Attendee: AttendeeId: "d8ac5546-33b3-ee56-32b5-cd9301920ffb"ExternalUserId: "User0"JoinToken: "ZDhhYzU1NDYtMzNiMy1lZTU2LTMyYjUtY2Q5MzAxOTIwZmZiOmUxMmE5YTFmLTI0ZGItNDYwNi1iNDAxLTQ1NWZmNDllOWE2OQ"__proto__: Object__proto__: Object

on this line: const configuration = new MeetingSessionConfiguration(this.meetingResponse, this.attendeeResponse);

core.js:6142 ERROR TypeError: Cannot read property 'toLowerCasePropertyNames' of undefined
    at toLowerCasePropertyNames (MeetingSessionConfiguration.js:157)
    at Array.map (<anonymous>)
    at MeetingSessionConfiguration.toLowerCasePropertyNames (MeetingSessionConfiguration.js:157)
    at MeetingSessionConfiguration.js:162
    at Array.reduce (<anonymous>)
    at MeetingSessionConfiguration.toLowerCasePropertyNames (MeetingSessionConfiguration.js:160)
    at MeetingSessionConfiguration.js:162
    at Array.reduce (<anonymous>)
    at MeetingSessionConfiguration.toLowerCasePropertyNames (MeetingSessionConfiguration.js:160)
    at MeetingSessionConfiguration.js:162

**Comment by ltrung** [comment] 2021-02-09 18:51
@gsudhanshu Thanks for reporting. Could you double check the json object format? From the example above, it seems the response format is not correct (lacking comma and extra curly braces). I also noticed that there were some metadata property there. Do you still have the same issue if you remove those?

**Comment by gsudhanshu** [comment] 2021-02-10 05:10
@ltrung I have server backend on laravel where I use aws-sdk-php-chimeClient for create meeting and createattendee

I am getting objects from both these calls and I am converting them to array using my object_to_array function. laravels response()->json() function converts array to json and returns it back.

I dont know why it has metadata?

my controller code:

class APIController extends Controller
{

    private function object_to_array($data)
    {
        if (is_array($data) || is_object($data))
        {
            $result = array();
            foreach ($data as $key => $value)
            {
                $result[$key] = $this->object_to_array($value);
            }
            return $result;
        }
        return $data;
    }
    
    /**
     * create a new meeting
     */
    public function createMeeting() 
    {
        $chimeClient = AWS::createClient('chime');

        $result = $chimeClient->createMeeting([
            'ClientRequestToken' => 'Meeting1', // REQUIRED
            'ExternalMeetingId' => 'Meeting1',
            'MediaRegion' => 'ap-southeast-1',
            'Tags' => [
                [
                    'Key' => 'type', // REQUIRED
                    'Value' => 'test', // REQUIRED
                ],
            ],
        ]);
        $obj = $this->object_to_array($result);
        return response()->json($obj);
    }

    /**
     * create a new attendee for given meeting id
     */
    public function createAttendee($meetingId) {
        $chimeClient = AWS::createClient('chime');

        $attendeeResult = $chimeClient->createAttendee([
            'ExternalUserId' => 'User0', // REQUIRED
            'MeetingId' => $meetingId, // REQUIRED
            'Tags' => [
                [
                    'Key' => 'type', // REQUIRED
                    'Value' => 'test', // REQUIRED
                ],
            ],
        ]);
        $obj = $this->object_to_array($attendeeResult);
        return response()->json($obj);
    }

    /**
     * Delete meeting
     */
    public function deleteMeeting($meetingId) {
        $chimeClient = AWS::createClient('chime');

        $result = $chimeClient->deleteMeeting([
            'MeetingId' => $meetingId, // REQUIRED
        ]);
        $obj = $this->object_to_array($result);
        return response()->json($obj);
    }

}

**Comment by ltrung** [comment] 2021-02-10 18:13
@gsudhanshu could you prettify the json response and copy it here?

**Comment by gsudhanshu** [comment] 2021-02-11 07:30
@ltrung 
pls find below:
createMeeting response:
{
    "Meeting": {
        "MeetingId": "6fe13920-be68-42b3-8229-0276e5b62869",
        "ExternalMeetingId": "Meeting1",
        "MediaPlacement": {
            "AudioHostUrl": "506ae4be3fa3c970db771c2174bd3fbf.k.m1.as1.app.chime.aws:3478",
            "AudioFallbackUrl": "wss://haxrp.m1.as1.app.chime.aws:443/calls/6fe13920-be68-42b3-8229-0276e5b62869",
            "ScreenDataUrl": "wss://bitpw.m1.as1.app.chime.aws:443/v2/screen/6fe13920-be68-42b3-8229-0276e5b62869",
            "ScreenSharingUrl": "wss://bitpw.m1.as1.app.chime.aws:443/v2/screen/6fe13920-be68-42b3-8229-0276e5b62869",
            "ScreenViewingUrl": "wss://bitpw.m1.as1.app.chime.aws:443/ws/connect?passcode=null&viewer_uuid=null&X-BitHub-Call-Id=6fe13920-be68-42b3-8229-0276e5b62869",
            "SignalingUrl": "wss://signal.m1.as1.app.chime.aws/control/6fe13920-be68-42b3-8229-0276e5b62869",
            "TurnControlUrl": "https://ccp.cp.ue1.app.chime.aws/v2/turn_sessions"
        },
        "MediaRegion": "ap-southeast-1"
    },
    "@metadata": {
        "statusCode": 201,
        "effectiveUri": "https://chime.us-east-1.amazonaws.com/meetings",
        "headers": {
            "x-amzn-requestid": "4c216c02-9436-46d5-b78e-04fe04a08958",
            "content-type": "application/json",
            "content-length": "850",
            "date": "Thu, 11 Feb 2021 07:28:15 GMT"
        },
        "transferStats": {
            "http": [
                []
            ]
        }
    }
}

createAttendee response:
{
    "Attendee": {
        "ExternalUserId": "User0",
        "AttendeeId": "ac121238-0bd1-cb38-a85a-a23d7da81df9",
        "JoinToken": "YWMxMjEyMzgtMGJkMS1jYjM4LWE4NWEtYTIzZDdkYTgxZGY5OjY5NmM1MGI4LTkxOTItNGZkZS05NWJiLTcxNzFlYWZkN2U4YQ"
    },
    "@metadata": {
        "statusCode": 201,
        "effectiveUri": "https://chime.us-east-1.amazonaws.com/meetings/6fe13920-be68-42b3-8229-0276e5b62869/attendees",
        "headers": {
            "x-amzn-requestid": "fc876791-3efe-4943-895f-a54496cf111a",
            "content-type": "application/json",
            "content-length": "216",
            "date": "Thu, 11 Feb 2021 07:29:55 GMT"
        },
        "transferStats": {
            "http": [
                []
            ]
        }
    }
}

**Comment by gsudhanshu** [comment] 2021-02-11 07:36
@ltrung Meanwhile, I changed my server-app from laravel to java spring using aws-java-sdk and it worked.

response when using java backend:

createMeeting:
{
    "sdkResponseMetadata": {
        "requestId": "4526be36-9347-4ca3-94c4-3afb16deae78"
    },
    "sdkHttpMetadata": {
        "httpHeaders": {
            "Content-Length": "850",
            "Content-Type": "application/json",
            "Date": "Thu, 11 Feb 2021 07:33:33 GMT",
            "x-amzn-RequestId": "4526be36-9347-4ca3-94c4-3afb16deae78"
        },
        "httpStatusCode": 201,
        "allHttpHeaders": {
            "x-amzn-RequestId": [
                "4526be36-9347-4ca3-94c4-3afb16deae78"
            ],
            "Content-Length": [
                "850"
            ],
            "Date": [
                "Thu, 11 Feb 2021 07:33:33 GMT"
            ],
            "Content-Type": [
                "application/json"
            ]
        }
    },
    "meeting": {
        "meetingId": "774e0d03-34a7-4387-abbd-30f232232b57",
        "externalMeetingId": "Meeting1",
        "mediaPlacement": {
            "audioHostUrl": "95cddcdb1f339a3ddebb3e56f8e890a5.k.m2.as1.app.chime.aws:3478",
            "audioFallbackUrl": "wss://haxrp.m2.as1.app.chime.aws:443/calls/774e0d03-34a7-4387-abbd-30f232232b57",
            "screenDataUrl": "wss://bitpw.m2.as1.app.chime.aws:443/v2/screen/774e0d03-34a7-4387-abbd-30f232232b57",
            "screenSharingUrl": "wss://bitpw.m2.as1.app.chime.aws:443/v2/screen/774e0d03-34a7-4387-abbd-30f232232b57",
            "screenViewingUrl": "wss://bitpw.m2.as1.app.chime.aws:443/ws/connect?passcode=null&viewer_uuid=null&X-BitHub-Call-Id=774e0d03-34a7-4387-abbd-30f232232b57",
            "signalingUrl": "wss://signal.m2.as1.app.chime.aws/control/774e0d03-34a7-4387-abbd-30f232232b57",
            "turnControlUrl": "https://ccp.cp.ue1.app.chime.aws/v2/turn_sessions"
        },
        "mediaRegion": "ap-southeast-1"
    }
}

createAttendee:
{
    "sdkResponseMetadata": {
        "requestId": "23444962-1403-480e-b672-234faa387cc2"
    },
    "sdkHttpMetadata": {
        "httpHeaders": {
            "Content-Length": "216",
            "Content-Type": "application/json",
            "Date": "Thu, 11 Feb 2021 07:35:48 GMT",
            "x-amzn-RequestId": "23444962-1403-480e-b672-234faa387cc2"
        },
        "httpStatusCode": 201,
        "allHttpHeaders": {
            "x-amzn-RequestId": [
                "23444962-1403-480e-b672-234faa387cc2"
            ],
            "Content-Length": [
                "216"
            ],
            "Date": [
                "Thu, 11 Feb 2021 07:35:48 GMT"
            ],
            "Content-Type": [
                "application/json"
            ]
        }
    },
    "attendee": {
        "externalUserId": "User1",
        "attendeeId": "a75985c7-0098-b297-6e08-459fb7e601a8",
        "joinToken": "YTc1OTg1YzctMDA5OC1iMjk3LTZlMDgtNDU5ZmI3ZTYwMWE4OjJlODI3ZmJiLTdiZWYtNGI0My04Yjc2LTYzMDlmZWVhZGFkZg"
    }
}

**Comment by narek-king** [comment] 2021-02-18 11:05
@gsudhanshu I had the same issue and I forked and made a slight change in the toLowerCasePropertyNames method and it worked for me. You can try to install it from https://github.com/narek-king/amazon-chime-sdk-js.git.
Let me know if it works for you.

**Comment by ltrung** [comment] 2021-02-19 21:22
@gsudhanshu Have you tried the fix that @narek-king posted?

**Comment by sanjitkung** [comment] 2021-02-20 06:03
I am getting same error as well.

**Comment by gsudhanshu** [comment] 2021-02-21 08:54
@ltrung the fix suggested by @narek-king worked for me. Thanks to both of you

**Comment by ltrung** [comment] 2021-02-22 17:14
@gsudhanshu, I tried out the createMeeting and createAttendee response that you posted but it worked for me without @narek-king fix:
```
new MeetingSessionConfiguration(
        {
          "MeetingId": "6fe13920-be68-42b3-8229-0276e5b62869",
          "ExternalMeetingId": "Meeting1",
          "MediaPlacement": {
            "AudioHostUrl": "506ae4be3fa3c970db771c2174bd3fbf.k.m1.as1.app.chime.aws:3478",
            "AudioFallbackUrl": "wss://haxrp.m1.as1.app.chime.aws:443/calls/6fe13920-be68-42b3-8229-0276e5b62869",
            "ScreenDataUrl": "wss://bitpw.m1.as1.app.chime.aws:443/v2/screen/6fe13920-be68-42b3-8229-0276e5b62869",
            "ScreenSharingUrl": "wss://bitpw.m1.as1.app.chime.aws:443/v2/screen/6fe13920-be68-42b3-8229-0276e5b62869",
            "ScreenViewingUrl": "wss://bitpw.m1.as1.app.chime.aws:443/ws/connect?passcode=null&viewer_uuid=null&X-BitHub-Call-Id=6fe13920-be68-42b3-8229-0276e5b62869",
            "SignalingUrl": "wss://signal.m1.as1.app.chime.aws/control/6fe13920-be68-42b3-8229-0276e5b62869",
            "TurnControlUrl": "https://ccp.cp.ue1.app.chime.aws/v2/turn_sessions"
          },
          "MediaRegion": "ap-southeast-1"
        },
        {
          "ExternalUserId": "User0",
          "AttendeeId": "ac121238-0bd1-cb38-a85a-a23d7da81df9",
          "JoinToken": "YWMxMjEyMzgtMGJkMS1jYjM4LWE4NWEtYTIzZDdkYTgxZGY5OjY5NmM1MGI4LTkxOTItNGZkZS05NWJiLTcxNzFlYWZkN2U4YQ"
        }
);
```

Is that how you did it?

**Comment by gsudhanshu** [comment] 2021-02-23 03:50
@ltrung I did it as follows using fix by @narek-king 

```
this.configuration = new MeetingSessionConfiguration(
              this.meetingResponse, 
              this.attendeeResponse);
```

**Comment by vidya-mohan** [comment] 2021-05-03 21:11
@gsudhanshu @narek-king thank you for the interest in the SDK. 

Could you please clarify what was the original issue that you are trying to fix and how we can reproduce it? There is an PR with active comments on it https://github.com/aws/amazon-chime-sdk-js/pull/1072 that need addressed - we would like to help you move this forward but need additional clarification

**Comment by gsudhanshu** [comment] 2021-05-14 18:44
@vidya-mohan try creating meetingSession using aws chime sdk js with meeting and attendee responses from aws-sdk-php

you will understand the need for this change

**Comment by gsudhanshu** [comment] 2021-09-05 16:30
@ltrung @vidya-mohan 
is this issue fixed in latest release of aws-chime-sdk-js?

I see @narek-king 's fixed has been reviewed [here](https://github.com/aws/amazon-chime-sdk-js/pull/1072)

**Comment by nainkunal933** [comment] 2021-09-10 01:18
Hi @gsudhanshu, thank you for opening this issue and @narek-king for opening this PR #1072 

I have looked through your code and API responses. I created a PHP application that gave me same response as you provided above. One of the things to note is that the JS SDK response for a `createAttendee` and the PHP SDK's response are a little different. PHP SDK response has this extra bit of metadata info:

```json
{
	"@metadata": {
		"statusCode": 201,
		"effectiveUri": "https://chime.us-east-1.amazonaws.com/meetings/6fe13920-be68-42b3-8229-0276e5b62869/attendees",
		"headers": {
			"x-amzn-requestid": "fc876791-3efe-4943-895f-a54496cf111a",
			"content-type": "application/json",
			"content-length": "216",
			"date": "Thu, 11 Feb 2021 07:29:55 GMT"
		},
		"transferStats": {
			"http": [
				[]
			]
		}
	}
}
```

From this metadata response, the issue happens at this http info:
```json
"http": [
[]
]
```
 When this 2d array gets to `toLowerCasePropertyNames`, the method is called recursively at this line: https://github.com/aws/amazon-chime-sdk-js/blob/master/src/meetingsession/MeetingSessionConfiguration.ts#L199

```ts
else if (Array.isArray(input)) {
      return input.map(this.toLowerCasePropertyNames);
    }
```
then the following error is thrown.
> TypeError: Cannot read properties of undefined (reading ‘toLowerCasePropertyNames’)
    at toLowerCasePropertyNames (MeetingSessionConfiguration.js:176)
    at Array.map (<anonymous>)
    at MeetingSessionConfiguration.toLowerCasePropertyNames (MeetingSessionConfiguration.js:176)
    at eval (MeetingSessionConfiguration.js:181)
    at Array.reduce (<anonymous>)
    at MeetingSessionConfiguration.toLowerCasePropertyNames (MeetingSessionConfiguration.js:179)
    at eval (MeetingSessionConfiguration.js:181)
    at Array.reduce (<anonymous>)
    at MeetingSessionConfiguration.toLowerCasePropertyNames (MeetingSessionConfiguration.js:179)
    at eval (MeetingSessionConfiguration.js:181)


When input.map is called recursively, it does not preserve the value of `this` object and `undefined` is passed into the next recursion. Please refer to [MDN docs](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/map) for further explanation on this behavior of `Array.map()` method.
![Screen Shot 2021-09-09 at 11 25 03 AM](https://user-images.githubusercontent.com/31940639/132781992-671eaae4-1ad9-4316-be7b-0a83576c86e7.png)
This is not an issue with passing empty arrays or anything like that. I initially thought that was it but on further research I don't think that's the issue.

@narek-king's fork is currently working because if you start checking for the length of the array on the code attached above you will never call `toLowerCasePropertyNames` inside the else if block and hence you will never run into the issue of loosing `this` reference due to `Array.map()`'s behavior.

Now on to the **solution** for this problem, there are two ways to fix this:
1. either we pass `this` as an optional parameter to `map()` method or 
2. we make the method **static** so usage of this is no longer required 

I will be opening a PR soon with the second fix. Also, I will be adding some unit test coverage to avoid running into similar issue from this method.

Even though my PR will be opened soon, it will take some time to get merged and then release, so an easy **mitigation strategy**  for you in the meanwhile is to filter out the metadata from PHP response. After that your application should start working with the latest version of the JS SDK.

Please let me know if you have any questions or concerns. Thank you for using Chime JS SDK.

**Comment by narek-king** [comment] 2021-09-10 10:07
@nainkunal933 Thank you for the details. I wasn't able to figure this out. I tried to set up and use the latest version of the SDK and it works. The back-end solution I used was AWS Lamda but not PHP. So now it is clear the real cause of the issue.
I think making the method static is a more reasonable solution as per the comment [here](https://github.com/aws/amazon-chime-sdk-js/pull/1072#discussion_r579714994).

**Closed** 2021-09-13 19:58 UTC
Labels: Bug, chime-setup

**Comment by nainkunal933** [comment] 2021-09-13 20:03
Hi @gsudhanshu and @narek-king,

I have merged the PR and you should be able to use the fix after the next release. The slight change from what I was saying above is that I actually did not make the method static but moved it to `Utils.ts`. Since, the this reference is no longer used you should not run into the same issue.

Thank you!!
