### ISSUE TITLE
activeId not returned from subscribeToActiveSpeakerDetector

### ISSUE THREAD

**Issue by jkelting** [aws/amazon-chime-sdk-js#924] opened 2020-12-03 09:10 UTC
I join a meeting with a couple of different attendees. For visual support of who is speaking the most active speaker has a red border around his videotile. I use the subscription "subscribeToActiveSpeakerDetector"  to get the activeId of the most acitve speaker.
After a while this subscription stops working and return null as activeId, which means my border is not shown anymore.

Start a meeting with a couple of attendees
log the id you get from "subscribeToActiveSpeakerDetector"
talk a while and check the logs
After some time the tileId is returned as null, even though someone is talking

Expected behavior
The subscription should always return the activeId of the activee speaker

Version currently in use:
"amazon-chime-sdk-js: "1.17.2",

**Comment by bradmanAWS** [comment] 2020-12-03 17:46
Hi @jkelting could you please provide the client logs when this error occurs for our investigation?

**Comment by jkelting** [comment] 2020-12-03 18:08
Hey, thanks for your quick reply. What kind of logs do you mean? What should be logged? Where can I find them?
If you are talking about my steps how to reproduce the behavoir, then those logs dont show that much. At some point the activeId is always null. This happens not for everyone in the meeting and if they reload it is fine again.

**Comment by bradmanAWS** [comment] 2020-12-03 18:47
You can set your log level to info as shown in the readme here: https://github.com/aws/amazon-chime-sdk-js#meeting-session and then view and save them from the browser console.

**Comment by jkelting** [comment] 2020-12-03 18:53
Alright I will set this up and provide the results when I get them. Since this doenst happen all the time it might take a little while.

**Comment by jkelting** [comment] 2020-12-03 19:39
[bug-logs-1.txt](https://github.com/aws/amazon-chime-sdk-js/files/5638536/bug-logs-1.txt)
[bug-logs-2.txt](https://github.com/aws/amazon-chime-sdk-js/files/5638537/bug-logs-2.txt)

Those are the logs from two different browsers (both chrome) of two attendees in the same meeting. In the beginning the active speaker indicator worked fine. Both logs contain only the time when the active speaker indicator was not working anymore.
Is this helpful?

**Comment by bradmanAWS** [comment] 2020-12-03 21:32
Hi @jkelting can you please include the complete logs as requested in the issues template? I don't think these logs include the information we need. And as I can't reproduce this error on my end, I'm not sure how what else we can do to resolve this. Can you also join a meeting in our demo application in this repo https://github.com/aws/amazon-chime-sdk-component-library-react and see if you can reproduce the issue there? If not, perhaps there is some implementation that is causing this issue.

**Comment by jkelting** [comment] 2020-12-08 20:48
Hey @bradmanAWS I have two differnet projects and it is failing in both at times. The newer one is using the demo as a basis. I did not really write any code myself.

**Comment by jkelting** [comment] 2020-12-08 21:40
Coming to think of it. In my first and little bit older project I have never experienced this error until recently. It started when I changed that attendees who had no videotile could still talk in the meeting. Before that change it was only possible to talk when you had a videotile. I hope this helps you to find the possible bug.

**Comment by jkelting** [comment] 2020-12-15 10:33
Hey @bradmanAWS is there any progress on the issue? Could you recreate the bug?

**Comment by bradmanAWS** [comment] 2020-12-18 21:47
Hi @jkelting we have found an issue related to this: https://github.com/aws/amazon-chime-sdk-js/issues/673 and we are investigating the issue. We'll update when we have a solution.

**Comment by jkelting** [comment] 2021-01-12 09:39
Hey @bradmanAWS  Is there any progress? And when will you push a new version to npm?
Best regards

**Comment by bradmanAWS** [comment] 2021-01-12 18:07
@jkelting Yes, the fix is in place and we are working to release soon.

**Comment by jkelting** [comment] 2021-01-12 21:14
Nice :) Thanks for the reply

**Comment by bradmanAWS** [comment] 2021-01-12 23:02
@jkelting This fix was released in 2.4. Can you upgrade and reopen this issue if you are still experiencing this issue (after updating your code). Thanks.

**Closed by bradmanAWS** 2021-01-12 23:02 UTC
Labels: Bug, Triaged
