### ISSUE TITLE
Pause/Unpause content share 

### ISSUE THREAD

**Issue by colin-shah** [aws/amazon-chime-sdk-js#1080] opened 2021-02-22 09:34 UTC
**Describe the bug**
we have implemented pause/Unpause option for content share, but while doing pause  It playing continues in the background just showing blank video tile on other attendee ends but still voice is present and also it continues playing. I have attached screen-cast for reference. and info log too

**Screenshots**
https://share.vidyard.com/watch/y2ECcn7K2C2fn2cTJ4bfsX?

Meeting ID: a6619edc-f886-4573-b8e0-17b6df945b17
Attendee ID: ec71c0a0-6fd1-d4f7-5df7-6d82bfe3e149

**Platform**
 OS: Windows
 Browser: Chrome, Firefox
 Browser Version: For chrome 86.0.4242.111
 Amazon Chime SDK: 2.2.1

**Log**
2021-02-22T09:32:01.737Z [INFO] SDK - local clock skew estimate=24ms from ping-pong time=216ms
ConsoleLogger.js:68 2021-02-22T09:32:02.784Z [INFO] SDK - API/DefaultAudioVideoFacade/a6619edc-f886-4573-b8e0-17b6df945b17/ec71c0a0-6fd1-d4f7-5df7-6d82bfe3e149/pauseContentShare
meetingV2.ts:1808 [DEMO] content share paused.
ConsoleLogger.js:68 2021-02-22T09:32:06.277Z [INFO] SDK - local clock skew estimate=29ms from ping-pong time=203ms
ConsoleLogger.js:68 2021-02-22T09:32:09.300Z [INFO] SDK - API/DefaultAudioVideoFacade/a6619edc-f886-4573-b8e0-17b6df945b17/ec71c0a0-6fd1-d4f7-5df7-6d82bfe3e149/unpauseContentShare
meetingV2.ts:1808 [DEMO] content share unpaused.
ConsoleLogger.js:68 2021-02-22T09:32:11.740Z [INFO] SDK - local clock skew estimate=26ms from ping-pong time=221ms
ConsoleLogger.js:68 2021-02-22T09:32:16.277Z [INFO] SDK - local clock skew estimate=29ms from ping-pong time=203ms
ConsoleLogger.js:68 2021-02-22T09:32:17.478Z [INFO] SDK - API/DefaultAudioVideoFacade/a6619edc-f886-4573-b8e0-17b6df945b17/ec71c0a0-6fd1-d4f7-5df7-6d82bfe3e149/pauseContentShare
meetingV2.ts:1808 [DEMO] content share paused.
ConsoleLogger.js:68 2021-02-22T09:32:20.089Z [INFO] SDK - API/DefaultAudioVideoFacade/a6619edc-f886-4573-b8e0-17b6df945b17/ec71c0a0-6fd1-d4f7-5df7-6d82bfe3e149/unpauseContentShare
meetingV2.ts:1808 [DEMO] content share unpaused.
ConsoleLogger.js:68 2021-02-22T09:32:21.727Z [INFO] SDK - local clock skew estimate=20ms from ping-pong time=208ms
ConsoleLogger.js:68 2021-02-22T09:32:26.275Z [INFO] SDK - local clock skew estimate=28ms from ping-pong time=201ms

**Comment by ltrung** [comment] 2021-02-22 17:49
@colin-shah Thanks for reporting. I could reproduce bug in our meeting demo as well. This is because we did not pause the video element that plays the shared video when content share is paused. This should be fixed in PR #1081. Please let me know if it works for you.

**Closed** 2021-03-22 16:53 UTC
Labels: Minor Issue
