### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by tahamazari** [aws/amazon-chime-sdk-js#879] opened 2020-11-19 07:47 UTC
**Describe the bug**
I'm trying to login with the same user in a meeting, two or three times without logging out or stopping meeting. The server then replies with {"message": "Internal server error"}.

**Screenshots**
https://pbs.twimg.com/media/EnK60aFXUAM35og?format=jpg&name=medium

**Platform**
 - OS: Windows
 - Browser:  Chrome

**Comment by tahamazari** [comment] 2020-11-19 07:47
please help i am currently in testing phase.

**Comment by RidipDe** [comment] 2020-11-25 19:12
Were you connected over VPN when you saw this error ?
Is it reproducible on the demo app - if so can you please provide the steps ?

**Comment by tahamazari** [comment] 2020-11-26 14:32
I'll explain the steps.

1. You login in room Test1 and with User1
2. Works fine
3. Stop Meeting
4. Then you login again we get Internal Server Error.

Maybe the meeting was not quit properly? You could do the same on Postman, provide the room name and user name in body.
Post it a few times and you get the internal server error

**Comment by p-foucht** [comment] 2020-12-29 00:11
If this was using the demo app/server, I believe this is caused by the auto-end policy of chime meetings - [docs here](https://docs.aws.amazon.com/chime/latest/dg/mtgs-sdk-mtgs.html).

A meeting will be deleted in the case where "no audio connections are present in the meeting for more than five minutes." I don't believe the demo server takes this into account and throws errors when trying to join a deleted meeting.

**Comment by ltrung** [comment] 2020-12-29 01:35
It seems like in this case, the API Gateway encounters a 502 which is not from Chime JS SDK. Could you turn on CloudWatch logging for API Gateway and see what cause the issue?

**Comment by hansemannn** [comment] 2021-01-31 20:54
This is a very serious error when handling multiple fast-recurring connections. It can be reproduced by re-using the same `Name` parameter in the demo, e.g.:
```
/Prod/join?title=123&name=Test&region=eu-central-1
```

The microservice should catch up again and recreate the meeting.

**Comment by ahmet-tas** [comment] 2021-01-31 21:03
Once you end the meeting you cannot use the same meeting name again in the demo environment.

This happens because, in the demo the meeting names are cached in memory. Once you stop and restart the demo app, you can reuse it.

This won't happen if you deploy the demo app on AWS, cause meeting names are kept in DynamoDB

**Comment by ltrung** [comment] 2021-04-23 00:36
@hansemannn @tahamazari Do you guys have the requestId of the API calls that returns Internal Server Error?

**Comment by hansemannn** [comment] 2021-04-23 06:26
@ltrung For us we fixed it by generating new meeting IDs every time a new meeting is started (instead of a static room id)

**Comment by ltrung** [comment] 2021-04-26 17:28
Thanks. I will close the issue for now but feel free to open a new issue

**Closed by ltrung** 2021-04-26 17:28 UTC
Labels: Needs More Information
