### ISSUE TITLE
When Share a uploaded video through startContentShare method it is show GREEN screen to remote participants.

### ISSUE THREAD

**Issue by mkmuduli** [aws/amazon-chime-sdk-js#1487] opened 2021-08-04 10:57 UTC
### What happened and what did you expect to happen?

when a user share a uploaded video by below code . it is showing green to remote participants.
Currently i am using chime demo application. it is happening there.

`let videoStream = video.captureStream();`
`await meetingManager.audioVideo.startContentShare(videoStream);`

Screen Share Participants Side
<img width="240" alt="Screenshot 2021-08-04 at 4 14 20 PM" src="https://user-images.githubusercontent.com/16792091/128169400-39b47ce5-b172-46bb-8ac4-d1af5a6973cf.png">

Remote Participants Side
<img width="240" alt="Screenshot 2021-08-04 at 4 14 23 PM" src="https://user-images.githubusercontent.com/16792091/128169231-bf120c84-debe-4d91-9a52-5e5f6d3d8095.png">

Uploaded video visible properly on uploader participants. but **Green** screen is showing on remote participants side.

Please help me we need feature urgently, Thanks.

### Have you reviewed our existing documentation?

- [X] GitHub [issues](https://github.com/aws/amazon-chime-sdk-js/issues)
- [X] FAQs [page](https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html)
- [X] README [page](https://github.com/aws/amazon-chime-sdk-js#amazon-chime-sdk-for-javascript)
- [X] Feature-specific [guides](https://github.com/aws/amazon-chime-sdk-js#guides)

### Reproduction steps

Share a uploaded video by share screen dropdown

### Amazon Chime SDK for JavaScript version

2.14.0 and 2.4.1

### What browsers are you seeing the problem on?

Chrome

### Browser version

latest 92 +

### Browser console logs

nothing

**Comment by devalevenkatesh** [comment] 2021-08-04 19:56
I could not reproduce this issue on my machine.

System Information:
macOs Catalina v10.15.7
Google Chrome 92.0.4515.107 (Official Build) (x86_64)

Here is the screen recording:

https://user-images.githubusercontent.com/61809205/128243908-81597ae3-5630-498b-95e4-d69e568f176c.mov

Would like to know some more information below:
1. Are you using the Chime JS SDK demo as is or it is your own app?
2. If not, could you please try to check these lines to see if you are missing any step / function call:
- Check whether you are catching any errors like we do [here](https://webrtc.github.io/samples/src/content/capture/video-pc/).
- Check the `playToStream` function which returns the media stream [here](https://github.com/aws/amazon-chime-sdk-js/blob/b77ec7e210aba3803a842ced62158c882dda883f/demos/browser/app/meetingV2/meetingV2.ts#L2912-L2922).
3. Turn off Chrome's hardware acceleration and check if this solves the issue:
https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html#when-i-stream-video-in-chrome-other-attendees-see-a-black-screen-is-this-a-known-issue
4. Request you to please try to reproduce this on an official WebRTC samples demo to rule-out if this is specific to your device:
https://webrtc.github.io/samples/src/content/capture/video-pc/

**Comment by vidya-mohan** [comment] 2021-08-20 22:39
Resolving as couldnt proceed

**Closed by vidya-mohan** 2021-08-20 22:39 UTC
Labels: Needs More Information
