### ISSUE TITLE
Chime Recording file error- when the mp4 is played ,it's displaying white screen and no audio content 

### ISSUE THREAD

**Issue by sidharth-sid** [aws/amazon-chime-sdk-js#579] opened 2020-07-22 10:37 UTC
I have set up the chime Video call demo App and the recording demo app in AWS.
Followed the steps in :
https://aws.amazon.com/blogs/business-productivity/how-to-enable-client-side-recording-using-the-amazon-chime-sdk/
https://github.com/aws-samples/amazon-chime-sdk-recording-demo

The resources got deployed success. We were able to see the video call app hosted and was able to make the meeting.
We also wanted the recording functionality but it doesn't seem to work as expected.
Invoked start and stop of recording using the API gateway API and the API seems to work fine by seeing the response.
**The file is also generated in the S3 bucket at the end of the recording. But the mp4 file when played does not work. Tried to download in local and play in different players like VLC, media player, etc (even after updating them )** 

The duration of the file seems to the same as the recording time (Start and stop recording invocation). But the file plays a white screen with no audio or screen share capture shown.

The AWS Support team seems not able to identify the issue.  Did someone encountered similar problems??
And what might be the probable thing I'm are missing ??

@vidya-mohan @aburnson

**Comment by anuranduttaroy** [comment] 2020-07-24 01:11
Hey @sidharth-sid I tried to reproduce this issue on my personal aws-account and I could see the recording properly with audio, video & screenshare. 

Some of the things to make sure we are doing correctly.
1. Making sure the meeting URL is correct and confirm the `<<Meeting Recorder>>` user shows up in the roster.
2. While passing the meeting URL as a param from API Gateway, we need to make sure the URL is `URL encoded` as given in [Start the meeting recording](https://github.com/aws-samples/amazon-chime-sdk-recording-demo#start-the-meeting-recording) section of the README. 

If it still does not work, you might have to check for any error messages in the ECS task logs. For accessing the logs, 
1. Sign into your AWS account and go to the AWS ECS cluster page (e.g https://us-east-1.console.aws.amazon.com/ecs/home?region=us-east-1#/clusters), 
2. Click on the Cluster name (Default name: RecordingDemoEC2Cluster)
3. Click on the task which was running the recording. Note: It might be under the "Stopped" tasks too.
4. There would be a "Logs" tab on the top. 

You can attach the logs here in the issue and I can take a look to see if there is any issues.

**Comment by HbZh** [comment] 2020-07-31 09:56
Hi @anuranduttaroy,

I met the same issue. 

The demo setup successfully and the start/stop api works fine as I can see the uploaded mp4 file in my bucket. 
However, the recorded video is just white screen lasting for a while. 

I follow your info to check the log of my ECS task: 
`[recording process] exited with code SIGTERM and signal 15(SIGTERM)
  (firefox:62): LIBDBUSMENU-GLIB-WARNING **: 09:46:21.798: Unable to get session bus: Failed to execute child process ?dbus-launch? (No such file or directory)
[upload process] constructed a S3 object with bucket: xxxxxxxxx, key: xxxxxxx.mp4`

Can you offer help, thanks.

**Comment by anuranduttaroy** [comment] 2020-07-31 16:37
I just worked on an identical issue today and the root cause for that issue was that the meeting URL which was being passed on to the meeting recorder was incorrect. If you see the screenshot below, the URL highlighted in the red box needs to be encoded and passed on to the meeting recorder. 

![image](https://user-images.githubusercontent.com/4708896/89056323-b2beaf00-d310-11ea-9185-2fb2c8a80147.png)

**Example:** If the meeting URL is `https://abcdefghij.execute-api.us-east-1.amazonaws.com/Prod/v2?m=MyMeetingTest`, then the encoded URL which needs to be passed to the meeting recorder should look like `https%3A%2F%2Fabcdefghij.execute-api.us-east-1.amazonaws.com%2FProd%2Fv2%3Fm%3DMyMeetingTest`

Can you confirm that is what you are doing?

Also, it would be helpful to get the entire ECS logs to see what URL you are exactly passing to the meeting recorder.

**Comment by HbZh** [comment] 2020-08-01 03:03
@anuranduttaroy  it was the meeting URL issue. It is fixed now. Thanks!

**Comment by anuranduttaroy** [comment] 2020-08-01 04:23
@sidharth-sid can you confirm the solution mentioned in https://github.com/aws/amazon-chime-sdk-js/issues/579#issuecomment-667218127 works for you?

Feel free to re-open the issue if you still see the issue happening and I would be happy to help.

**Closed by anuranduttaroy** 2020-08-01 04:23 UTC

**Comment by sidharth-sid** [comment] 2020-08-03 05:12
Thanks, @anuranduttaroy
 I also had the issue with the meeting URL used for invoking recording
