### ISSUE TITLE
Video Not Displaying in Chromium Browser on Linux

### ISSUE THREAD

**Issue by troyready** [aws/amazon-chime-sdk-js#1074] opened 2021-02-18 18:47 UTC
Webapp is working properly when used in Google Chrome. When launched under [Chromium](https://packages.debian.org/buster/chromium) however, a "Update your client to support recent video improvements" message is displayed in place of other participants video streams.

I've confirmed that it isn't a codec issue in the browser ([h264/aac videos](http://demo.nimius.net/video_test/) playback properly), so I assume it's a quirk of the current chromeLike browser detection or a similar issue.

**Screenshots**
![image](https://user-images.githubusercontent.com/1806418/108405294-c6aaff00-71d5-11eb-8fad-525d395352fe.png)

**Platform**
 - OS: Debian 10
 - Browser: Chromium
 - Browser Version: 88.0.4324.146

**Comment by devalevenkatesh** [comment] 2021-02-18 20:42
Can you please let us know if you are using Amazon Chime JS SDK (version ?) or the Amazon Chime app? From the pic, it looks like the Amazon Chime app.

**Comment by troyready** [comment] 2021-02-18 22:19
You're right, I'm seeing this in the [webclient](https://webclient.app.chime.aws/) -- based on previously reported issues I assume it's inheriting the problem from here (but could be 100% mistaken in that)

**Comment by devalevenkatesh** [comment] 2021-02-19 00:11
Ok, thanks. Since it looks like the issue is with the Amazon Chime App and not with the JS SDK, request you to open a AWS support ticket for Amazon Chime or you can ask questions at https://answers.chime.aws/.

Hope this helps. Please feel free to report any issues related to Amazon Chime JS SDK here. Closing this issue now.

**Closed by devalevenkatesh** 2021-02-19 00:11 UTC
Labels: Needs More Information
