### ISSUE TITLE
Meeting not adhering to the upstream sending bandwidth established 

### ISSUE THREAD

**Issue by AleKiller21** [aws/amazon-chime-sdk-js#2248] opened 2022-05-22 08:51 UTC
Hi,

I'm currently working on an Electron app that uses the Chime SDK to initiate and record a **single attendee** meeting. I recently opened another issue which you can find here https://github.com/aws/amazon-chime-sdk-js/issues/2247 in case you wish to get a little more context.

I'm interested in monitoring the attendee's uplink to determine whether the upload is good enough to produce a smooth high-quality recording. For this, I'm monitoring the `videoUpstreamBitrate` obtained from the `clientMetricReport` retrieved from the `metricsDidReceive` event. I'm basing myself on this section of the [Chime docs](https://aws.github.io/amazon-chime-sdk-js/modules/qualitybandwidth_connectivity.html#events-for-monitoring-local-attendee-downlink) to build this monitoring tool.

I'm using the `chooseVideoInputQuality` function to specify what the max bitrate upper limit will be. After doing some tests with different values being sent in the fourth argument of the function, the `maxBandwidthKbps` parameter, I can confirm that the SDK is obeying the upper limit bitrate that I'm specifying. Whenever I type the following: ```meetingSession.audioVideo.chooseVideoInputQuality(1280, 720, 30, 100);```, the application doesn't go beyond 100 Kbps of bitrate. I know this because I'm logging into the console the `videoUpstreamBitrate` from the `metricsDidReceive` event.

However, even though the logs say that the `videoUpstreamBitrate` is below 100 kbps, after reviewing the generated recording of the meeting, I noticed that this one went pretty smooth and not as pixelated as I thought it would go with only 100 kbps of bitrate.

I called once again the ```meetingSession.audioVideo.chooseVideoInputQuality(1280, 720, 30, 2500);```, but this time with a higher bitrate limit as you can see in the call of the function. The reported bitrate was indeed 2500 kbps, and the resulting recording looked just the same way as the previous one, the one where the bitrate limit was 100 kbps. I find this a little weird, especially since both meetings had a different upper limit for the upstream sending bandwidth.

I did another test, still sticking to the 2500 kbps, but this time I decided to throttle the upload bandwidth of the Electron app running the meeting. After doing this, I noticed that the reported bitrate started falling down as to be expected because of the throttling. While reviewing the resulting recording of the meeting, this time the video did look pixelated and blurry because of the low bitrate.

I'm a little confused regarding why the recording of the first meeting, which had a low uplink limit established through the ```chooseVideoInputQuality``` function, was looking fine even though the recording of the last test, which suffered from throttling and therefore had a low bitrate as well, was looking bad. Is this the expected behavior regarding the `videoUpstreamBitrate` and `chooseVideoInputQuality` function?

Thanks

**Chime SDK Version**
2.30.0

**Comment by ltrung** [comment] 2022-05-23 16:08
Closing this as it seems to be a duplicate of #2247

**Closed by ltrung** 2022-05-23 16:08 UTC
