### ISSUE TITLE
TypeError: Cannot read properties of null (reading 'removeObserver')

### ISSUE THREAD

**Issue by ildar-shamilov-clearscale** [aws/amazon-chime-sdk-js#2265] opened 2022-06-01 09:02 UTC
### What happened and what did you expect to happen?

After migrating to v3 from v2.

Calling AudioVideoFacade.stop() sometimes throws exception:

LoggerService.ts:89 TypeError: Cannot read properties of null (reading 'removeObserver')
    at DefaultAudioVideoController.uninstallPreStartObserver (DefaultAudioVideoController.js:210:1)
    at DefaultAudioVideoController.<anonymous> (DefaultAudioVideoController.js:221:1)
    at Generator.next (<anonymous>)
    at DefaultAudioVideoController.js:10:1
    at new Promise (<anonymous>)
    at push.../node_modules/amazon-chime-sdk-js/build/audiovideocontroller/DefaultAudioVideoController.js.__awaiter (DefaultAudioVideoController.js:6:1)
    at handleClosed (DefaultAudioVideoController.js:218:1)
    at Object.handleSignalingClientEvent (DefaultAudioVideoController.js:226:1)
    at DefaultSignalingClient.sendEvent (DefaultSignalingClient.js:291:1)
    at DefaultSignalingClient.closeEventHandler (DefaultSignalingClient.js:23:1)

### Have you reviewed our existing documentation?

- [X] GitHub [issues](https://github.com/aws/amazon-chime-sdk-js/issues)
- [X] FAQs [page](https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html)
- [X] README [page](https://github.com/aws/amazon-chime-sdk-js#amazon-chime-sdk-for-javascript)
- [X] Feature-specific [guides](https://github.com/aws/amazon-chime-sdk-js#guides)

### Reproduction steps

Calling AudioVideoFacade.stop() 

### Amazon Chime SDK for JavaScript version

3.2.0

### What browsers are you seeing the problem on?

Chrome latest

### Browser version

Chrome latest

### Browser console logs

LoggerService.ts:89 TypeError: Cannot read properties of null (reading 'removeObserver')
    at DefaultAudioVideoController.uninstallPreStartObserver (DefaultAudioVideoController.js:210:1)
    at DefaultAudioVideoController.<anonymous> (DefaultAudioVideoController.js:221:1)
    at Generator.next (<anonymous>)
    at DefaultAudioVideoController.js:10:1
    at new Promise (<anonymous>)
    at push.../node_modules/amazon-chime-sdk-js/build/audiovideocontroller/DefaultAudioVideoController.js.__awaiter (DefaultAudioVideoController.js:6:1)
    at handleClosed (DefaultAudioVideoController.js:218:1)
    at Object.handleSignalingClientEvent (DefaultAudioVideoController.js:226:1)
    at DefaultSignalingClient.sendEvent (DefaultSignalingClient.js:291:1)
    at DefaultSignalingClient.closeEventHandler (DefaultSignalingClient.js:23:1)

**Comment by xuesichao** [comment] 2022-06-01 22:42
Hi @ildar-shamilov-clearscale , thanks for reporting this issue.

It seems this issue happens because the `signalingClient` is `null`. JS SDK initialize a `signalingClient` instance when calling `AudioVIdeoFacade.start()` or reconnecting. The `signalingClient` is set to only when re-connection failed and disconnected.

Could you please provide us more details for your use cases, and how you encounter this issue.
If you can find a stable way to reproduce this issue, that would help us a lot.

**Comment by ildar-shamilov-clearscale** [comment] 2022-06-02 05:38
Probably when i am calling .stop() before .start()

**Comment by devalevenkatesh** [comment] 2022-06-14 16:39
@ildar-shamilov-clearscale could you please provide browser console logs for this issue? I tried calling `.stop()` before `.start()` but did not ran into any such issue. Seems like the `meetingSessionContext.signalingClient` is not valid in `uninstallPreStartObserver` [here](https://github.com/aws/amazon-chime-sdk-js/blob/main/src/audiovideocontroller/DefaultAudioVideoController.ts#L295). I suspect if these two lines race sometime.
https://github.com/aws/amazon-chime-sdk-js/blob/main/src/audiovideocontroller/DefaultAudioVideoController.ts#L737-L738

The `uninstallPreStartObserver` is called when the signaling client received a `close` event. Thus it might be happening that the `signalingClient.closeConnection` triggers the event but the `signalingClient` is nullified in above two lines. 

Created a PR to fix the error. But I think we need console logs to root cause.

**Comment by devalevenkatesh** [comment] 2022-06-20 20:26
Closing this issue as we have merged the PR with a fix. Please let me know if you have more issues.

**Closed by devalevenkatesh** 2022-06-20 20:26 UTC
Labels: Needs More Information
