### ISSUE TITLE
Screen sharing stops on Safari if mute/unmute using headphones

### ISSUE THREAD

**Issue by anatolii-globalid** [aws/amazon-chime-sdk-js#1613] opened 2021-09-22 10:59 UTC
### What happened and what did you expect to happen?

When on call, Screen sharing stops (screen share becomes black also video fade out ) if you press mute/unmute on your headphones (standard apple headphones, or other) - Mac / Safari. 
Another case is when the Siri voice command opened and at the same time screen sharing become frozen

### Reproduction steps

1. Start audio / video call with a first user
2. Have the second user screen share and activate camera
3. Press the mute button on the headphones
4. The screen sharing or/and the second user camera freezes, if pressed multiple times the screens can go black as well

### Amazon Chime SDK for JavaScript version

2.17.0

### What browsers are you seeing the problem on?

Safari

### Browser version

14.1.2

### Browser console logs

-

**Comment by xuesichao** [comment] 2021-09-27 17:40
Hi @anatolii-globalid , thank you for bringing this up, could you please tell us that after pressing the mute button on the headphones, is user get disconnected from the meeting? And if you unmute yourself using headphone button, could it go back to normal after a few time (around 30s)?
Feel like the issue is that user get disconnected due to no audio signal when user uses headphone button to mute. If that the case, user should be able to reconnect to the meeting after being unmute.

Could you please give us more information?

**Comment by anatolii-globalid** [comment] 2021-09-29 10:17
I’ve been able to replicate this share screen freeze a couple of times, however the steps do not work for me every time. Note that I haven’t been using any specific apple headphones, but was able to do it with my old Samsung wired earphones.

The problem seems to be connected with Siri voice command which opens up when I press the mute/unmute (or play/pause) button on the earphones and at the same time the screen sharing freezes. I was able to repeat this by launching Siri manually with a mouse click instead of earphones button and it caused the same issue a few times.

**Comment by xuesichao** [comment] 2021-09-29 18:39
@anatolii-globalid Thanks for you clarification, I am able to reproduce this issue by joining a meeting and then launch Siri.

#### Reproduce Step
1. User A joins the meeting via Mac
2. User B joins the meeting via iPhone Safari
3. Both users open the Camera
4. User B holds the battery button to launch Siri
5. User B's all video tiles (remote and local) freeze (go blank) immediately, there's a orange dot in the User B's roster list indicates a bad connection, and User B can not input any audio stream. While everything on User A's side is correct, but User A can not hear any audio stream from User B, and there's a orange dot in User B's roster list
    * If User B keeps Siri for around 30s, User B drops the meeting
6. User B close Siri
7. Bad connection is gone/ User B reconnects to the meeting, but all video tiles are still blank on User B's side.
    * video tiles can be recovered by reopen User B's camera (local) and User A's camera (remote)

For audio issue, SDK uses an audio input signal to notify the Chime server that the current attendee has joined a meeting. Seems launching Siri cuts off the audio signal of all other apps except itself, causing User B a bad connection/drops the meeting. I don't think we can do to much here. But user B reconnects to the meeting after closing the Siri, it looks good to me.

For video tiles, they should be recovered after reconnection. @devalevenkatesh @michhyun1 Could you please check this?

**Comment by devalevenkatesh** [comment] 2021-09-29 20:39
Thanks @xuesichao for the repro steps. I could reproduce this using the JS SDK meeting demo. But, this looks like a general behavior with WebRTC related apps.

I tested on below WebRTC official github sample and could repro the same behavior for video feed:
- https://webrtc.github.io/samples/src/content/devices/input-output/

This is also irrespective of browsers I think. I used iOS Chrome (94.0.4606.52) and Desktop Chrome (94.0.4606.61) and see once you start the Siri, your video go black not frozen. Same when the remote attendee screen shares, the screen share on the iOS Chrome side would go black and come back again once Siri is turned off.

Can you can also try doing the steps in this demo as well?
https://webrtc.github.io/samples/src/content/getusermedia/getdisplaymedia/

For some reason, I cannot enable my Siri on the laptop but when tried on the phones (Safari iOS 14 as well as iOS Chrome) the `getDisplayMedia` is not supported hence cannot confirm.

**Comment by anatolii-globalid** [comment] 2021-10-01 15:01
Hi @devalevenkatesh. Thanks for reply. 
1. There was no issues on WebRTC demo
2. In my case frozen means a snapshot of screen (user A browser Safari) without any reflection of shared screen (user B Chrome). Though one of my collages managed to reproduce the same behaviour you described (black screen), it happens occasionally and hard to reproduce.  
3. Yes, and that is literally a frozen screen after Siri is called as described in point 2.

**Comment by devalevenkatesh** [comment] 2021-12-30 01:43
Sorry for the delay this seems to me like a problematic behavior when Siri gets enabled. Though in my testing I found that the SDK worked fine when Siri is disabled. If Siri or even an external call comes in then this seems to happen and as soon as it is done the SDK works as expected. Since, the audio attendee join is audio signal driven, if the Siri enabling or call goes on for more seconds > 15 then SDK thinks it needs to re-connect as it finds there is audio signal loss. If the reconnection attempts go on for more than 2 mins there wont be any successful connection and the meeting session will fail.

You can customize this behavior for reconnection based on below FAQ:
- https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html#when-does-the-amazon-chime-sdk-retry-the-connection-can-i-customize-this-retry-behavior
- https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html#what-is-the-timeout-for-connect-and-reconnect-and-where-can-i-configure-the-value

Since, there is not much SDK can do here closing the issue, please feel free to re-open if you find this to be still an issue only on the apps using Amazon Chime SDK for JavaScript or if I am missing some testing steps.

**Closed by devalevenkatesh** 2021-12-30 01:43 UTC
