### ISSUE TITLE
Browser crashes on camera switch in Chime SDK v3.3.0

### ISSUE THREAD

**Issue by tapaskdhar** [aws/amazon-chime-sdk-js#2273] opened 2022-06-03 14:54 UTC
### What happened and what did you expect to happen?

After migrating to V3 from V2,

We observed that while switching the device the browser is getting crashed and We are not able to get any logs to debug the issue.

Note: Camera switch works fine in Chime SDK v2.26

### Have you reviewed our existing documentation?

- [X] GitHub [issues](https://github.com/aws/amazon-chime-sdk-js/issues)
- [X] FAQs [page](https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html)
- [X] README [page](https://github.com/aws/amazon-chime-sdk-js#amazon-chime-sdk-for-javascript)
- [X] Feature-specific [guides](https://github.com/aws/amazon-chime-sdk-js#guides)

### Reproduction steps

step 1. have two attendees join the meeting (attendee A and attendee B)
step 2. attendee A starts sharing the screen.
step 3. attendee B tries to switch the camera device.

after this, the browser of attendee B gets crashed.

### Amazon Chime SDK for JavaScript version

3.3.0

### What browsers are you seeing the problem on?

chrome, firefox , safari

### Browser version

Version 102.0.5005.63

### Browser console logs

no logs are available as the browser is getting crashed

**Comment by xuesichao** [comment] 2022-06-03 19:34
Hi @tapaskdhar , thanks for reporting this issue. I was not able to reproduce it using our [browser demo](https://github.com/aws/amazon-chime-sdk-js/tree/main/demos/browser). Could you please try to reproduce it using this browser demo and see if you can reproduce it successfully?

My repro steps are:
1. attendee 1 joins the meeting via Chrome
2. attendee 2 joins the meeting via Chrome
3. attendee 1 starts content sharing
4. attendee 2 enables camera
5. attendee 2 switches the camera
6. attendee 2 switches the camera back

I'm testing on macOS Monterey (12.3.1) with Chrome Version 102.0.5005.61 (Official Build) (x86_64). I switched the camera device between MacBook built-in camera and an external USB camera.

Please let me know if any of these steps are wrong.

**Comment by devalevenkatesh** [comment] 2022-06-10 23:41
@tapaskdhar We could not reproduce this issue so could you please let us know if this is still an issue on you facing? As suggested by Sichao, request to check the browser demo if you need help.

**Comment by devalevenkatesh** [comment] 2022-06-20 20:29
Closing this issue due to no-acitivity, please feel free to open this or a new issue if need be. Thank you for interest in Amazon Chime SDK for JavaScript library.

**Closed by devalevenkatesh** 2022-06-20 20:29 UTC
Labels: Needs More Information
