### ISSUE TITLE
Video play/stop buttons are displayed on IOS

### ISSUE THREAD

**Issue by ducpv-1644** [aws/amazon-chime-sdk-js#2685] opened 2023-06-20 07:48 UTC
### What happened and what did you expect to happen?

Both the self-preview video and the opponent's video show the play/pause button, and both sides can play/pause
**Device:** iPhone 7 Plus - IOS 15.5

![2023-06-20_14-27](https://github.com/aws/amazon-chime-sdk-js/assets/48663821/9131c1d3-6de3-43a5-8773-bda556a4039e)

How to hide that play/stop button?

### Have you reviewed our existing documentation?

- [X] GitHub [issues](https://github.com/aws/amazon-chime-sdk-js/issues)
- [X] FAQs [page](https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html)
- [X] README [page](https://github.com/aws/amazon-chime-sdk-js#amazon-chime-sdk-for-javascript)
- [X] Feature-specific [guides](https://github.com/aws/amazon-chime-sdk-js#guides)

### Reproduction steps

1. Create a Chime meeting
2. Join as an attendee at the meeting
Expected result: **Not** display button play/stop video on self-preview video and the opponent's video
Actual result: Display button play/stop video on self-preview video and the opponent's video

### Amazon Chime SDK for JavaScript version

3.10.0

### What browsers are you seeing the problem on?

Safari

### Browser version

15.5

### Browser console logs

I don't know how to see the logs when opening with my phone.

**Comment by xuesichao** [comment] 2023-06-20 22:24
Hi @ducpv-1644 I am unable to replicate this issue. My guess is that this issue might be related to the attributes of your <video> element. Could you share a code snippet containing that element? It could also because that iOS 15.5 might have its own logic to render those default controls.

1. Could try to reproduce the issue using the WebRTC sample provided here: https://webrtc.github.io/samples/src/content/getusermedia/gum/?
2. Additionally, could you try reproducing the issue using our browser demo available at this location: [browser demo](https://github.com/aws/amazon-chime-sdk-js/tree/main/demos/browser)?

**Comment by ducpv-1644** [comment] 2023-06-21 02:26
@xuesichao Thank you. I tried reproduce the issue using the WebRTC sample: https://webrtc.github.io/samples/src/content/getusermedia/gum/

The device I use is: **Safari - iPhone 7 Plus - IOS 15.5**

The result is exactly the same as the problem we are having. The video play/stop button has appeared.
You can watch the video below:

https://github.com/aws/amazon-chime-sdk-js/assets/48663821/4797c70c-1de6-4277-beb5-aa53ab497040

**Comment by xuesichao** [comment] 2023-06-21 19:14
@ducpv-1644 This is iOS's behavior and out of control of our SDK. I found this solution online, maybe you can give it a try?
This CSS may be able to hide those controls:
```
video::-webkit-media-controls {
    display:none !important;
}
```
Or
```
*::-webkit-media-controls-panel {

  display: none!important;

  -webkit-appearance: none;

}

*::--webkit-media-controls-play-button {

  display: none!important;

  -webkit-appearance: none;

}

*::-webkit-media-controls-start-playback-button {

  display: none!important;

  -webkit-appearance: none;

}
```

**Comment by ducpv-1644** [comment] 2023-06-26 07:54
@xuesichao 
Thanks for your support. But it doesn't work in my React Application. 
This problem still appears when I use **Safari - iPhone 7 Plus - IOS 15.5** .
It stuck with me for a long time. Do you have any other ideas? I am so thankful for that.

**Comment by xuesichao** [comment] 2023-06-26 17:17
Try these:
1. https://stackoverflow.com/questions/8911247/hide-iphone-html5-video-play-button
2. https://stackoverflow.com/questions/40742351/hide-html5-video-play-button-on-ios
3. https://stackoverflow.com/questions/23617054/how-to-hide-the-controls-of-the-html5-video-tag-with-ios-iphone-devices-on-webki

Since this is iOS behavior, I'm resolving this issue now.

**Closed by xuesichao** 2023-06-26 17:17 UTC
