### ISSUE TITLE
Unable to stretch video tile vertically

### ISSUE THREAD

**Issue by husaindevelop** [aws/amazon-chime-sdk-js#1836] opened 2021-11-27 15:41 UTC
### What happened and what did you expect to happen?

![error](https://user-images.githubusercontent.com/62126860/143687740-68dd3a73-2ec5-435b-adeb-2b4feaf58ef5.png)

This is test video chat room. As you can see, the viewport dimensions is 400 width x 700 height. But the video tile only reaches 400px width and 250px height, which means it is only the quarter of the viewport's dimension. What i want is that tile should fully cover the viewport's dimension to 400w x 700h like the one in whatsapp video chat. We tried changing css dimensions like object-fit:cover, max-height, max-width. Created a wrapper div under video tag, but none of them works for us. Shall appreciate should you find us a way out of this issue. Thank you.

### Have you reviewed our existing documentation?

- [X] GitHub [issues](https://github.com/aws/amazon-chime-sdk-js/issues)
- [X] FAQs [page](https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html)
- [X] README [page](https://github.com/aws/amazon-chime-sdk-js#amazon-chime-sdk-for-javascript)
- [X] Feature-specific [guides](https://github.com/aws/amazon-chime-sdk-js#guides)

### Reproduction steps

On successful meeting id creation, the self tile element is initialized. 
On initialization, the video tile does not display based on the dimensions set, for example as we set: 400 width and 800 height. It just opens a blank space around the height set and displays the image at 400 width and 250 height, almost dimensions being proportionate.

### Amazon Chime SDK for JavaScript version

Latest one

### What browsers are you seeing the problem on?

Chrome

### Browser version

96

### Browser console logs

Its design related issue, so logs are not necessary, you can view the url though for better understanding

**Comment by devalevenkatesh** [comment] 2021-11-29 18:43
Hi @husaindevelop ,

Thanks for reporting the issue, could you please check this [FAQ](https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html#how-can-i-create-a-video-tile-layout-for-my-application) and see whether handling the video dimensions based on the aspect ratio helps?

Also is this issue an duplicate of #1817?

**Comment by husaindevelop** [comment] 2021-12-02 08:01
Yes its a duplicate of 1817. Since you asked us to submit a bug request, we raised this ticket. Regarding the problem, used the object-fit:contain css and resized videoElementCssheight, videoElementCsswidth but it continues to display the tile same way as the screenshot is displaying. Please guide us as what we should do. Thanks.

**Comment by devalevenkatesh** [comment] 2021-12-29 21:38
Closing this issue due to provided guideline here in an duplicate of this:
https://github.com/aws/amazon-chime-sdk-js/issues/1891#issuecomment-999870232

So the video stream dimensions cannot be changed rather the video itself can zoom-in / out based on the `object-fit: contain | cover` or `chooseVideoInputQuality` API. We do not have a workaround or solution to preserve the video's dimensions itself as it depends on the source who is sharing and the way currently the media constraints are requested. Make sure you call `chooseVideoInputQuality` API before calling `chooseVideoInputDevice` that way the later will honor what you requested with first.

**Closed by devalevenkatesh** 2021-12-29 21:38 UTC
Labels: Question
