### ISSUE TITLE
Cannot find name 'OffscreenCanvas' Angular 13

### ISSUE THREAD

**Issue by mohamadkhalil88** [aws/amazon-chime-sdk-js#1938] opened 2022-01-14 13:01 UTC
### What happened and what did you expect to happen?

I upgrade my application angular 13, now i have error with the library:

```
Error: node_modules/amazon-chime-sdk-js/build/videoframeprocessor/VideoFrameBuffer.d.ts:33:45 - error TS2304: Cannot find name 'OffscreenCanvas'.

33     asCanvasElement?(): HTMLCanvasElement | OffscreenCanvas | null;
```

### Have you reviewed our existing documentation?

- [X] GitHub [issues](https://github.com/aws/amazon-chime-sdk-js/issues)
- [X] FAQs [page](https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html)
- [X] README [page](https://github.com/aws/amazon-chime-sdk-js#amazon-chime-sdk-for-javascript)
- [X] Feature-specific [guides](https://github.com/aws/amazon-chime-sdk-js#guides)

### Reproduction steps

Create a new app with angular 13, install the package and call it, then run "npm run build"

### Amazon Chime SDK for JavaScript version

2.25.0

### What browsers are you seeing the problem on?

no browser

### Browser version

no browser

### Browser console logs

 Error: node_modules/amazon-chime-sdk-js/build/videoframeprocessor/VideoFrameBuffer.d.ts:33:45 - error TS2304: Cannot find name 'OffscreenCanvas'.

33     asCanvasElement?(): HTMLCanvasElement | OffscreenCanvas | null;
                                               ~~~~~~~~~~~~~~~

**Comment by ltrung** [comment] 2022-01-20 22:34
This is a duplicate of https://github.com/aws/amazon-chime-sdk-js/issues/1909. There is a workaround suggested.

**Closed by ltrung** 2022-01-20 22:34 UTC
