### ISSUE TITLE
Improve/Add documentation for simple UC use cases using the Chime JS SDK

### ISSUE THREAD

**Issue by vidya-mohan** [aws/amazon-chime-sdk-js#201] opened 2020-04-01 16:24 UTC
### What are you trying to do?
There have been several issues filed such as #198 on the lack of sufficient documentation for basic scenarios on the JS SDK such as video join, basic audio controls and notifications. This is tracking improvement and discoverability in that front. Also point to code snippets in a demo to support the learning

### How can the documentation be improved to help your use case?

Improve the GettingStarted or ReadMe documentation 

### What documentation have you looked at so far?

README.md, Amazon Chime SDK Developer Guide, GettingStarted

**Comment by mding5692** [comment] 2020-04-01 18:51
Hi, we've been recently contacted with an offer from AWS Chime to add AWS Chime JS SDK to our company application, I'm following this topic too because want to know if there are any documentation that are specific. As well, we have been in meetings with developers from AWS Chime but in general we would like some kind of docs that might go over like a quickstart which describes how using Javascript we can create a 1:1 videocall because we feel like we might miss something just using the AWS Chime API Reference.

**Comment by aburnson** [comment] 2020-04-03 17:02
Closing as duplicate of #223

**Closed by aburnson** 2020-04-03 17:02 UTC
Labels: documentation
