### ISSUE TITLE
Need video-frame length and breadth be varied at discretion

### ISSUE THREAD

**Issue by husaindevelop** [aws/amazon-chime-sdk-js#1817] opened 2021-11-21 06:53 UTC
Soon we experience a problem, you are reminded and undermentioned lose no time connecting you. Here before you with another problem soliciting your guidance for its way out. That was only in the ligher vein, we do remember you and valued support you have provided.

The current problem that we have encountered is the dimension of video-frame enhances proportionately and not discretely. For instance the size we get is 400px x 250 and enhances proportionately to 800 x 500 and not discretely like 400 x 800. To be more precise, we need the length and breadth be varied at discretion. Sure this problem replenishes grist to grind

**Comment by devalevenkatesh** [comment] 2021-11-23 22:50
@husaindevelop could you please provide any screenshots to better understand your issue here?

- We would like to understand what you are trying to do?
- Are you using any video uplink / downlink policy features?
- Is this specific browser related?
- For instance the size we get is 400px x 250 and enhances proportionately to 800 x 500 and not discretely like 400 x 800? Could you explain when this happens?
- Are you trying to explicitly set video input quality using `chooseVideoInputQuality`?

Request you to fill create issue with "Bug form template" to better capture the details when you open an issue.

**Comment by husaindevelop** [comment] 2021-11-24 16:03
The screenshots would give you a better understanding
![error](https://user-images.githubusercontent.com/62126860/143272672-cdb9dad4-2510-4e5a-9ab2-fd8f88d4b955.png)
This is test video chat room. As you can see, the viewport dimensions is 400 width x 700 height. But the video tile only reaches 400px width and 250px height, which means it is only the quarter of the viewport's dimension. What i want is that tile should fully cover the viewport's dimension to 400w x 700h like the one in whatsapp video chat.  We tried changing css dimensions like object-fit:cover, max-height, max-width. Created a wrapper div under <video> tag, but none of them works for us. Shall appreciate should you find us a way out of this issue. Thank you.

**Comment by husaindevelop** [comment] 2021-11-25 06:10
Prompt response to queries however complicated, complex they were has been your characteristic, which is laudable. Understand circumstances you are into now and therefore no issue about the delay. Take your time and let things come to status quo ante. Shall Wait.

**Comment by husaindevelop** [comment] 2021-11-27 01:33
Hope you have resumed operations per status quo ante and looking forward for your support against query seeking as how vide tile's length and breadth be varied at discretion.

**Comment by ltrung** [comment] 2021-12-11 01:36
Close as duplicate of #1836

**Closed by ltrung** 2021-12-11 01:36 UTC
Labels: Needs More Information
