### ISSUE TITLE
Voice Focus Leak : WebRTC audio stream not released

### ISSUE THREAD

**Issue by chdeps** [aws/amazon-chime-sdk-js#2298] opened 2022-06-14 14:27 UTC
### What happened and what did you expect to happen?

After intializing Voice Focus, the webRTC audio stream is never released. 

I'm creating a `VoiceFocusTransformDevice` through the `VoiceFocusDeviceTransformer` and using the default `voicefocus-inline-processor`. When Stopping the device through the `stop()` method and ending the meeting, we can still see active webRTC audio streams through chrome debugger (chrome://webrtc-internals). 

I noticed that when stopping the `worklet-inline-node` we send a 'stop' message through the port, yet we dont stop the worker that seems to stay alive. 
In the meetingV2 demo app, you dont get the issue because you seem to redirect to another page straight after ending the meeting.

### Have you reviewed our existing documentation?

- [X] GitHub [issues](https://github.com/aws/amazon-chime-sdk-js/issues)
- [X] FAQs [page](https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html)
- [X] README [page](https://github.com/aws/amazon-chime-sdk-js#amazon-chime-sdk-for-javascript)
- [X] Feature-specific [guides](https://github.com/aws/amazon-chime-sdk-js#guides)

### Reproduction steps

Supposing you have a started audioVideo meeting :

- Create a voice focus transformer with `VoiceFocusDeviceTransformer.create`. It will create in turn a `VoiceFocus` and its associated worker. **How do you I destroy it even without creating a device ?**

- Create a voice focus device with `.createTransformDevice(innerDevice)` and `startAudioInput` on deviceController of the `meetingSession`'s `audioVideo`

- Call `stop` on the device, when stopping the `audioVideo` and destroying the `deviceController`

You still have running webRTC audio streams.

### Amazon Chime SDK for JavaScript version

3.2.0

### What browsers are you seeing the problem on?

Mac OS Chrome

### Browser version

Version 102.0.5005.61 (Official Build) (x86_64) 

### Browser console logs

Remaining webRTC audio streams :
![9019aecf0c353bfa14b6b1660a7e97eb](https://user-images.githubusercontent.com/32538485/173602066-3805bdea-3451-44fd-bc7d-29e1541987c4.png)

**Comment by devalevenkatesh** [comment] 2022-06-14 16:10
Thanks for reporting the issue. Could you once confirm when you say `stop` on the device, are you calling `stopAudioInput` before destroying device controller?

Migration guide section on audio API changes: https://github.com/aws/amazon-chime-sdk-js/blob/main/guides/17_Migration_to_3_0.md#updates-to-the-audio-input-api

**Comment by chdeps** [comment] 2022-06-17 14:58
Shouldn't we stop the worker in the worklet-inline-node (https://github.com/aws/amazon-chime-sdk-js/blob/a030477974b93f54025da5c3f25197cfdc656b71/libs/voicefocus/worklet-inline-node.js#L56) or through the processing of the `stop` message ?

**Comment by richhx** [comment] 2022-06-23 07:07
Hey @chdeps, thanks for raising this issue. After giving it a look, the worker is definitely not being released. I've submitted a PR at https://github.com/aws/amazon-chime-sdk-js/pull/2320 to fix this issue.

However, I believe the worker leak is unrelated to the WebRTC stream leak. This can be tested out through the following steps in the demo application (on the release branch).

1. Deploy the demo application on the release branch (or main, though the additional options wasn't working for me when I tried)
2. Open chrome://webrtc-internals/ in a tab.
3. Open the demo site in a new tab
4. Enter stuff into "Meeting Title" and "Your Name"
5. Make sure "Web Audio" is unselected
6. Click "Continue"
7. Click "Join" (notice that there's no "Enable Voice Focus" option since Web Audio is disabled)
8. Hold the "Shift" key and click the "Leave meeting" green icon in the top-right. The "Shift" key is important here because it will not redirect the page, thereby allowing us to debug the contents of the page.
9. Notice that it says "Gone" on the page.
10. Visit the chrome://webrtc-internals/ tab that was previously opened.
11. Notice that even though the "Connection state" is "closed", ICE connection state is still "connected", Signaling state is "stable", and WebRTC audio streams and audio sources are still running

Logs from my testing:
https://pastebin.com/1WaxaC8m

Screenshot from my testing:
<img width="1423" alt="Screen Shot 2022-06-22 at 11 55 53 PM" src="https://user-images.githubusercontent.com/8881667/175235763-d5cf06a7-13c9-4cb4-b3fb-68aa57414189.png">

Based on this testing, my guess is it's somewhere in the controller and not the Voice Focus library, since the Voice Focus code isn't even executed in this test path and the issue is still reproduced.

@michhyun1 or @devalevenkatesh are you able to look into this further?

**Comment by michhyun1** [comment] 2022-06-30 17:32
@richhx Thanks for the help! I was not able to reproduce this - my webrtc internal tab will be cleared when I leave the meeting while pressing the shift button. 

We definitely close the signalingClient when we leave the meeting: https://github.com/aws/amazon-chime-sdk-js/blob/e526e89af28b2334dab7d60e178b092717228b24/src/task/CleanStoppedSessionTask.ts#L30

**Comment by nainkunal933** [comment] 2022-07-07 22:55
@chdeps Can you please download the latest version of JS SDK from main branch and try the code in your application again? @richhx's PR will be included in 3.7.0 release of the SDK and that release should come out soon. It seems like Richard's PR might fix your issue here. 

I will like to bring up some `VoiceFocusTransformDevice` code that is relevant to the discussion of audio stream here. When a user is selecting the voice focus option, the audio stream is getting created here:
https://github.com/aws/amazon-chime-sdk-js/blob/d4898eef452db3ed6fe02144d824d7642be79428/src/voicefocus/VoiceFocusTransformDevice.ts#L194

And `this.node` is destroyed on meeting leave by this code:
https://github.com/aws/amazon-chime-sdk-js/blob/d4898eef452db3ed6fe02144d824d7642be79428/src/voicefocus/VoiceFocusTransformDevice.ts#L72-L77

So, there should not be any audio stream that is running when the user leaves the meeting. I will recommend taking a look at JS SDK demo code here under `app/meetingV2`:
https://github.com/aws/amazon-chime-sdk-js/tree/main/demos/browser

If you have questions about the worker implementation, I will refer to @richhx's expertise on that.

If you still have the same issue can you please send some more information on what makes you think the audio stream is not getting released? I will like to take a look.

**Comment by nainkunal933** [comment] 2022-07-19 23:39
There was some confusion about the expected behavior of the chrome webrtc internals page during investigation. I suspected this as an issue and opened a Chromium bug. We have some progress on that bug where the chromium team has identified the behavior as inconsistent and have marked the bug with P3 severity.

You can follow the bug here: https://bugs.chromium.org/p/chromium/issues/detail?id=1343010#c3

Notify: @richhx @michhyun1 

@chdeps Are we good to close this issue? I will close it after a week of no response.

**Comment by devalevenkatesh** [comment] 2022-08-04 00:57
Closing as stale with no response, feel free to re-open if you still need help with this issue.

**Closed by devalevenkatesh** 2022-08-04 00:57 UTC
Labels: Needs More Information, audio-ml

**Comment by chdeps** [comment] 2022-11-15 08:26
@nainkunal933 Thanks for investigating! 
I'll follow up on Chromium issue :)
