### ISSUE TITLE
Can not join a meeting and start video on Chrome canary version 87.0.4251.0 (Official Build) canary (64-bit)

### ISSUE THREAD

**Issue by fangzhoulu-hiretual** [aws/amazon-chime-sdk-js#646] opened 2020-09-01 20:16 UTC
**Describe the bug**
Seems I cannot join a meeting with the newest Chrome canary and open video. And I can reproduce it with the browser demo. But chrome works.

**Screenshots**
If applicable, add screenshots to help explain the problem.
![image](https://user-images.githubusercontent.com/36866257/91901485-21b35e80-ec55-11ea-9612-7b24583d43c9.png)

![image](https://user-images.githubusercontent.com/36866257/91901510-2d9f2080-ec55-11ea-8331-034c98acf4ff.png)

**Platform**
 - OS: Windows 10
 - Browser:  Chrome canary 
 - Browser Version: 87.0.4251.0
 - Amazon Chime SDK Version: 1.16

**Logs**
[localhost-1598991248505.log](https://github.com/aws/amazon-chime-sdk-js/files/5158576/localhost-1598991248505.log)

**Comment by Sean-Der** [comment] 2020-09-16 17:15
Hi @fangzhoulu-hiretual 

Thanks for reporting this. We did some investigation and it turns out to be a Chrome bug https://bugs.chromium.org/p/chromium/issues/detail?id=1124384

The issue was fixed in Canary. This will not be broken in any stable releases of Chrome.

**Closed** 2020-09-16 18:38 UTC
Labels: Triaged

**Comment by aburnson** [comment] 2020-09-30 15:55
I've confirmed that in these latest versions of Chrome dev and Chrome canary, the issue no longer reproduces:

Version 87.0.4270.0 (Official Build) dev (x86_64)
Version 87.0.4278.0 (Official Build) canary (x86_64)
