### ISSUE TITLE
Add connection recovery methods

### ISSUE THREAD

**Issue by aburnson** [aws/amazon-chime-sdk-js#321] opened 2020-04-30 17:15 UTC
Need these to determine when the connection has recovered:

- connectionDidBecomeGood (opposite of connectionDidBecomePoor)
- connectionDidSuggestRestartVideo (opposite of connectionDidSuggestStopVideo)

Can be triggered here:
https://github.com/aws/amazon-chime-sdk-js/blob/01ea3c81a0e3c49ac13ea8e1aec2414f2419754b/src/task/MonitorTask.ts#L239

**Comment by vidya-mohan** [comment] 2020-05-01 16:34
Dupe of https://github.com/aws/amazon-chime-sdk-js/issues/320

**Closed by vidya-mohan** 2020-05-01 16:34 UTC
