### ISSUE TITLE
Echo occurs when participant joins from android chrome

### ISSUE THREAD

**Issue by Rambarani** [aws/amazon-chime-sdk-js#1752] opened 2021-11-05 11:11 UTC
### What happened and what did you expect to happen?

**When one participant join from desktop chrome and other participant join from mobile chrome means**, echo issue happens
**participant joins from desktop chrome hears his own voice back** and sometimes there may be delay in voice.

If both people join from desktop chrome means no issue.

So problem with android chrome. I tested with official demo code and all android devices (Redmi, POCO, motorola)

### Have you reviewed our existing documentation?

- [X] GitHub [issues](https://github.com/aws/amazon-chime-sdk-js/issues)
- [X] FAQs [page](https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html)
- [X] README [page](https://github.com/aws/amazon-chime-sdk-js#amazon-chime-sdk-for-javascript)
- [X] Feature-specific [guides](https://github.com/aws/amazon-chime-sdk-js#guides)

### Reproduction steps

1. 1st Participant join from desktop
2. 2nd Participant join from mobile chrome browser.

Means the desktop participant will hears his own voice back and echo.

I used

amazon-chime-sdk-component-library-react: 2.11.1
amazon-chime-sdk-js: 2.20.0

I tested in these all devices.

Mobile: android (POCO)
Browser: chrome
version: 95.0.4638.72

Mobile: android (Moto G Play)
Browser: chrome
version: 94.0.4608.85

Mobile: android ( redmi )
Browser: chrome
version: 83.0.4303.101

etc..

 

### Amazon Chime SDK for JavaScript version

2.20.0

### What browsers are you seeing the problem on?

Chrome

### Browser version

87.0.4280.101

### Browser console logs

Since i am facing issues in mobile chrome browser alone. i did;t take any log from mobile.

**Comment by xuesichao** [comment] 2021-11-05 17:28
Hi @Rambarani , thanks for reporting the issue!

When retrieving your microphone, the Chime SDK for JavaScript passes the following constraints to enable echo cancellation supported by the browser. See [here](https://github.com/aws/amazon-chime-sdk-js/blob/1c4ea707597eb63fb0735238c2c707bf19d38708/src/devicecontroller/DefaultDeviceController.ts#L1701-L1708) for the complete list.

* [echoCancellation](https://developer.mozilla.org/en-US/docs/Web/API/MediaTrackConstraints/echoCancellation)
* googEchoCancellation
* googNoiseSuppression

If your Android browser does not support these echo-related constraints, echo cancellation won't work. Besides these constraints, the current version (2.21.0) of Chime SDK for JavaScript does not perform any custom logic to suppress echo.

#### Suggestions

* On your Android device, can you try a WebRTC official example (https://appr.tc) and see if other participants can hear an echo from you?

* Have you tried enabling the [Amazon Voice Focus](https://aws.github.io/amazon-chime-sdk-js/modules/amazonvoice_focus.html) on your Android device? Amazon Voice Focus is a noise suppressor to reduce unwanted background noise. The current version of Amazon Voice Focus does not perform echo cancellation, but you can try it out to see if reducing the noise helps.

* The Chrome 87.0.4280.101 is supported by Amazon Voice Focus. See the [Browser compatibility](https://aws.github.io/amazon-chime-sdk-js/modules/amazonvoice_focus.html#can-i-use-amazon-voice-focus-in-my-application) for more information.

* We recommend wearing headphones when using a cell phone. Without using the headphone, the sound from the speaker is easily captured by the microphone, thus creating an echo.

**Comment by Rambarani** [comment] 2021-11-06 03:58
Thanks @xuesichao ! for the reply.

I used amazon focus. but it did't turned on by default. Participant have turn it on manually. if it is turned on means no echo occurs. so is there any way we can turn it on by default when joining meeting ?

**Comment by xuesichao** [comment] 2021-11-06 17:25
Hi @Rambarani , we received several requests about how to enable the Voice Focus by default. We are tracking this request in issue #1755. I need to confirm with the team about it. I know that before joining the meeting, SDK support enabling the Voice Focus in the device setup process. You could check how we implement that from our [JS SDK browser demo](https://github.com/aws/amazon-chime-sdk-js/tree/master/demos/browser). Could you please check this demo first and we will post the update in the issue #1755.

**Comment by xuesichao** [comment] 2021-11-06 17:47
Close the issue, because it is a duplicate of issue #1756. Please track the updates there.

**Closed by xuesichao** 2021-11-06 17:47 UTC
Labels: Bug
