### ISSUE TITLE
Attendees getting AudioJoinedFromAnotherDevice error on joining meeting

### ISSUE THREAD

**Issue by kg-jcaron** [aws/amazon-chime-sdk-js#1290] opened 2021-05-13 15:56 UTC
We've been running into an issue where we frequently get AudioJoinedFromAnotherDevice (2) terminal status code for some attendees in our meetings immediately after joining, which prevents them from connecting to the meeting.

We've verified that no-one getting this is actually joining from multiple devices, and we've tried implementing auto-reconnecting users when this happens but it doesn't fix it for the majority of our attendees who encounter this.

We were originally storing and reusing attendee connection info, but stopped doing that to try and resolve this bug. With creating new attendees on each join we are still getting the error frequently.

Bug info:

Meeting ID: b8a1dcf5-7f14-4000-80a0-53a0a9916f86
Attendee ID who received AudioJoinedFromAnotherDevice status code:
- External user id: 270158
- Chime attendee id: not sure unfortunately (our logs were misconfigured)

Logs:
2021-05-13T15:01:33 console.log -- audioVideoDidStart observer called
2021-05-13T15:01:33.761Z [ERROR] [BS ChimeLogger] - session will not be reconnected
2021-05-13T15:01:33.763Z [ERROR] [BS ChimeLogger] - failed with status code AudioJoinedFromAnotherDevice
2021-05-13T15:01:33.818Z [WARN] [BS ChimeLogger] - no transition found from Disconnecting with Update
2021-05-13T15:01:33.820Z [WARN] [BS ChimeLogger] - no stream found for tile=null
2021-05-13T15:01:33.820Z [WARN] [BS ChimeLogger] - no stream found for tile=null
2021-05-13T15:01:33.820Z [WARN] [BS ChimeLogger] - no stream found for tile=null
2021-05-13T15:01:33.821Z [WARN] [BS ChimeLogger] - no stream found for tile=null

Timeline:
2021-05-13T15:01 - user joins and we call audioVideo.start()
2021-05-13T15:01 - immediately fails

Platform:
- OS: macOS 10.15.7 (19H114)
- Browser: Chrome
- Browser Version: 90.0.4430.212 (Official Build) (x86_64)
- Amazon Chime SDK Github Commit: v2.8.0 tag (release from npm)

**Comment by devalevenkatesh** [comment] 2021-05-17 16:58
Hello, thanks for reporting the issue.

We are still investigating this issue. The JS SDK gets the `AudioJoinedFromAnotherDevice` meeting session status code from the backend and has no logic that may trigger this internally from JS SDK. We have created a ticket internally to investigate this issue further.

It would be really helpful to get some browser console logs around this issue as you see this to be frequent on your side.

Also, could you please provide information to few questions below:
1. Does your code join an attendee to the same meeting before the attendee has been fully disconnected or left?
2. Does your code use `audioVideoDidStop` observer to wait and receive the failure code `AudioJoinedFromAnotherDevice` and after that only start the reconnection?

**Comment by kg-jcaron** [comment] 2021-05-18 14:15
Hi sorry we don't have additional logs from the browser beyond what was initially in the ticket. That seems to be all we really see logged for this issue.

I think we might have found the issue though, we switched to never reusing the same external user id (we're now appending a uuid to the end and then parsing it back out later when we need to reference the id for something), and haven't seen this issue since.

In the past we've seen the bug  when joining the same meeting or a new meeting that's never had that external user id in it before, and we've seen it whether or not we call DeleteAttendees through the sdk on the backend first before adding a new attendee with that external id.

To answer your questions:

1. No, the first meeting session is destroyed before creating a new one to the same/a new meeting
2. Yes we are using the audioVideoDidStop observer to try the auto-reconnect when we get that status code

**Comment by devalevenkatesh** [comment] 2021-05-18 22:26
Thank you for the response and we are glad that the issue is resolved now. As an action item we will be adding an FAQ on the `AudioJoinedFromAnotherDevice` meeting session status code.

I have linked the PR for the same. Closing this issue now, please re-open / create new issue if you have further questions.

**Closed by devalevenkatesh** 2021-05-18 22:26 UTC
Labels: Needs More Information
