### ISSUE TITLE
Switching video inputs causes instability on certain mobile devices

### ISSUE THREAD

**Issue by jheising** [aws/amazon-chime-sdk-js#1316] opened 2021-05-25 18:20 UTC
# Problem

Calling `meetingSession.audioVideo.chooseVideoInputDevice` using a `facingMode` or `deviceID` causes the following error to occur:

`
2021-05-18T15:59:25.589Z [ERROR] SDK - failed to get video device for constraints {"video":{"deviceId":{"exact":"defd88d947ae14dba27177afb67ef6c240451813ea401fcc4a31d62093e6b2de"},"width":{"ideal":960},"height":{"ideal":540},"frameRate":{"ideal":15},"googCpuOveruseDetection":true,"googCpuOveruseEncodeUsage":true,"googCpuOveruseThreshold":85,"googCpuUnderuseThreshold":55}}: NotReadableError: Could not start video source
meetingV2.ts:2007 [DEMO] Received an event: {"name":"videoInputFailed","attributes":{"attendeeId":"4af6414a-e88a-e3c7-3920-7b107d4da593","browserMajorVersion":"89","browserName":"Chrome","browserVersion":"89.0.4389.105","deviceName":"Samsung SM-G973F","externalMeetingId":"jheising","externalUserId":"1bafe552#Browser","meetingHistory":[{"name":"audioInputSelected","timestampMs":1621353500077},{"name":"videoInputSelected","timestampMs":1621353501001},{"name":"meetingStartRequested","timestampMs":1621353504847},{"name":"videoInputUnselected","timestampMs":1621353504868},{"name":"meetingStartSucceeded","timestampMs":1621353506033},{"name":"attendeePresenceReceived","timestampMs":1621353506216},{"name":"videoInputSelected","timestampMs":1621353519076},{"name":"videoInputFailed","timestampMs":1621353531627},{"name":"videoInputFailed","timestampMs":1621353539818},{"name":"videoInputSelected","timestampMs":1621353544169},{"name":"videoInputFailed","timestampMs":1621353548259},{"name":"videoInputFailed","timestampMs":1621353561652},{"name":"videoInputFailed","timestampMs":1621353565588}],"meetingId":"56fd5d69-def0-493a-9198-0dec276c3c82","osName":"Android","osVersion":"9","sdkVersion":"2.9.0","sdkName":"amazon-chime-sdk-js","timestampMs":1621353565588,"videoInputErrorMessage":"NotReadableError: Could not start video source"}}`

# Details

- Seems to mostly occur on many Samsung and LG devices. This specific error occurred on a Samsung S10 running Android 9 running Chrome.
- Once the error occurs it becomes impossible to switch the video input device to another device.
- The error doesn't occur at once— it seems to take 1 or 2 device switches before it happens. But once it happens, it seems to be unrecoverable.
- This was reproducible using an Amazon reference implementation/example for the SDK.

# Possible Solution
My theory was that it's possible those media track constraints that start with `googCpu` were causing the issue. So I commented out the lines at https://github.com/aws/amazon-chime-sdk-js/blob/22b82e54beaa1aca6bfb583903edf22f31f86e4e/src/devicecontroller/DefaultDeviceController.ts#L1550-L1556 and it seems to have made the issue better (but not quite 100%).

**Comment by jheising** [comment] 2021-05-25 18:58
Looking at it further it actually seems like it may have to do more with the width, height, and framerate constraints: https://github.com/aws/amazon-chime-sdk-js/blob/22b82e54beaa1aca6bfb583903edf22f31f86e4e/src/devicecontroller/DefaultDeviceController.ts#L1538-L1546

Commenting those out seems to solve the problem entirely.

**Comment by ldai1** [comment] 2021-05-27 00:39
Hi, 

Thanks for bringing up this issue and possible solutions. We will review the issue and get back to you once we confirmed the solution.

**Comment by XHatan** [comment] 2021-06-01 17:36
@jheising 

Hi, Jim thanks for letting us know about this.
I am trying this out on the mobile devices I have but it does not seem to reproduce.
I guess this might be device related. 

Before I can get a hold of a device, could you try change the lines here  https://github.com/aws/amazon-chime-sdk-js/blob/22b82e54beaa1aca6bfb583903edf22f31f86e4e/src/devicecontroller/DefaultDeviceController.ts#L1538-L1546

to 
```
trackConstraints.width =  { ideal: trackConstraints.width || this.videoInputQualitySettings.videoWidth };      
trackConstraints.height = {  ideal: trackConstraints.height ||  this.videoInputQualitySettings.videoHeight };      
trackConstraints.frameRate = {  ideal: trackConstraints.frameRate ||  this.videoInputQualitySettings.videoFrameRate };
```

**Comment by jheising** [comment] 2021-06-04 16:00
@XHatan hello, yes I've tried ideal, exact, and everything in between and it doesn't seem to matter. I am able to produce almost all the time on a Samsung S20. It also seems to happen pretty often on the Pixel 5 as well. Can you tell me which devices you are trying on? For many of them it works great, but S20's and Pixel 5's are pretty common.

In further testing it seems to be a combo more of the goog constraints and the frame rate combo strangely enough.

**Comment by XHatan** [comment] 2021-06-04 18:29
Thanks for the pointers. 
I cleaned up and removed the goog constraints  in the master branch since most of them are deprecated. I guess you already try comment those out so I am not sure if it will help.

Yeah, I do not have Samsung and Pixel devices right now. just trying out on huawei and ios

**Comment by XHatan** [comment] 2021-06-09 00:14
@jheising I could reproduce this in a Huawei device. but this does not work for me even if I comment out the code like you mentioned
https://github.com/aws/amazon-chime-sdk-js/issues/1316#issuecomment-848181394  

it looks like in Android Chrome, last acquired media stream needs to be completely released before getUserMedia could return a new media stream

**Comment by michhyun1** [comment] 2021-07-13 19:43
@jheising Following up on this thread. Have you tried what @XHatan has suggested above? For some devices, the mediaStream needs to be explicitly released before activating a new stream. I'd  recommend trying to call `stopLocalVideoTile` and then `startLocalVideoTile` when you switch between video inputs. Can you try this and get back to me? If you're doing this with a video preview - you can use `stopVideoPreview` and `startVideoPreview` to achieve the same effect.

**Comment by shriyajuneja** [comment] 2021-07-28 13:20
Hi @michhyun1,  I'm using ```selectVideoInputDevice``` from amazon-chime-sdk-component-library-react, In my case below solution works. But ideally this should be handled in selectVideoInputDevice or chooseVideoInputDevice.
```
audioVideo?.stopLocalVideoTile();
await meetingManager.selectVideoInputDevice(deviceId);
audioVideo?.startLocalVideoTile();
audioVideo?.startVideoPreviewForVideoInput(localVideoRef.current);
```

**Comment by michhyun1** [comment] 2021-07-28 17:50
There is a fix in PR right now - https://github.com/aws/amazon-chime-sdk-js/pull/1452

**Comment by michhyun1** [comment] 2021-07-29 19:48
@jheising Please feel free to try out the master branch - a fixed has been merged. Please let us know if that fix works for you! Thanks.

**Comment by michhyun1** [comment] 2021-08-06 16:29
Resolving for now since there was no feedback - please let us know if the issue still exists.

**Closed by michhyun1** 2021-08-06 16:29 UTC
Labels: Triaged, video, device

**Comment by shriyajuneja** [comment] 2021-09-13 15:30
Hi @michhyun1, it works after updating to 2.15.0, but there's still an issue if we keep switching camera devices continuously (3-4 times), chooseVideoInputDevice fails without throwing any error.
I'm changing camera input using following function
` await meetingManager.audioVideo?.chooseVideoInputDevice(deviceId);`


Meeting Id - 5deee7e2-8cf3-4501-babe-d31bda610706

Logs - 
```
[ERROR] SDK - no video device chosen, stopping local video tile
2021-09-13T15:22:54.059Z [ERROR] Meet Logger 5deee7e2-8cf3-4501-babe-d31bda610706 - no video device chosen, stopping local video tile
2021-09-13T15:22:54.068Z [WARN] Meet Logger 5deee7e2-8cf3-4501-babe-d31bda610706 - could not acquire video input from current device
```

**Comment by michhyun1** [comment] 2021-09-13 16:53
@shriyajuneja Can you please create a new issue so that we can track it there? Thanks
