### ISSUE TITLE
audioVideo.stop does not stop/clean everything

### ISSUE THREAD

**Issue by rlebosse** [aws/amazon-chime-sdk-js#706] opened 2020-09-23 09:41 UTC
* For my test, I have blocked the domain `chime.aws` with the Little Snitch app (real use case : the user is on a network that is blocking the domain `chime.aws`)

* In the browser, I initialize, set some observers and start the meeting session :
```js
const logger = new ConsoleLogger('SDK', LogLevel.WARN)
const deviceController = new DefaultDeviceController(logger)
const configuration = new MeetingSessionConfiguration(
    meetingData,
    attendeeData
)
const meetingSession = new DefaultMeetingSession(
    configuration,
    logger,
    deviceController
)
const audioVideo = meetingSession.audioVideo
const audioVideoObserver = {
    audioVideoDidStartConnecting(reconnecting) {
        console.log('RLE audioVideoDidStartConnecting', {reconnecting})
    },
    audioVideoDidStart() {
        console.log('RLE audioVideoDidStart')
    },
    audioVideoDidStop(sessionStatus: MeetingSessionStatus) {
        console.log('RLE audioVideoDidStop', {
            sessionStatus,
            statusCode: sessionStatus?.statusCode(),
        })
    },
}
audioVideo.addObserver(audioVideoObserver)
audioVideo.start()
```

* I receive the `audioVideoDidStartConnecting` with `reconnecting = false`
* I can see in the Chrome DevTools that the `amazon-chime-sdk-js` is trying to connect to the Chime Meeting (in vain), multiple times
* After some time, in my code, I call `audioVideo.stop()`
* I expect from the `amazon-chime-sdk-js` to stop trying to connect to the Chime Meeting, but it keeps doing it !

Moreover, if stop blocking the domain `chime.aws` after calling `audioVideo.stop()`, the other attendees will see me joining the Chime Meeting even if I explicitly stopped it.

Would it be possible to make the call to `audioVideo.stop()` to stop trying to connect to the Chime meeting please ?
I think there should be a way to clean stop everything.

Thanks in advance !

**Platform**
 - OS: macOS 10.15.6
 - Browser: Google Chrome 85
 - Amazon Chime SDK version: 1.18.0

**Comment by rlebosse** [comment] 2020-10-13 09:41
Any news on this issue ?

**Comment by bradmanAWS** [comment] 2020-12-08 22:41
Hi @rlebosse I just looked into this issue and I cannot reproduce this behavior. Running `audioVideo.stop()` kills the meeting session, as expected. Can you confirm this is still an issue for you? Sorry for the delay.

**Comment by devalevenkatesh** [comment] 2021-01-19 23:58
Closing this issue, since the [fix](https://github.com/aws/amazon-chime-sdk-js/pull/1008) is merged now. The `AudioVideo.stop()` will kill the reconnecting now.

**Closed by devalevenkatesh** 2021-01-19 23:58 UTC
Labels: Bug, Triaged
