### ISSUE TITLE
FAQs feedback

### ISSUE THREAD

**Issue by tumbelin** [aws/amazon-chime-sdk-js#810] opened 2020-10-23 16:09 UTC
Hi, I know you have a workaround for recording meetings, but, are you going to implement an easy way to use it?. I consider the current method is pretty hard to use.

**Comment by vidya-mohan** [comment] 2020-10-23 21:06
@tumbelin could you please clarify which workaround you are talking about and what challenges you are having presently?

**Comment by tumbelin** [comment] 2020-10-23 21:29
@vidya-mohan I meant this one (https://aws.amazon.com/es/blogs/business-productivity/how-to-enable-client-side-recording-using-the-amazon-chime-sdk/), I already did it, it looks easy but It took me 2 weeks because I was having problems due to memory space with Cloud9 service and I did not know at that moment, someone helped me with that (https://github.com/aws-samples/amazon-chime-sdk-recording-demo/issues/48), also if you want to customize some parameters like video-name or end location to have a control of these files you have to go in deep of the walkthrough to discover how.
I think all this process could be easier and friendly to customize.

**Comment by anuranduttaroy** [comment] 2020-10-26 20:34
@tumbelin These are some of the topics I noted from the above message to update the README with.
- Cloud9 service (Recommendation on memory, instance type to use etc)
- How to customize some parameters like video-name or end location

Is there any other areas which took most of your time which we can improve on?

**Comment by tumbelin** [comment] 2020-10-26 23:36
Hi @anuranduttaroy I consider that there are 2 topics that would be good mention as regards recordings:

- Recommendations or best practices for multiple recording, I am planning launch this recording feature in the nearly future, expecting to have more than 1000 concurrent recording, but I have to do it slowly because I don't know clearly how this solution go to behave both in prices or architecture.

- Auto-end option alternative, let's suppose I have a user with the privilege to record a meeting, but for some reason, this person leaves the meeting without invoke the stop action, it means that recording will continue theoretically endlessly.

**Comment by vidya-mohan** [comment] 2021-05-26 17:37
Resolving as dupe of https://github.com/aws/amazon-chime-sdk-js/issues/1011 which tracks better recording support

**Closed by vidya-mohan** 2021-05-26 17:37 UTC
Labels: Documentation, Triaged
