### ISSUE TITLE
Remote videos disappear after some participant stopLocalVideo 

### ISSUE THREAD

**Issue by AlexUlianets** [aws/amazon-chime-sdk-js#1742] opened 2021-11-01 11:34 UTC
### What happened and what did you expect to happen?

1 - open first user (no camera)
2 - open 2nd user (use camera)
3 - open 3rd user (use camera)

When the second user stops his video, all remote videos disappear.

Expected result: do not lose all participants.

Seems it doesn't go to videoDidupdate method

### Have you reviewed our existing documentation?

- [X] GitHub [issues](https://github.com/aws/amazon-chime-sdk-js/issues)
- [X] FAQs [page](https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html)
- [X] README [page](https://github.com/aws/amazon-chime-sdk-js#amazon-chime-sdk-for-javascript)
- [X] Feature-specific [guides](https://github.com/aws/amazon-chime-sdk-js#guides)

### Reproduction steps

1 - open first user (no camera)
2 - open 2nd user (use camera)
3 - open 3rd user (use camera)

When the second user stops his video, all remote videos disappear.

### Amazon Chime SDK for JavaScript version

2.17

### What browsers are you seeing the problem on?

Chrome

### Browser version

Chrome Version 95.0.4638.54 (Official Build) (x86_64)

### Browser console logs

No errors.

**Comment by ltrung** [comment] 2021-11-02 20:28
Hi, I could not reproduce this issue using our [meeting demo](https://github.com/aws/amazon-chime-sdk-js/tree/master/demos/browser).
Could you provide a console log so we could investigate further?

**Comment by devalevenkatesh** [comment] 2021-11-18 17:30
Closing the issue due to no-activity, please feel free to re-open if you still face issue. As suggested in an earlier comment request to also refer the meeting demo linked to compare the implementation.

**Closed by devalevenkatesh** 2021-11-18 17:30 UTC
Labels: Needs More Information, video
