### ISSUE TITLE
Plug off headphones while in call interrupts the input stream with Smartphones ( Android - iOS ).

### ISSUE THREAD

**Issue by felipenandz** [aws/amazon-chime-sdk-js#1721] opened 2021-10-26 12:51 UTC
### What happened and what did you expect to happen?

Trying to plug off the headphones while in the call but the switch doesn't work automatically with mobile phones and the input audio is interrupted. I choose the new device after **audioInputsChanged** is triggered by calling chooseAudioInputDevice with the device ID. 

I expect that plugging off the headphones and choosing the new Audio stream works fluid. 

- The switch works automatically with **desktop browsers** and if I use **Airpods.** ( plug in and plug of many times ) and audio continues working for remote. 

- **Weird Thing:** It works if I start the call without headphones and then plug it in (Input stream continues working ),  but then when I plug it off it stops working.

- **Call keep dropping**: If I start the call with headphones and plug it off, the input audio stream stops, and chime keeps trying to reconnect.

- **_Fun fact_:** If I switch between apps in my phone and come back to safari the input audio starts to work again. 

**Worth attention:** **In the app demo of chime sdk the behaviour is the same (plugging off interrupts the input stream), so I don't think it's a problem in my code**

Devices Tested: 

Android
Iphone SE - v.14.2 
Iphone 12 - v.15.2

### Have you reviewed our existing documentation?

- [X] GitHub [issues](https://github.com/aws/amazon-chime-sdk-js/issues)
- [X] FAQs [page](https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html)
- [X] README [page](https://github.com/aws/amazon-chime-sdk-js#amazon-chime-sdk-for-javascript)
- [X] Feature-specific [guides](https://github.com/aws/amazon-chime-sdk-js#guides)

### Reproduction steps

(Mobile Phone - Not working) Enter the call with headphones and then plug it off -> Input stream interrupts
(Desktop - Working) Enter the call with headphones and then plug it off -> Input stream continues working

### Amazon Chime SDK for JavaScript version

^2.18.0

### What browsers are you seeing the problem on?

Chrome, Firefox, Safari

### Browser version

Chome - 95.0.4638.50

### Browser console logs

choosing the new device works well while looking in the console log, all works successfully.

**Comment by xuesichao** [comment] 2021-11-01 00:38
@felipenandz Hi, thanks for providing the detailed reproduce steps. In our previous test we didn't enable the WebAudio, and it worked well. This time we followed the detailed steps you provided, and confirm the issue exists.

I notice that "set fullband speech (mono) quality" has nothing to do with this question. As long as I enable the WebAudio for mobile attendee, I can reproduce the issue using: iPhone 13 Pro + iOS 15.1 + mobile Safari/mobile Chrome.

I think the current mitigation is: NOT enable the WebAudio for mobile attendee if possible. 

We are investigating this issue and will keep you posted. Thanks for your patience!

**Comment by felipenandz** [comment] 2021-11-01 21:52
Hi @xuesichao , thank you for your feedback. 

Awesome, we will implement this control for the moment. 

Thank you very much.

**Comment by xuesichao** [comment] 2021-11-02 22:54
Hi @felipenandz , we confirm the bug also occurs without using the Chime SDK for JavaScript. We cut a new ticket in the WebKit Bugzilla and will escalate it to Apple (Check [here](https://bugs.webkit.org/show_bug.cgi?id=232640)).

We can't think of mitigations other than disabling WebAudio while waiting for Apple to fix it.

**Comment by devalevenkatesh** [comment] 2021-11-24 06:43
Closing this issue, since we have added a WebKit bug and added it to #1059 list where we track all browser bugs. Thanks!

**Closed by devalevenkatesh** 2021-11-24 06:43 UTC
Labels: Browser Bug

**Comment by dinuone** [comment] 2023-06-27 04:46
I'm facing the same issue what is the solution?
