### ISSUE TITLE
Error deploy lamdba folder - videohelpdesk demo

### ISSUE THREAD

**Issue by acidSnkj** [aws/amazon-chime-sdk-js#310] opened 2020-04-29 17:17 UTC
### What are you trying to do?

I'm trying to mount and run the VideoHelpDesk to test, follow the steps until this part

> Deploy the API, On the right-hand side open the AWS Resources tab, locate the Lambda pane. Under Local Functions, select the videohelpdesk folder containing the Lambdas it detected in the project and press the Deploy button (the icon showing an up arrow).

I uplaod the folder after the `npm run build` to cloud9, and when I try no deploy the lamdba folder 
got this first.

![imagen](https://user-images.githubusercontent.com/58449502/80625589-0d472700-8a13-11ea-8d02-e21f3e14f9e3.png)

then I push the button delete stack and try again, but then  this happend.

![imagen](https://user-images.githubusercontent.com/58449502/80625230-86924a00-8a12-11ea-94cc-b8c096937251.png)

So I cant continue with the example.

### What documentation have you looked at so far?

Amazon Chime SDK README.md videohelpdesk

Can u help me please?

Thank you.

**Comment by aburnson** [comment] 2020-04-29 22:15
Hi @acidSnkj , I'm not sure what caused this error. I have been unable to reproduce it so far. Try going to your CloudFormation stacks list:

https://console.aws.amazon.com/cloudformation/home?region=us-east-1#/stacks?filteringText=cloud9-videohelpdesk&filteringStatus=active&viewNested=true&hideStacks=false&stackId=

And deleting the `cloud9-videohelpdesk` stack entirely. Wait until the stack is completely deleted (reload page until it is no longer in the list of stacks). Then back in the Cloud9 environment, under AWS Resources > Lambda > Local Functions, select `videohelpdesk` and press the `Deploy` up arrow button.

Once that finishes, go back to the CloudFormation stacks and confirm the stack is in the green `CREATE_COMPLETE` state. If it's not go to the events for that stack, and post the event list that you are getting back on this GitHub issue so we can see what is going on.

**Comment by acidSnkj** [comment] 2020-05-01 00:34
Thank you for the anwser, the first problem is solve, but now I have this problem.
In this point I already done the deploys and uncomment  as the guides says.

So I try to connect to the URL: `https://5jwjrqj6zh.execute-api.us-east-1.amazonaws.com/Prod/helpdesk`

and got this error: 
```
helpdesk:1 GET https://5jwjrqj6zh.execute-api.us-east-1.amazonaws.com/Prod/helpdesk 502
favicon.ico:1 GET https://5jwjrqj6zh.execute-api.us-east-1.amazonaws.com/favicon.ico 403
```

In cloudwacth this show up.
```
{
    "errorType": "Runtime.ImportModuleError",
    "errorMessage": "Error: Cannot find module 'uuid/v4'",
    "stack": [
        "Runtime.ImportModuleError: Error: Cannot find module 'uuid/v4'",
        "    at _loadUserApp (/var/runtime/UserFunction.js:100:13)",
        "    at Object.module.exports.load (/var/runtime/UserFunction.js:140:17)",
        "    at Object.<anonymous> (/var/runtime/index.js:45:30)",
        "    at Module._compile (internal/modules/cjs/loader.js:778:30)",
        "    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)",
        "    at Module.load (internal/modules/cjs/loader.js:653:32)",
        "    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)",
        "    at Function.Module._load (internal/modules/cjs/loader.js:585:3)",
        "    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)",
        "    at startup (internal/bootstrap/node.js:283:19)"
    ]
}
```

So, I try to install the `uuid4`, add to the package, etc. Then build and deploy again. But still the problem persist.

**Comment by aburnson** [comment] 2020-05-01 19:51
Hmm, and just to confirm you did run `npm run build`?

As part of the build script, a Lambda Layer is created that includes the `uuid` package. If you navigate to the Lambda console, is there a Lambda Layer? It sounds like either that layer isn't there or the layer is missing that dependency for some reason. You may want to try deleting the layer and re-running `npm run build`. Even after recreating the Lambda Layer, the layer version may increment past version 1. If this is the case, you would need to update the `template.yaml` to point at the latest version for the layer here:

https://github.com/aws/amazon-chime-sdk-js/blob/master/demos/videohelpdesk/template.yaml#L17

Ultimately we should change this demo to not use Lambda Layers and instead bundle the packages directly into the Lambda. Marking this issue with `enhancement` label.

**Comment by acidSnkj** [comment] 2020-05-02 02:04
Thank you, ok I did what you say about the version (delete the layer)
I had the version 1, and after the delete change to 2.

Updated the template, but still the same error uuid4 :(

![Captura de pantalla de 2020-05-01 20-33-06](https://user-images.githubusercontent.com/58449502/80852565-39b79a80-8bef-11ea-9a5d-63ec4e1c7edf.png)

**Comment by pemmerich** [comment] 2020-05-19 14:17
I had a similar issue with the UUID library.
Using the newest version of UUID you have to declare it like this:
const { v4: uuidv4 } = require('uuid');
rather than:
const uuidv4 = require('uuid/v4');
in handlers.js
Hope this helps.

**Comment by devalevenkatesh** [comment] 2020-12-30 01:19
Closing this issue. The suggested `uuid` import was fixed in [this](https://github.com/aws/amazon-chime-sdk-js/commit/e7f7d4c3dfede746292c70bd76c332806aaea268) commit. Let us know if you still face any issue.

**Closed by devalevenkatesh** 2020-12-30 01:19 UTC
Labels: Documentation, Enhancement, Minor Issue, Triaged
