### ISSUE TITLE
In mac safari browser mic and camera doesn't work

### ISSUE THREAD

**Issue by vibhakchosla** [aws/amazon-chime-sdk-js#1003] opened 2021-01-12 03:34 UTC
If user is using Safari in mac and navigates to a different tab within their browser or any other application, their audio as well as video is lost to other meeting attendees. Other attendee can not see or listen that mac safari user.

Is this known issue or will i have to do some configuration for mac safari ?

I am using 2.3.0 version of sdk.

**Comment by nicklera1** [comment] 2021-01-12 22:49
Hi @vibhakchosla,

The behavior described above could imply that there could be some relation with privacy policies that come in effect when webpage is out of focus. 
What version of MacOS and Safari user is using?
Is the same happens when "Safari user" uses Chrome or Firefox?
Is it possible to provide a video of user exercise? 
And most importantly could you please provide logs from both "Safari User" and if possible at least one other users and meetingId during which this issues occurs. 
Thanks!

**Comment by nicklera1** [comment] 2021-01-21 17:43
Please see our [FAQ](https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html#my-video-disappears-in-safari-browsers-is-this-a-known-issue) related to your question. In short this is a limitation of Safari browser on both macOS and iOS devices. 

Resolving! Feel free to re-open if needed.

**Comment by lavluda** [comment] 2021-05-31 14:47
@nicklera1 can we please reopen this ticket and investigate. i can reproduce this issue using the Demo app.  
Steps: 
1. Join 2 user on safari 
2. First make sure both users can hear each other
3. now open a new tab in the same browser window for User A
4. User B will not able to hear User A, until User A return to the Demo apps tab. 

ps: opening a new window (not tab), the mic still works fine. 
OS: Mac 10.15.7 
Safari: 14.1

I think this problem can reproduce on the latest OS too.

**Comment by michhyun1** [comment] 2021-06-02 18:04
I was not able to reproduce this. Here is the steps that I took:

1. User A - Join the meeting from a Phone (Chrome)
2. User B - Join the meeting from Safari (14.1) on Mac 10.15.7
3. User B - open a new tab and navigate to the new Tab
4. Speak into User B's mic while being on a different tab than the meeting demo
5. Verified that User A can still hear User B

Are you joining the meeting for both Users on the same Safari window?

**Comment by lavluda** [comment] 2021-06-02 20:07
@michhyun1 thanks for trying it. I did more test. And noticed, this problem only occurred when the speaking person has webaudio enabled at the join. 

I used 2 mac for the test.

**Comment by michhyun1** [comment] 2021-06-03 22:25
@lavluda, Yes, I've been able to reproduce the bug. I haven't been able to reproduce this in other browsers, and I cannot reproduce this with other WebRTC based apps because it requires WebAudio to be enabled and I don't know how to enable WebAudio for other WebRTC based apps.

**Comment by lavluda** [comment] 2021-06-04 09:35
@michhyun1 yes, we are using it for our meeting system. Yes, this bug only exists on the safari browser. For us, the workaround for this is to disable WebAudio for safari user, which is not best solution.

**Comment by michhyun1** [comment] 2021-06-07 20:35
@lavluda thanks for bringing this up - this might be a bug on the WebKit side. I haven't seen this behavior on other browsers. I'll try to repro this using a mediaRecorder and audio graph and then see if the audio graph goes flat when I switch tabs.

**Comment by devalevenkatesh** [comment] 2021-11-19 02:34
We have filed a WebKit bug for the same:
https://bugs.webkit.org/show_bug.cgi?id=231105

We have added it to know browser issues. Request you to please check. Closing the issue as we have an active Webkit bug for it.

**Closed by devalevenkatesh** 2021-11-19 02:34 UTC
Labels: device
