### ISSUE TITLE
Preview video input device with video processor using 'startVideoPreviewForVideoInput'

### ISSUE THREAD

**Issue by paul365** [aws/amazon-chime-sdk-js#1297] opened 2021-05-17 18:47 UTC
### What are you trying to do?

I'm trying to show a preview of a video processor with selected device on device setup. I'm using 'startVideoPreviewForVideoInput' but the video processor is not applied in the preview. Logs says 'video transform device processing started' and continuing into the meeting the video processor is applied there. Can this be done? Thanks

### How can the documentation be improved to help your use case?

Show a section on how to do this if possible or add it to the demo :)

### What documentation have you looked at so far?

README.md, Amazon Chime SDK Developer Guide, etc.

**Comment by simmkyu** [comment] 2021-05-19 17:25
The `startVideoPreviewForVideoInput` API does not support the video transform device yet. In the current version (`2.9.0`), the preview API uses an underlying `MediaStream` object of a selected device. We will keep this issue open and post any updates.

**Comment by vidya-mohan** [comment] 2021-07-14 23:19
@paul365  - I am resolving as duplicate of https://github.com/aws/amazon-chime-sdk-js/issues/1253 . Please follow that issue for updates

**Closed by vidya-mohan** 2021-07-14 23:19 UTC
Labels: feature-request, video
