### ISSUE TITLE
Needs for new feature to overcome 16 videotiles limitation

### ISSUE THREAD

**Issue by kyojunlee** [aws/amazon-chime-sdk-js#885] opened 2020-11-20 02:03 UTC
Zoom: "https://support.zoom.us/hc/en-us/articles/201362323-Changing-the-video-layout-Active-Speaker-View-and-Gallery-View-"
Zoom provides attendees pagination feature to selectively choose a page to see other attendees' video tiles(up to 49 per page). In this way, an attendee is able to communicate with all of the attendees with videos eventually.
On the other hand, Chime has hard limit of 16 video tiles which is not selectable, and automatically decided by the central server (first in gets the video tile).  It would be great if Chime should support the pagination feature like Zoom.

Also, if additional attendees turn on video when 16 video tiles are already filled, existing attendees who were using the video tiles lose connections randomly. (I think this is a bug!) If Chime team is gonna keep this hard limit of 16 videos, I think it is necessary to make sure that the 16 video tiles must not be affected by others who try to turn on camera later)

Thank you.

**Comment by p-foucht** [comment] 2020-12-22 23:43
Hi @kyojunlee, I'll relay your feature request to the team

[This repo](https://github.com/aws-samples/amazon-chime-sdk-smart-video-sending-demo) may be of interest to you, as it shows one potential way to workaround the 16 tile limit using websocket command messges. 

Not as robust, but you could consider preventing users from starting video on the client side when there are 16 video tiles present in the session

**Comment by devalevenkatesh** [comment] 2021-01-12 23:59
Just to add you can also come via the AWS support channel to discuss your app specific use case.

**Comment by vidya-mohan** [comment] 2021-11-05 16:45
SDK supports 25 video tiles. Dupe of https://github.com/aws/amazon-chime-sdk-js/issues/1497

**Closed by vidya-mohan** 2021-11-05 16:45 UTC
Labels: feature-request, Triaged
