### ISSUE TITLE
Specific users are disconnected from meeting on another users video being enabled.

### ISSUE THREAD

**Issue by Russelldan554** [aws/amazon-chime-sdk-js#1318] opened 2021-05-26 14:41 UTC
**Important:** Please attach INFO-level logs with timestamps to the report from *before* the session started up until the point at which the unexpected behavior occurred. For multi-participant calls, attach a log file for each participant if possible.

[Logs of attendee who left](https://github.com/aws/amazon-chime-sdk-js/files/6547464/attendee-left-logs-e666a28a-1bc8-44c0-a793-a2b0e2732b16.csv)

[Logs of user who turned on video](https://github.com/aws/amazon-chime-sdk-js/files/6547465/Attendee-toggled-video.log)

**Meeting and attendee IDs:**
MeetingId: e666a28a-1bc8-44c0-a793-a2b0e2732b16

Problematic Attendee
Attendee Id:  fd98ff48-ae14-b5d2-eafe-ecb608bb2f9b (Chrome, puppeteer container)

Non problematic Attendee
Attendee Id: 23ec6153-a194-d2d0-384a-ba078db384e0 (Chrome)
Attendee Id: 4a42890e-2fbf-6d9f-08e2-840f2e2bd78e (Chrome, also puppeteer container)

**Timeline**

* 2021-05-26T14:23:16.765Z Non problematic attendee turns on video
* 2021-05-26T14:23:18.989Z  Problematic Attendee loses websocket connection and disappears from the meeting roster

**Describe the bug**
As a user when I toggle on my video another attendee disappears from the session until I turn my video off then they reappear. This seemingly only happens to very few people. We had reports of this happening last week in a meeting but no errors were logged as far as we could tell. We eventually recreated it when using our puppeteer testing containers. We would launch two puppeteer containers that connect to our application through ECS using Fargate. These connect successfully and we have been using them for testing previously. When one connects there is no issue toggling video but when the second connects seemingly randomly one of them will lose connection to the meeting until the video is turned off. Oddly the containers themselves can toggle their video on without issue. I have tried recreating this with poor network conditions but have been unable to see the same effects locally.  

**Screenshots**
If applicable, add screenshots to help explain the problem.

**Platform**
 - OS: Ubuntu
 - Browser: Chrome
 - Browser Version: 90.0.4427
 - Amazon Chime SDK GitHub Commit: 
 - "amazon-chime-sdk-js": "^2.10.0",

**Comment by ldai1** [comment] 2021-05-27 00:23
Hi,

Thanks for providing details about this issue. When you mentioned another attendee would disappear when you toggle on your video, do you mean the other attendee were getting kicked out from the meeting and got rejoined automatically later when you toggle off your video?

**Comment by Russelldan554** [comment] 2021-05-27 21:11
Hey,

Yes the attendees was kicked. The non problematic users recieved the realtimeSubscribeToAttendeeIdPresence call back with that user as not present. However the user who dropped had no indication they where out of the meeting. there was no audioVideoDidStop call only a  connectionDidSuggestStopVideo call back and then when the main user turned off their video we received them back into the meeting normally.

**Comment by ldai1** [comment] 2021-05-27 22:47
Hi,

Thanks for the update! Can you double check if there is a realtime fatal error when those users got kicked out? This usually happens when  user calls the “realtimeSendDataMessage” API before or during the WebSocket connection, the API may fail, which resulting in  forcing log out.

**Comment by ldai1** [comment] 2021-05-28 23:04
Hi,

We checked the log you pasted and our server log and found that the attendee `fd98ff48` had an issue receiving audio packets immediately after another attendee `23ec6153` turned on the local video. After ~30 seconds, the attendee `fd98ff48` was reconnected to the session.

Some log here indicating the reason why the problematic Attendee got dropped and reconnected:
```1622039024261,"2021-05-26T14:23:44.220Z [WARN] SDK - reconnection recommended due to: no packets received: true, missed pongs: false, bad audio delay: false"```

We also found the timeline for this process:

Timeline
07:23:18 — The attendee (23ec6153) turned on the video
07:23:18 — The attendee (fd98ff48) dropped from the meeting due to missing audio packets.
07:23:45 — The attendee (fd98ff48) was reconnected.

The Chime SDK often outputs the above message when the attendee has a poor Internet connection. It seems that receiving the video stream affect audio bandwidth and causing reconnect.

I would suggest to implement the following audio observers and see if the attendee has network issues:
https://aws.github.io/amazon-chime-sdk-js/modules/qualitybandwidth_connectivity.html#events-for-monitoring-local-attendee-downlink

As you mentioned there is a `connectionDidSuggestStopVideo` which indicates that the audio connection is experiencing packet loss. Stopping local video and pausing remote video tiles may help the connection recover by reducing CPU usage and network consumption.

**Comment by Russelldan554** [comment] 2021-06-01 20:27
We setup the videoNotReceivingEnoughData callback and had it pause the video tile. However the user is still initially removed from the session but then they come back and stay in the session after about 15-20 seconds. This is problematic as if anyone toggles their video again they would be kicked again. Also it seems like the videoNotReceivingEnoughData is continuously sending updates even after the video is paused (videoNotReceivingEnoughData: [{"expectedAverageBitrateKbps":2.458,"receivedAverageBitrateKbps":0,"attendeeId":"32f8c1aa-33f0-a73b-3c47-7c04183ab58a"}] - This shows up every few seconds even though the video is paused). 

The other event watchers were setup but none of them were firing. We implemented (connectionDidSuggestStopVideo, videoSendDidBecomeUnavailable, videoAvailabilityDidChange, videoSendBandwidthDidChange, connectionDidBecomeGood, connectionDidBecomePoor, estimatedDownlinkBandwidthLessThanRequired). connectionDidSuggestStopVideo only fired only occasionally after the video was already stopped. 

Also once paused is there a way we would check to un pause the video when the connection improves if that was the problem and is there a way to automatically pause all incoming video for a user? 

How can we surface to the users that they are disconnected from the meeting and are reconnecting? Currently I don’t see any messages from audioVideoDidStop about reconnecting.

**Comment by ldai1** [comment] 2021-06-02 22:40
Hi,

For your last question, you probably can use audioVideoDIdStartConnecting, which is present with reconnection boolean parameter which they can use: https://github.com/aws/amazon-chime-sdk-js/blob/master/demos/browser/app/meetingV2/meetingV2.ts#L2506

To automatically pause video for a user, you probably can use this downlink policy `VideoPriorityBasedPolicy`, which providing the ability to explicitly request remote video sources to receive and set their respective priorities.  See [this guide](https://aws.github.io/amazon-chime-sdk-js/modules/prioritybased_downlink_policy.html) for more details and a code walkthrough of using the policy.


Hope this is helpful.

**Comment by XHatan** [comment] 2021-06-03 18:09
Thanks for reporting this.
Looking at server side log and the incident logs you provided , this does not result from bandwidth.
The server encountered a sending error and hanged up for the receiving attendee (hence we only saw the receiving attendee lost websocket). 

@Russelldan554  we will probably need some help to debug this further. While we are looking at this issue, were you able to reproduce this issue with our demo client ?

**Comment by Russelldan554** [comment] 2021-06-05 18:45
@XHatan We are consistently able to reproduce this with our puppeteer testing containers. They are just puppeteer scripts that connect to the meeting and sit there for awhile. These are launched in Fargate with varying cpu and memory limits although we noticed it happens whether we give it .5 cpu or 4 cpu. 

We have not tried to recreate it in the demo. We have been using the sdk in our app for over a year though and its been pretty stable. We only saw this happen in a real meeting once and in testing we only recreated it twice using browserstack and an Iphone on safari.

**Comment by Russelldan554** [comment] 2021-06-07 20:52
@XHatan We noticed today while testing that the bug has stopped happening. We tested on our develop and beta sites and the beta site code has not changed in a week so it does not seem like anything we fixed on our end. Is it possible the chime servers were updated? I will keep you informed if we see it pop up again but we just spent a while testing and it did not happen once.

**Comment by vidya-mohan** [comment] 2021-06-25 00:14
thanks @Russelldan554 , we will close the issue for now

**Closed by vidya-mohan** 2021-06-25 00:14 UTC
Labels: video
