### ISSUE TITLE
Error: ENOENT: no such file or directory, open 'dist/meetingV2.html'

### ISSUE THREAD

**Issue by gavandivya** [aws/amazon-chime-sdk-js#1330] opened 2021-05-29 11:25 UTC
### What are you trying to do?
trying to run npm run start:hot

I tried running npm run build, npm run start but I am getting the same error.

Error faced 
----------------------------------------
Using index path dist/meetingV2.html
internal/fs/utils.js:307
    throw err;
    ^

Error: ENOENT: no such file or directory, open 'dist/meetingV2.html'
    at Object.openSync (fs.js:476:3)
    at Object.readFileSync (fs.js:377:35)
    at Object.<anonymous> (C:\Users\Disha\amazon-chime-sdk-js\demos\browser\server.js:20:22)
    at Module._compile (C:\Users\Disha\amazon-chime-sdk-js\demos\browser\node_modules\v8-compile-cache\v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (C:\Users\Disha\amazon-chime-sdk-js\demos\browser\node_modules\v8-compile-cache\v8-compile-cache.js:159:20)
    at Object.onListening (C:\Users\Disha\amazon-chime-sdk-js\demos\browser\webpack.config.js:25:27) {
  errno: -4058,
  syscall: 'open',
  code: 'ENOENT',
  path: 'dist/meetingV2.html'
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! amazon-chime-sdk-js-demos@0.1.0 start:hot: `webpack-cli serve --config ./webpack.config.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the amazon-chime-sdk-js-demos@0.1.0 start:hot script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Disha\AppData\Roaming\npm-cache\_logs\2021-05-29T11_18_22_137Z-debug.log

**Comment by ltrung** [comment] 2021-06-01 18:20
@gavandivya The error means that the dist folder did not exist. Could you try to do the following steps?

1) In the root folder run `npm install`
2) In demos/browser, run `npm run start`

Let us know if it still doesn't work for you.

**Comment by gavandivya** [comment] 2021-06-01 19:38
Hello @ltrung It is not working
After following the above two steps mentioned by you.

The following error was thrown
Should start local server: true
Possible app: undefined
events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: spawn webpack ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:269:19)
    at onErrorNT (internal/child_process.js:465:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
    at onErrorNT (internal/child_process.js:465:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'spawn webpack',
  path: 'webpack',
  spawnargs: [ '--config', './webpack.config.js' ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! amazon-chime-sdk-js-demos@0.1.0 start:fast: `node script/webpack-wrapper.js --serve`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the amazon-chime-sdk-js-demos@0.1.0 start:fast script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Disha\AppData\Roaming\npm-cache\_logs\2021-06-01T19_33_47_632Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! amazon-chime-sdk-js-demos@0.1.0 start: `npm run deps && npm install && npm run start:fast`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the amazon-chime-sdk-js-demos@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Disha\AppData\Roaming\npm-cache\_logs\2021-06-01T19_33_47_790Z-debug.log

**Comment by gavandivya** [comment] 2021-06-01 19:42
OS - Windows10

node -v
v14.16.0

npm -v
6.14.11

**Comment by ltrung** [comment] 2021-06-02 21:10
@gavandivya Thanks, I have reproduced the issue. The problem is that our current build script in package.json `node script/webpack-wrapper.js` does not work in Windows. For now, could you replace the scripts part in the demos/browser package.json with the following and try again.
```
  "scripts": {
    "deps": "cd ../.. && npm run build",
    "build:fast": "tsc && webpack --config ./webpack.config.js",
    "build": "npm run deps && npm install && tsc && npm run build:fast",
    "start:fast": "npm run build:fast && node serve.js",
    "start:hot": "webpack-cli serve --config ./webpack.config.js",
    "start": "npm run deps && npm install && npm run start:fast"
  },
```

**Comment by ltrung** [comment] 2021-06-02 22:42
#1344 should fix this issue so closing this issue.

**Closed by ltrung** 2021-06-02 22:42 UTC
