### ISSUE TITLE
Turn ON/OFF Event camera delay 2s ~ 4s

### ISSUE THREAD

**Issue by mrnav90** [aws/amazon-chime-sdk-js#1953] opened 2022-01-24 05:02 UTC
Hi @ltrung 
Currently, we have issue with case revive events mute / unmute camera.
Some times, this issue happen with a camera device input or camera of macbook / windows.
I've checked and see event mute / unmute delay so can't show camera in same time with button on / off
Could you help check this case?
I will send you video record.

https://user-images.githubusercontent.com/9253581/150724699-b3b69011-2b02-4a57-8321-a953075f326e.mp4

Many thanks
 
 Sorry for set wrong issue label...

**Comment by mrnav90** [comment] 2022-01-28 01:41
@ltrung 
Could you please help check this issue?
Thanks

**Comment by ltrung** [comment] 2022-01-28 18:35
Is this a regression that you noticed recently or it has always been this way? 
I am not quite sure what you mean by mute/unmute. Do you mean toggle video on/off?
Also is this the same issue as #3 in https://github.com/aws/amazon-chime-sdk-js/issues/1968 ?

**Comment by ltrung** [comment] 2022-02-04 21:29
Closing due to inactivity but feel free to reopen if you still have issues.

**Comment by mrnav90** [comment] 2022-02-07 02:11
@ltrung 
Sorry for late.


> Is this a regression that you noticed recently or it has always been this way? I am not quite sure what you mean by mute/unmute. Do you mean toggle video on/off? Also is this the same issue as #3 in #1968 ?

--> yes. 

Chime SDK demo also happens issue mute / unmute ( blank / black video camera )
Please help check

**Comment by mrnav90** [comment] 2022-02-09 02:35
@ltrung hi, could you help check. I can't re-open this issue.

**Comment by ltrung** [comment] 2022-02-09 05:27
@mrnav90 Could you attach a console log so we could take a look further?

**Comment by mrnav90** [comment] 2022-02-09 14:10
@ltrung 
<img width="552" alt="Screen Shot 2022-02-09 at 16 57 03" src="https://user-images.githubusercontent.com/9253581/153217115-8acc3bc4-c756-4f12-bcc1-cac0e1863c7c.png">
After called `audioVideo.chooseAudioInputDevice` then event `videoTileDidUpdate` delay some seconds like video.
Chime SDK Demo App also happened issue.

**Comment by ltrung** [comment] 2022-02-09 18:49
I assume this is a typo and you mean `chooseVideoInputDevice`. The delay is because it tries to get the stream from browsers and update the subscription to back end.

**Comment by ltrung** [comment] 2022-02-09 19:32
Also if you could give us some logs we could confirm what takes time for you

**Comment by mrnav90** [comment] 2022-02-10 01:53
@ltrung 
This is video from Chime SDK demo
https://user-images.githubusercontent.com/9253581/153321859-4cf3215b-0ed8-41d4-a1eb-719047ffce87.mp4

**Comment by mrnav90** [comment] 2022-02-10 02:41
@ltrung @xuesichao 
This is video from Chime SDK Demo

https://user-images.githubusercontent.com/9253581/153326915-b0501ead-8493-4350-8d4e-eeb6f1bb52e7.mp4

**Comment by mrnav90** [comment] 2022-02-11 08:11
@ltrung @xuesichao 
Could you help check video...

**Comment by ltrung** [comment] 2022-02-11 17:58
@mrnav90 Yeah in our demo we just toggle the status of the button when you click on it so if you keep clicking it will go out of sync with the actually video on/off. As I mentioned above, this is because to it takes time to get video input from browsers and update the video subscription. We can do something in the UI to prevent you from clicking until the video show up.

**Comment by mrnav90** [comment] 2022-02-13 15:40
@ltrung 
Thank you, but for the future of Chime SDK. Chime SDK Team can be improve that?

**Comment by ltrung** [comment] 2022-02-14 16:39
Yes, I will close this issue for now and track the feature request in #1968.

**Closed by ltrung** 2022-02-14 16:39 UTC
Labels: device
