### ISSUE TITLE
Concatenation fails when recording started and stopped multiple times

### ISSUE THREAD

**Issue by chandruchiku** [aws/amazon-chime-sdk-js#2649] opened 2023-04-27 10:17 UTC
### What happened and what did you expect to happen?

I am using MediaPipeline APIs to start and stop recording of Chime Meeting. Finally calling a Concat API to concat all the chunks into a single file.

Recording Started and Stopped 1 time per meeting --> Concatenation API works 
Recording Started and Stopped 2 times per meeting --> Concatenation works
Recording Started and Stopped more than 3 Times per meeting --> Concatenation API shows InProgress and then concatinated file never appears on the S3.

### Have you reviewed our existing documentation?

- [X] FAQs [page](https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html)
- [X] GitHub [issues](https://github.com/aws/amazon-chime-sdk-js/issues)
- [X] README [page](https://github.com/aws/amazon-chime-sdk-js#amazon-chime-sdk-for-javascript)
- [X] Feature-specific [guides](https://github.com/aws/amazon-chime-sdk-js#guides)

### Reproduction steps

Start and Stop Recording more than 3 times in the same meeting. At the end of the meeting call concatination API with the last PipelineID as the input. 

### Amazon Chime SDK for JavaScript version

3.10

### What browsers are you seeing the problem on?

Not Applicable

### Browser version

Not Applicable

### Meeting and Attendee ID Information.

Meeting ID: 3cdec50d-357e-4d22-b625-970d4f0f2713

Pipeline1: 	19707faf-d882-4d70-ad79-89311b4d9bc9
Pipeline2: 	ec4b0fed-c18a-401e-a719-b559b99210a8
Pipeline3:	        8bcae0b3-6f28-44ab-8380-69f22431c151

Concat Pipeline ID: 574ceb60-9269-4abf-be93-2e637a69b390

### Browser console logs

Not Applicable

**Comment by nehtambe** [comment] 2023-05-04 17:36
@chandruchiku, thanks for reporting the issue. We are investigating, we will update you once we find the root cause and fix.

**Comment by nehtambe** [comment] 2023-05-04 22:35
@chandruchiku we have pushed a fix for to resolve the above issue. We will update here once its deployed.

**Closed** 2023-05-22 17:21 UTC
Labels: capture-service
