### ISSUE TITLE
Switching shared Chrome tabs causes share icon to remain after stopping content share

### ISSUE THREAD

**Issue by mark-vanr** [aws/amazon-chime-sdk-js#2153] opened 2022-04-04 22:07 UTC
### What happened and what did you expect to happen?

When content-sharing in a meeting, and sharing a Chrome tab, if the user switches to another Chrome tab and shares it, and then stops the content share in the meeting, the red dot on the meeting tab and the share icon in the shared tab do not go away even though the content share does stop. This is reproducible always.
If I end the meeting on the demo app the content share icon does go away, but not if I only stop content share while remaining in meeting.

### Have you reviewed our existing documentation?

- [X] GitHub [issues](https://github.com/aws/amazon-chime-sdk-js/issues)
- [X] FAQs [page](https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html)
- [X] README [page](https://github.com/aws/amazon-chime-sdk-js#amazon-chime-sdk-for-javascript)
- [X] Feature-specific [guides](https://github.com/aws/amazon-chime-sdk-js#guides)

### Reproduction steps

- Join a meeting in the meetingV2 demo app in Chrome; have 2+ other tabs open on Chrome
- Click the button to Toggle Content Share, select 'Chrome Tab', select a tab, and share
- Confirm correct tab is sharing in meeting.
- Switch to another, unshared Chrome tab and in the prompt select 'Share this tab instead'
- Return to the meeting tab and Toggle Content Share off
- Note that the shared Chrome tab still has the sharing icon on, and Chrome is still showing the prompt to Stop sharing

### Amazon Chime SDK for JavaScript version

2.30

### What browsers are you seeing the problem on?

Chrome

### Browser version

Version 100.0.4896.60

### Browser console logs

INFO log from reproducing on demo app:
[chrome_tab_sharing.log](https://github.com/aws/amazon-chime-sdk-js/files/8413403/chrome_tab_sharing.log)

**Comment by ltrung** [comment] 2022-04-06 01:19
@mark-vanr Thanks for reporting this. This looks like a Chrome bug since I could reproduce this by manually calling browser APIs as below:
```
stream = await navigator.mediaDevices.getDisplayMedia({ audio: true, video: true});
stream.getTracks()[0].stop(); //Audio
stream.getTracks()[1].stop(); // Video
```
The above code will have the same issue when you try to switch sharing tab (no issue if you do not switch). Interestingly, if we only request video with `getUserMedia` then there is also no issue even when switching tab.

**Comment by ltrung** [comment] 2022-05-09 16:49
@mark-vanr I believed the issue is fixed in latest Chrome version (although it seems they just removed the functionality) so closing the issue for now.

**Closed by ltrung** 2022-05-09 16:49 UTC
Labels: Browser Bug
