### ISSUE TITLE
Reconnect: Video Receive Fails when Mobile Peer Reconnects

### ISSUE THREAD

**Issue by tylerlot** [aws/amazon-chime-sdk-js#1029] opened 2021-01-26 18:26 UTC
Wanted to report a bug for the mobile client’s video reconnection logic between the mobile and web sdk. When we force the mobile client to reconnect to a meeting (toggling mobile device WiFi/LTE off/on, no web changes), we notice that after the mobile client reconnects, the mobile-video-send is not received by the web client (web client sees audioVideoTileWasRemoved fires after reconnection). The mobile local video preview remains intact. We are able to resolve this state by manually restarting the mobile client’s video feed. After reconnection there is no problem with the audio feed, this always resolves successful. The issue does not occur if the party who is “reconnecting” to the meeting is the web client.

**Meeting and attendee IDs:**
e289d41b-f0a2-072f-832e-0e12b8256d19 ::: desktop user attendee
6dc2e4ab-2670-82aa-49e8-81d03cf773ae ::: mobile user attendee
[Serverless demo logs.txt](https://github.com/aws/amazon-chime-sdk-js/files/5875214/Serverless.demo.logs.txt)
[Mobile logs.txt](https://github.com/aws/amazon-chime-sdk-js/files/5875215/Mobile.logs.txt)

**Describe the bug**
The bug appears as the web client not receiving any video from the mobile client after the mobile client goes through reconnection. Not sure if the issue is on the web or mobile side, so cutting across platforms.

We have been able to reproduce this issue on both iOS and Android platforms, and on separate devices.
- iOS issue: aws/amazon-chime-sdk-ios#221
- Android issue: aws/amazon-chime-sdk-android#222

We noticed the mobile app SDP contains 2 video tracks (the initial track, and a new one being offer). This is followed by logs indicating the web client receives a track event, but does not add the track as this attendee already has a tileId (logs attached). When the user attempts to workaround the bug by restarting their video, we see a log in the web client again that the stream does not belong to a known attendee. We believe the duplicate tracks to be the source of the issue here.

[TwoTrackSDPFromMobile.txt](https://github.com/aws/amazon-chime-sdk-js/files/5875255/TwoTrackSDPFromMobile.txt)

**Screenshots**
If applicable, add screenshots to help explain the problem.

**Platform**
 - OS: Mac
 - Browser: Chrome 
 - Browser Version: Version 88.0.4324.96 (Official Build) (x86_64)
 - Amazon Chime SDK GitHub Commit: 1.19

**Comment by simmkyu** [comment] 2021-01-29 01:05
The Chime server logs indicate that the mobile user dropped from the meeting four times. After each drop, the mobile user reconnected and restarted sharing the video. For two drop events, however, the desktop user's Chime SDK for JavaScript hasn't restarted viewing the video (See the Notes).

Timestamp (PST) | Desktop user's JS SDK | Mobile user's action | Notes
--|--|--|--
17:40:27 | Started viewing video | Joined the meeting and enabled the video for the first time | 
17:41:17 | No action found | Dropped from the meeting | 
17:41:38 | No action found | Reconnected and enabled the video | **The desktop user's JS SDK did not restart viewing video**
17:42:08 | Ended viewing video | Disabled the video | 
17:42:11 | Started viewing video | Dropped, reconnected, and enabled the video | 
17:42:36 | Ended viewing video | Dropped from the meeting | 
17:42:38 | Started viewing video | Reconnected and enabled the video again | 
17:43:13 | No action found | Dropped, reconnected, and enabled the video again | **The desktop user's JS SDK did not restart viewing video**
17:47:35 | Ended viewing video | Left the meeting | 

Questions
- Did the desktop user ever see the mobile video after reconnection? i.e., During this meeting from 17:40 to 17:47 (PST), how many times did the desktop user fail to view the mobile video?
- Could you please upload the `INFO` level logs from Chime SDK for JavaScript? We can check if JS SDK has an issue binding a video.
  ```
  const logger = new ConsoleLogger('MyLogger', LogLevel.INFO);
  ```

**Comment by tylerlot** [comment] 2021-01-29 01:18
The user saw the mobile user after the 2, 3, and 4th reconnections. The 1st and fifth did not restart the video. I can provide the full application logs offline. I attached the logs that seemed pertinent to the issue in `TwoTrackSDPFromMobile.txt`. 

The root of the problem is that the Chime SDK **chooses** to explicitly ignore the new track: 

2021-01-26T02:00:45.749Z [INFO] MyLogger - received track event: kind=video id=track_5 label=track_5

2021-01-26T02:00:45.750Z [INFO] MyLogger - Not adding remote track. Already have tile for attendeeId:  887bacce-ca8b-2f0a-b3d0-1f8c2ffe0d03

**Comment by vidya-mohan** [comment] 2021-02-15 22:26
The root cause is same as https://github.com/aws/amazon-chime-sdk-js/issues/561 so marking this as dupe. Please watch the master ticket for update

**Closed by vidya-mohan** 2021-02-15 22:26 UTC
