### ISSUE TITLE
Unexpected behavior of the meeting app: in iPhone once the user joins the meeting unexpectedly navigates to the join meeting screen

### ISSUE THREAD

**Issue by chinmayek** [aws/amazon-chime-sdk-js#2516] opened 2022-12-05 05:10 UTC
### What happened and what did you expect to happen?

Unexpected behavior of the meeting app: in iPhone once the user joins the meeting unexpectedly navigates to the join meeting screen. WebSocket connection is not successful. 

Expected: In all devices, once the user joins the meeting should be able to continue the meeting and should not navigates to the join meeting screen.

### Have you reviewed our existing documentation?

- [X] GitHub [issues](https://github.com/aws/amazon-chime-sdk-js/issues)
- [X] FAQs [page](https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html)
- [X] README [page](https://github.com/aws/amazon-chime-sdk-js#amazon-chime-sdk-for-javascript)
- [X] Feature-specific [guides](https://github.com/aws/amazon-chime-sdk-js#guides)

### Reproduction steps

In iPhone join any meeting.

### Amazon Chime SDK for JavaScript version

2.26.0

### What browsers are you seeing the problem on?

Mobile Safari

### Browser version

16.1

### Browser console logs

Once it navigates to join meeting screen logs will be cleared. so no logs.

**Comment by xuesichao** [comment] 2022-12-07 18:54
HI @chinmayek , I was not able to reproduce this issue using our [browser demo](https://github.com/aws/amazon-chime-sdk-js/tree/main/demos/browser) for both `v2.26.0` and `v3.9.0`. Could you try to reproduce the issue using this demo and provide us detailed repro steps for us to further debug the issue?

**Comment by devalevenkatesh** [comment] 2022-12-22 15:50
Hello, resolving this issue as we have not received further inputs, please feel free to re-open if you still find this issue.

In [v2.27.0](https://github.com/aws/amazon-chime-sdk-js/blob/main/CHANGELOG.md#2270---2022-01-27) there was a fix on reconnection on `close` event, not sure if this is related. PR: https://github.com/aws/amazon-chime-sdk-js/issues/1985

But suggest to try latest v3 version and let us know if you still have this issue.

**Closed by devalevenkatesh** 2022-12-22 15:50 UTC
Labels: Needs More Information

**Comment by chinmayek** [comment] 2022-12-22 17:22
I cross-checked with v3 and it was working. It helped me and resolved the issue. Thank you for your time and support.
