### ISSUE TITLE
failed to parse source map from '.../node_modules/amazon-chime-sdk-js/src/websocketadapter/defaultwebsocketadapter.ts' 

### ISSUE THREAD

**Issue by manojkalpana24** [aws/amazon-chime-sdk-js#2594] opened 2023-02-28 11:22 UTC
failed to parse source map from '.../node_modules/amazon-chime-sdk-js/src/websocketadapter/defaultwebsocketadapter.ts' 
file: error: enoent: no such file or directory, open '.../node_modules/amazon-chime-sdk-js/src/websocketadapter/defaultwebsocketadapter.ts'

Tried upgrading the amazon-chime-sdk-js to the latest version but no use. As 'src/' directory is not published with amazon-chime-sdk-js so it's blocking us from debugging the actual source also the above error is thrown while building the react application.

**Comment by xuesichao** [comment] 2023-03-22 21:48
Hi @manojkalpana24, sorry for late reply. I don't think we want to publish our `src/` folder in our library because we already published compiled `src/` folder - `build` folder.

It seems you imported `defaultwebsocketadapter` from wrong path. 
Try this instead:
```
node_modules/amazon-chime-sdk-js/build/websocketadapter/DefaultWebSocketAdapter.js
```

**Comment by senthilnathan27** [comment] 2023-07-26 11:05
how to use this path node_modules/amazon-chime-sdk-js/build/websocketadapter/DefaultWebSocketAdapter.js in create react app?

**Comment by mustafashabib** [comment] 2024-07-31 03:47
If it's helpful, I added this to my `webpack-config.js` in the root of my project to skip trying to load source maps for these `amazon-chime...` related dependencies

```javascript
 module: {
            strictExportPresence: true,
            rules: [
                // Handle node_modules packages that contain sourcemaps
                shouldUseSourceMap && {
                    enforce: 'pre',
                    exclude: /@babel(?:\/|\\{1,2})runtime/,
                    test: /\.(js|mjs|jsx|ts|tsx|css)$/,
                    loader: require.resolve('source-map-loader'),
                    options: {
                        filterSourceMappingUrl: (url, resourcePath) => {
                            const shouldSkipLoadingSourceMap =
                                /.*\/node_modules\/.*/.test(resourcePath) && /.*amazon-chime.*/.test(resourcePath);
                            return !shouldSkipLoadingSourceMap;
                        },
                    },
                },
```

**Comment by jp-hoehmann** [comment] 2024-08-22 15:06
@xuesichao the root cause of this is the source maps published with amazon-chime-sdk-js. The final distribution contains source maps referencing sources that do not exist. The source maps should either be removed, or the sources they map to should be included.

For example the file `build/websocketadapter/WebSocketReadyState.js` included in the distribution currently includes the line `//# sourceMappingURL=WebSocketReadyState.js.map`. This causes the source map `build/websocketadapter/WebSocketReadyState.js.map` to be loaded, which in turn points to `../../src/websocketadapter/WebSocketReadystate.ts`, which isn't included in the distribution, causing the error. To fix this, either the sources should be included in the distribution (allowing developers to step into the actual code of amazon-chime-sdk-js during debugging, but at the cost of increasing the package size), or the source maps (along with the references to them in the compiled javascript files) should be removed from the final package.

**Comment by ltrung** [comment] 2024-11-12 20:25
@jp-hoehmann Thanks. We did have an option to generate sourceMap .map file but not sure why it is not generated.

**Comment by ltrung** [comment] 2024-11-13 16:57
PR #3001 has merged to fix this issue so closing.

**Closed as completed by ltrung** 2024-11-13 16:57 UTC
Labels: Bug, Needs More Information
