### ISSUE TITLE
Video tiles are getting blank

### ISSUE THREAD

**Issue by JunedBrilworks** [aws/amazon-chime-sdk-js#2043] opened 2022-02-21 05:04 UTC
### What happened and what did you expect to happen?

we have noticed that video tiles are remaining blank in our application. Upon further investigating for blank tiles **MediaStream** 's id is something like **v_id** for example **v_12** instead of 36 character UUID. Turning the camera on/off for attendees whose tiles are blank also didn't help.

In our application, We have applied a downlink policy. Within the **videoTileDidUpdate** observer if the tile is **paused** we are showing the tile with the user avatar and if the tile is active and not paused then we are showing the video tile. Please guide if we are doing anything wrong at our end. The issue started to appear for versions after 2.24.0.

### Have you reviewed our existing documentation?

- [X] GitHub [issues](https://github.com/aws/amazon-chime-sdk-js/issues)
- [X] FAQs [page](https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html)
- [X] README [page](https://github.com/aws/amazon-chime-sdk-js#amazon-chime-sdk-for-javascript)
- [X] Feature-specific [guides](https://github.com/aws/amazon-chime-sdk-js#guides)

### Reproduction steps

It's happening randomly no exact reproduction step.

### Amazon Chime SDK for JavaScript version

2.27.0

### What browsers are you seeing the problem on?

Mostly all

### Browser version

Mostly All

### Browser console logs

Will try to replicate it again and put the exact log.

**Comment by ltrung** [comment] 2022-02-21 18:30
@JunedBrilworks Could you please attach a log?

**Comment by JunedBrilworks** [comment] 2022-02-22 05:35
We switched from 2.24.0 to 2.26.0 2.26.1 and 2.27.0 gradually in all this version issue is replicated. We have enabled simulcast recently and this issue is present with or without simulcast.

**Comment by JunedBrilworks** [comment] 2022-02-22 05:38
I will update to 2.27.0 and will post log ASAP.

**Comment by devalevenkatesh** [comment] 2022-02-23 01:31
@JunedBrilworks Could you also let us know which downlink policy you are using?

**Comment by JunedBrilworks** [comment] 2022-02-23 10:01
We are using `VideoPriorityBasedPolicy` policy

**Comment by devalevenkatesh** [comment] 2022-02-23 18:57
Thanks for the update, can you also provide the console logs and whether you have updated to latest version 2.27.0 of `amazon-chime-sdk-js`?

**Comment by devalevenkatesh** [comment] 2022-02-23 23:28
I am able to reproduce this issue with M1 mac mini, I will trying other machine to see if can repro. Basically even if the local side has valid UUID stream id for video or content share, the remote attendee gets it as `v_2`..`v_3` and then even though there is bound video stream in a `VideoTileState` it actually has incorrect streamIds.

I will update the issue once I have more info.

**Comment by devalevenkatesh** [comment] 2022-02-24 01:05
I also tested on a Intel Mac Big Sur 11.6.3 Safari Version 15.3 and could get the video and content share fine but the same does not work for Mac Mini M1 Safari 14. I tried the same JS SDK version so the stream IDs `v_2`.. `v_3` still work and no issues on UX.

**Comment by hensmi-amazon** [comment] 2022-02-24 01:38
Worth noting that we do not forward MSID, so it is expected that the remote receiving party's MSID will not match the senders. We use the `v_X` pattern for matching receive streams with the sending attendee ID.

**Comment by JunedBrilworks** [comment] 2022-02-24 06:24
Logs for the attendee who is receiving blank video tile 
**OS**: `macOS Big Sur 11.1  MacBook Air (M1, 2020) Apple M1`  
**Browser**:  `Firefox 97.0.1 64-bit`
[console-export-2022-2-24_11-48-36.txt](https://github.com/aws/amazon-chime-sdk-js/files/8130126/console-export-2022-2-24_11-48-36.txt)

Logs of attendee whose tile when blank
**OS**: `macOS Big Sur 11.1  MacBook Air (M1, 2020) Apple M1`  
**Browser**:  `Chrome 98.0.4758.102 (Official Build) (arm64)`
[localhost-1645683554975.log](https://github.com/aws/amazon-chime-sdk-js/files/8130150/localhost-1645683554975.log)

**Comment by devalevenkatesh** [comment] 2022-02-24 19:17
We have filed a WebKit bug for Apple M1 black content share issue: https://bugs.webkit.org/show_bug.cgi?id=236870. I am not sure yet if this is an issue with local video because, I tested camera video and it worked fine for from Safari -> any browser or from Chrome -> FF or FF -> Chrome. I have the same versions as mentioned above.

So only problem is for content share from Safari (14.0.2, 14.1.1, 14.1.2) on Apple M1 macOS Big Sur (my version is 11.1) -> any browser.

**Comment by JunedBrilworks** [comment] 2022-02-25 12:45
Happening in 2.24.0 also.
[www.devaccel.com-1645792724235.log](https://github.com/aws/amazon-chime-sdk-js/files/8141210/www.devaccel.com-1645792724235.log)
[www.devaccel.com-1645792973290.log](https://github.com/aws/amazon-chime-sdk-js/files/8141211/www.devaccel.com-1645792973290.log)

**Comment by JunedBrilworks** [comment] 2022-02-25 13:49
<img width="1440" alt="Screenshot 2022-02-25 at 19 16 37" src="https://user-images.githubusercontent.com/93306798/155726144-2976a56b-ffb5-462f-a13e-2a417d2cb6f1.png">
<img width="1440" alt="Screenshot 2022-02-25 at 19 17 19" src="https://user-images.githubusercontent.com/93306798/155726171-46683fbe-8df7-4418-9cc6-e35d73a1a8fe.png">
From logs looks like correspond  attendee is not found for stream id.

**Comment by JunedBrilworks** [comment] 2022-02-25 13:52
<img width="1404" alt="Screenshot 2022-02-25 at 19 20 15" src="https://user-images.githubusercontent.com/93306798/155726536-c80732dc-00d2-45ca-8b01-30920a11e327.png">
<img width="1392" alt="Screenshot 2022-02-25 at 19 20 51" src="https://user-images.githubusercontent.com/93306798/155726566-c9598e57-5cce-41d6-a0c9-5a287d2a32fc.png">

From logs looks like SDK fails to find corresponded attendee for stream and resulting in blank tile.

**Comment by JunedBrilworks** [comment] 2022-02-28 04:03
@devalevenkatesh @hensmi-amazon @ltrung 

Can you guys please give your feedback what could be possible solution ?

**Comment by devalevenkatesh** [comment] 2022-02-28 17:42
@JunedBrilworks I will go through the new logs. I did go through the older logs and found that attendees are starting the local videos before the SDK connects meeting session completely. From the logs, I see that the `startLocalVideoTile` call comes in while the SDK is completing the connection and hence any further update is deferred until SDK connection setup completes.

Can you confirm if you can use `audioVideoDidStart` observer to know that the SDK is connected completely and then call `startLocalVideoTile`?

I suspect that the deferred update leads to some missing updates. Still, I will go through the new logs and provide an update.

**Comment by devalevenkatesh** [comment] 2022-02-28 18:57
I also found that you are mentioned in other issue that you are modifying video preferences based on active speaker: https://github.com/aws/amazon-chime-sdk-js/issues/1927#issuecomment-1053858992. I think we recently merged in a fix https://github.com/aws/amazon-chime-sdk-js/pull/2055 for handling a similar issue to not mutate the video preference object which is currently been accessed so can you try this fix and see if that helps?

**Comment by devalevenkatesh** [comment] 2022-03-01 02:27
I think I went through the same `log-1` and `log-2` logs you provided and gave above suggestions, let me know if any of it works?

**Comment by JunedBrilworks** [comment] 2022-03-01 04:11
OK sure I will try it out and update it here.

**Comment by JunedBrilworks** [comment] 2022-03-03 11:46
Initial tests are looking good. 

Only notice a couple of times for firefox during the initial render. Looking forward to the solution of the below issue.
https://github.com/aws/amazon-chime-sdk-js/issues/2078

We close this issue if not reproducible during further tests.

**Comment by michhyun1** [comment] 2022-03-03 20:34
Great, thanks for the feedback and for communicating your results with us.

**Comment by ltrung** [comment] 2022-03-03 21:39
@JunedBrilworks Noticed that you mentioned Firefox which does not work with priority based downlink policy as the browser does not support bandwidth estimation stats. You can use this API [supportDownlinkBandwidthEstimation](https://github.com/aws/amazon-chime-sdk-js/blob/main/src/browserbehavior/DefaultBrowserBehavior.ts#L202) to check on whether you can use priority based downlink policy.

**Comment by JunedBrilworks** [comment] 2022-03-04 10:26
Yes, We can are using this API [supportDownlinkBandwidthEstimation](https://github.com/aws/amazon-chime-sdk-js/blob/main/src/browserbehavior/DefaultBrowserBehavior.ts#L202) to check on whether we can use a priority-based downlink policy.

For Firefox we have are also facing this issue https://github.com/aws/amazon-chime-sdk-js/issues/2078

**Comment by hensmi-amazon** [comment] 2022-03-16 21:09
https://github.com/aws/amazon-chime-sdk-js/issues/2078 backend deployment has been pushed.

**Comment by LeviSklaroff** [comment] 2022-04-19 22:00
This issue has not had a update in over 30 days and seems to have been resolved. Closing this issue.

**Closed by LeviSklaroff** 2022-04-19 22:00 UTC
Labels: video
