### ISSUE TITLE
checkBrowserSupportAndFeatureConfiguration returns null after browser detection

### ISSUE THREAD

**Issue by mgautam98** [aws/amazon-chime-sdk-js#2636] opened 2023-04-11 22:32 UTC
### What happened and what did you expect to happen?

Using chime in Android webview chime client throws following error. From what I checked it is failing wile reading `browser.name` in `checkBrowserSupportAndFeatureConfiguration`. 

Device details
- Pixel 6 API 33
- Android 13.0 Google APIs | arm64
- Chrome 101.0.4951.74

```
Error in meetingHandler try block TypeError: Cannot read properties of null (reading 'name')
    at s.name (asset?key=gautamx%2Fgautamx_LiveVideoShoppingBuyerFrontendServiceCR%2FLiveVideoShoppingBuyerFrontendServiceAssets%2F9cb1ee89cc42a0fc8b18d5b49ba7f4f82fd27c16.js.lz4&ext=js&AUIClients&AUIClients/LiveVideoShoppingBuyerFrontendServiceAssets:31:325553)
    at t.default.checkBrowserSupportAndFeatureConfiguration (asset?key=gautamx%2Fgautamx_LiveVideoShoppingBuyerFrontendServiceCR%2FLiveVideoShoppingBuyerFrontendServiceAssets%2F9cb1ee89cc42a0fc8b18d5b49ba7f4f82fd27c16.js.lz4&ext=js&AUIClients&AUIClients/LiveVideoShoppingBuyerFrontendServiceAssets:31:456764)
    at new t.default (asset?key=gautamx%2Fgautamx_LiveVideoShoppingBuyerFrontendServiceCR%2FLiveVideoShoppingBuyerFrontendServiceAssets%2F9cb1ee89cc42a0fc8b18d5b49ba7f4f82fd27c16.js.lz4&ext=js&AUIClients&AUIClients/LiveVideoShoppingBuyerFrontendServiceAssets:31:454596)
    at S (asset?key=gautamx%2Fgautamx_LiveVideoShoppingBuyerFrontendServiceCR%2FLiveVideoShoppingBuyerFrontendServiceAssets%2F9cb1ee89cc42a0fc8b18d5b49ba7f4f82fd27c16.js.lz4&ext=js&AUIClients&AUIClients/LiveVideoShoppingBuyerFrontendServiceAssets:31:932544)
    at asset?key=gautamx%2Fgautamx_LiveVideoShoppingBuyerFrontendServiceCR%2FLiveVideoShoppingBuyerFrontendServiceAssets%2F9cb1ee89cc42a0fc8b18d5b49ba7f4f82fd27c16.js.lz4&ext=js&AUIClients&AUIClients/LiveVideoShoppingBuyerFrontendServiceAssets:31:933415
    at l (asset?key=gautamx%2Fgautamx_LiveVideoShoppingBuyerFrontendServiceCR%2FLiveVideoShoppingBuyerFrontendServiceAssets%2F9cb1ee89cc42a0fc8b18d5b49ba7f4f82fd27c16.js.lz4&ext=js&AUIClients&AUIClients/LiveVideoShoppingBuyerFrontendServiceAssets:31:923751)
    at Generator.<anonymous> (asset?key=gautamx%2Fgautamx_LiveVideoShoppingBuyerFrontendServiceCR%2FLiveVideoShoppingBuyerFrontendServiceAssets%2F9cb1ee89cc42a0fc8b18d5b49ba7f4f82fd27c16.js.lz4&ext=js&AUIClients&AUIClients/LiveVideoShoppingBuyerFrontendServiceAssets:31:925106)
    at Generator.next (asset?key=gautamx%2Fgautamx_LiveVideoShoppingBuyerFrontendServiceCR%2FLiveVideoShoppingBuyerFrontendServiceAssets%2F9cb1ee89cc42a0fc8b18d5b49ba7f4f82fd27c16.js.lz4&ext=js&AUIClients&AUIClients/LiveVideoShoppingBuyerFrontendServiceAssets:31:924114)
    at x (asset?key=gautamx%2Fgautamx_LiveVideoShoppingBuyerFrontendServiceCR%2FLiveVideoShoppingBuyerFrontendServiceAssets%2F9cb1ee89cc42a0fc8b18d5b49ba7f4f82fd27c16.js.lz4&ext=js&AUIClients&AUIClients/LiveVideoShoppingBuyerFrontendServiceAssets:31:929759)
    at s (asset?key=gautamx%2Fgautamx_LiveVideoShoppingBuyerFrontendServiceCR%2FLiveVideoShoppingBuyerFrontendServiceAssets%2F9cb1ee89cc42a0fc8b18d5b49ba7f4f82fd27c16.js.lz4&ext=js&AUIClients&AUIClients/LiveVideoShoppingBuyerFrontendServiceAssets:31:929962)
```

User Agent Info from request:
```
User-Agent: Amazon.com/26.7.2.100 (Android/13/sdk_gphone64_arm64)
```

Code snippet for client

```
function createMeetingSession() {
        // following variable are injected by jsp into global scope
        const meetingConfig = utils.getMeetingSessionConfiguration(
        meetingId, attendeeId, joinToken, externalUserId,
        audioFallbackUrl, audioHostUrl, signalingUrl, turnControlUrl);
        deviceController = new DefaultDeviceController(logger);

        try {
            meetingSession = new DefaultMeetingSession(meetingConfig, logger, deviceController);
        } catch (error) {
            console.error("Error in meetingHandler try block", error)
        }
        audioVideo = meetingSession.audioVideo;
    }
```

> Note: It is working in chrome browser on same device

### Have you reviewed our existing documentation?

- [X] GitHub [issues](https://github.com/aws/amazon-chime-sdk-js/issues)
- [X] FAQs [page](https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html)
- [X] README [page](https://github.com/aws/amazon-chime-sdk-js#amazon-chime-sdk-for-javascript)
- [X] Feature-specific [guides](https://github.com/aws/amazon-chime-sdk-js#guides)

### Reproduction steps

NA
Info: I am testing it in Amazon MShop App

### Amazon Chime SDK for JavaScript version

"amazon-chime-sdk-js": "^3.9.0"

### What browsers are you seeing the problem on?

chrome

### Browser version

Chrome 101.0.4951.74

### Browser console logs

```
Created meeting config
[INFO] Chime Logs - DefaultDeviceController video dimension 960 x 540
[INFO] Chime Logs - Supported Constraints in this browser {"aspectRatio":true,"autoGainControl":true,"brightness":true,"channelCount":true,"colorTemperature":true,"contrast":true,"deviceId":true,"echoCancellation":true,"exposureCompensation":true,"exposureMode":true,"exposureTime":true,"facingMode":true,"focusDistance":true,"focusMode":true,"frameRate":true,"groupId":true,"height":true,"iso":true,"latency":true,"noiseSuppression":true,"pan":true,"pointsOfInterest":true,"resizeMode":true,"sampleRate":true,"sampleSize":true,"saturation":true,"sharpness":true,"tilt":true,"torch":true,"whiteBalanceMode":true,"width":true,"zoom":true}
Created device controller
Error in meetingHandler try block TypeError: Cannot read properties of null (reading 'name')
    at s.name (asset?key=gautamx%2Fgautamx_LiveVideoShoppingBuyerFrontendServiceCR%2FLiveVideoShoppingBuyerFrontendServiceAssets%2F9cb1ee89cc42a0fc8b18d5b49ba7f4f82fd27c16.js.lz4&ext=js&AUIClients&AUIClients/LiveVideoShoppingBuyerFrontendServiceAssets:31:325553)
    at t.default.checkBrowserSupportAndFeatureConfiguration (asset?key=gautamx%2Fgautamx_LiveVideoShoppingBuyerFrontendServiceCR%2FLiveVideoShoppingBuyerFrontendServiceAssets%2F9cb1ee89cc42a0fc8b18d5b49ba7f4f82fd27c16.js.lz4&ext=js&AUIClients&AUIClients/LiveVideoShoppingBuyerFrontendServiceAssets:31:456764)
    at new t.default (asset?key=gautamx%2Fgautamx_LiveVideoShoppingBuyerFrontendServiceCR%2FLiveVideoShoppingBuyerFrontendServiceAssets%2F9cb1ee89cc42a0fc8b18d5b49ba7f4f82fd27c16.js.lz4&ext=js&AUIClients&AUIClients/LiveVideoShoppingBuyerFrontendServiceAssets:31:454596)
    at S (asset?key=gautamx%2Fgautamx_LiveVideoShoppingBuyerFrontendServiceCR%2FLiveVideoShoppingBuyerFrontendServiceAssets%2F9cb1ee89cc42a0fc8b18d5b49ba7f4f82fd27c16.js.lz4&ext=js&AUIClients&AUIClients/LiveVideoShoppingBuyerFrontendServiceAssets:31:932544)
    at asset?key=gautamx%2Fgautamx_LiveVideoShoppingBuyerFrontendServiceCR%2FLiveVideoShoppingBuyerFrontendServiceAssets%2F9cb1ee89cc42a0fc8b18d5b49ba7f4f82fd27c16.js.lz4&ext=js&AUIClients&AUIClients/LiveVideoShoppingBuyerFrontendServiceAssets:31:933415
    at l (asset?key=gautamx%2Fgautamx_LiveVideoShoppingBuyerFrontendServiceCR%2FLiveVideoShoppingBuyerFrontendServiceAssets%2F9cb1ee89cc42a0fc8b18d5b49ba7f4f82fd27c16.js.lz4&ext=js&AUIClients&AUIClients/LiveVideoShoppingBuyerFrontendServiceAssets:31:923751)
    at Generator.<anonymous> (asset?key=gautamx%2Fgautamx_LiveVideoShoppingBuyerFrontendServiceCR%2FLiveVideoShoppingBuyerFrontendServiceAssets%2F9cb1ee89cc42a0fc8b18d5b49ba7f4f82fd27c16.js.lz4&ext=js&AUIClients&AUIClients/LiveVideoShoppingBuyerFrontendServiceAssets:31:925106)
    at Generator.next (asset?key=gautamx%2Fgautamx_LiveVideoShoppingBuyerFrontendServiceCR%2FLiveVideoShoppingBuyerFrontendServiceAssets%2F9cb1ee89cc42a0fc8b18d5b49ba7f4f82fd27c16.js.lz4&ext=js&AUIClients&AUIClients/LiveVideoShoppingBuyerFrontendServiceAssets:31:924114)
    at x (asset?key=gautamx%2Fgautamx_LiveVideoShoppingBuyerFrontendServiceCR%2FLiveVideoShoppingBuyerFrontendServiceAssets%2F9cb1ee89cc42a0fc8b18d5b49ba7f4f82fd27c16.js.lz4&ext=js&AUIClients&AUIClients/LiveVideoShoppingBuyerFrontendServiceAssets:31:929759)
    at s (asset?key=gautamx%2Fgautamx_LiveVideoShoppingBuyerFrontendServiceCR%2FLiveVideoShoppingBuyerFrontendServiceAssets%2F9cb1ee89cc42a0fc8b18d5b49ba7f4f82fd27c16.js.lz4&ext=js&AUIClients&AUIClients/LiveVideoShoppingBuyerFrontendServiceAssets:31:929962)
```

**Comment by simmkyu** [comment] 2023-04-12 22:50
The Chime SDK for JavaScript uses the [detect-browser library](https://www.npmjs.com/package/detect-browser) to extract browser information. The detect-browser library parses the user agent and verifies if its pre-defined browser list includes the specified browser.
- https://github.com/DamonOehlman/detect-browser/blob/546e6f1348375d8a486f21da07b20717267f6c49/src/index.ts#L262-L264
- Pre-defined list: https://github.com/DamonOehlman/detect-browser/blob/546e6f1348375d8a486f21da07b20717267f6c49/src/index.ts#L134

Here's a CodePen example to reproduce the issue:
1. Open [https://codepen.io/simmkyu/pen/rNZyYva](https://codepen.io/simmkyu/pen/rNZyYva) in your web view.
2. Click the "Use Detect-Browser" button. You should see the same error in CodePen's console or the browser console.

Questions:

- Do you see the same error in the CodePen example above?
- Do you customize the user agent in Android's WebView? Is it possible to use the default (or one of the user agent rules defined in the [detect-browser list](https://github.com/DamonOehlman/detect-browser/blob/master/src/index.ts#L134)) to mitigate the issue?

**Comment by mgautam98** [comment] 2023-04-13 20:16
Hi @simmkyu thanks for putting details about how chime detects browser. Yes the given codepen still throws error as our [detect-browser]([detect-browser library](https://www.npmjs.com/package/detect-browser)) is not able to parse our user-agent `Amazon.com/26.7.2.100 (Android/13/sdk_gphone64_arm64)`. We and many teams are planning to use chime in Amazon MShop android app and we can not change user-agent as we do not have control over native features.

What I see is the detect-browser library does have in-app browsers used by `facebook`, `Instagram`. I would go ahead with adding a browser for `amazon` as well. We want chime to support `amazon` as supported browser. Could we also make changes in `DefaultBrowserBehaviour` to add `amazon` as supported browser?

**Comment by xuesichao** [comment] 2023-04-28 19:05
We are not able to add support for amazon browser, because it's internal and we don't have control of `detect-browser.detect()` method.

What we can do is to give it a fallback value so it will not be `null` when UserAgent is not supported. The fix for this has been merged and will be included in next version release. Closing this now.

**Closed by xuesichao** 2023-04-28 19:05 UTC
