### ISSUE TITLE
Server halted during compilation

### ISSUE THREAD

**Issue by abhimanusharma** [aws/amazon-chime-sdk-js#1760] opened 2021-11-08 11:29 UTC
### What happened and what did you expect to happen?

Got below error in cloudwatch

```
c[[90m10:42:03 AM[0m] Starting compilation in watch mode...
--
[96mnode_modules/@types/dom-mediacapture-record/index.d.ts[0m:[93m48[0m:[93m5[0m - [91merror[0m[90m TS2717: [0mSubsequent property declarations must have the same type.  Property '"error"' must be of type 'Event', but here has type 'MediaRecorderErrorEvent'.
[7m48[0m     "error": MediaRecorderErrorEvent;
[7m  [0m [91m    ~~~~~~~[0m
[96mnode_modules/typescript/lib/lib.dom.d.ts[0m:[93m9927[0m:[93m5[0m
[7m9927[0m     "error": Event;
[7m    [0m [96m    ~~~~~~~[0m
'"error"' was also declared here.
[96mnode_modules/@types/dom-mediacapture-record/index.d.ts[0m:[93m64[0m:[93m5[0m - [91merror[0m[90m TS2717: [0mSubsequent property declarations must have the same type.  Property 'onerror' must be of type '(this: MediaRecorder, ev: Event) => any', but here has type '(this: MediaRecorder, event: MediaRecorderErrorEvent) => any'.
[7m64[0m     onerror: ((this: MediaRecorder, event: MediaRecorderErrorEvent) => any) \| null;
[7m  [0m [91m    ~~~~~~~[0m
[96mnode_modules/typescript/lib/lib.dom.d.ts[0m:[93m9938[0m:[93m5[0m
[7m9938[0m     onerror: ((this: MediaRecorder, ev: Event) => any) \| null;
[7m    [0m [96m    ~~~~~~~[0m
'onerror' was also declared here.
[[90m10:43:00 AM[0m] Found 2 errors. Watching for file changes.
 
```

### Have you reviewed our existing documentation?

- [X] GitHub [issues](https://github.com/aws/amazon-chime-sdk-js/issues)
- [X] FAQs [page](https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html)
- [X] README [page](https://github.com/aws/amazon-chime-sdk-js#amazon-chime-sdk-for-javascript)
- [X] Feature-specific [guides](https://github.com/aws/amazon-chime-sdk-js#guides)

### Reproduction steps

Just tried to deploy the latest build to the server.

### Amazon Chime SDK for JavaScript version

"amazon-chime-sdk-js": "2.16.1",

### What browsers are you seeing the problem on?

Google Chrome

### Browser version

Version 95.0.4638.54 (Official Build) (64-bit)

### Browser console logs

NA

**Comment by xuesichao** [comment] 2021-11-08 20:12
Hi @abhimanusharma thanks for reporting this issue. I made an investigation and it seems the issue is related to TypeScript 4.5-beta version. Check this [issue](https://github.com/microsoft/TypeScript/issues/46665#issuecomment-962142351) under TypeScript repo.

#### Reproduction Steps
I tried to reproduce this issue in our [JS SDK meetingV2 demo](https://github.com/aws/amazon-chime-sdk-js/tree/master/demos/browser/app/meetingV2). 
* I can not reproduce it with our package.json config, where the typescript version is 4.2.1.
* I can reproduce it after running `npm install typescript@beta`. The typescript version is then 4.5-beta.

#### Questions
What is the typescript version you are using?
* If it's 4.5-beta, could you please try to reproduce it after downgrade the typescript version to 4.2.1 or any non-beta version
* If not, could you please try to reproduce it using our [JS SDK meetingV2 demo](https://github.com/aws/amazon-chime-sdk-js/tree/master/demos/browser/app/meetingV2)
* If not, could you please provide the detailed reproduction steps

**Comment by abhimanusharma** [comment] 2021-11-09 06:11
I am facing this issue after updating the sdk version.

**Comment by xuesichao** [comment] 2021-11-09 17:30
@abhimanusharma I can not reproduce this issue in our demo App. The problem appears to be related to typescript. Could you confirm your typescript version?

**Comment by abhimanusharma** [comment] 2021-11-10 06:00
@xuesichao My typescript version is "typescript": "^4.2.4", I can not change the version as the app is already on production. Changing the version might put me in a very difficult situation. The issue I am facing is on production.

**Comment by ltrung** [comment] 2021-11-29 23:28
@abhimanusharma Can you verify that your typescript version in node_modules? ^4.2.4 means it can be any minor v4 version and I don't think JS SDK will work with TS v4.4+.

**Comment by devalevenkatesh** [comment] 2021-12-30 01:17
Closing this issue due to in-activity, feel free to re-open if you still need any help further or have any questions around this.

**Closed by devalevenkatesh** 2021-12-30 01:17 UTC
Labels: Needs More Information
