### ISSUE TITLE
Video cannot be received when turning on/off in a room with 2 participants

### ISSUE THREAD

**Issue by dathacky** [aws/amazon-chime-sdk-js#2064] opened 2022-02-25 07:09 UTC
### What happened and what did you expect to happen?

The remote side can't see the video when I try to turn on/off the camera

https://drive.google.com/file/d/1zCY8OWJ86ksKBKqKvG5gZT5Y-vfuqmsN/view?usp=sharing

### Have you reviewed our existing documentation?

- [X] GitHub [issues](https://github.com/aws/amazon-chime-sdk-js/issues)
- [X] FAQs [page](https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html)
- [X] README [page](https://github.com/aws/amazon-chime-sdk-js#amazon-chime-sdk-for-javascript)
- [X] Feature-specific [guides](https://github.com/aws/amazon-chime-sdk-js#guides)

### Reproduction steps

1. A and B join the meeting (Check Enable Simulcast for Chrome and Use Priority-Based Downlink Policy [Stable Network])
2. A and B turn on the camera
3. A turn off the camera
4. A turn on camera -> **on the B side, A's video is not received**

### Amazon Chime SDK for JavaScript version

2.27

### What browsers are you seeing the problem on?

Chrome

### Browser version

Version 98.0.4758.102 (Official Build) (x86_64)

### Browser console logs

No

**Comment by devalevenkatesh** [comment] 2022-02-25 17:27
Thanks for reporting the issue. I checked the video and tried to reproduced with our deployed apps for `2.24.0` as well as the latest SDK versions and could not reproduce the same issue.

My System:
- macOS Big Sur 11.6.3
- Chrome 98.0.4758.102 (Official Build) (x86_64) 

- Could you please attach your browser console logs to check further?
- Your deployed demo is using `2.24.0` version can you  once upgrade to latest SDK version `2.27.0` and check if you can run into the same issue?

**Comment by dathacky** [comment] 2022-02-28 01:36
@devalevenkatesh 
Can you reproduce it with the steps below, I just updated it, including joining the meeting room with 2 options Enable Simulcast for Chrome and Use Priority-Based Downlink Policy [Stable Network]
1. A and B join the meeting (Check Enable Simulcast for Chrome and Use Priority-Based Downlink Policy [Stable Network])
2. A and B turn on the camera
3. A turn off the camera
4. A turn on camera -> **on the B side, A's video is not received**

**Comment by ltrung** [comment] 2022-02-28 06:20
Thanks for reporting. I could reproduce this with just toggle a video on/off then on again in a simulcast meeting. Seem like the issue is with the uplink (transceiver encoder). I will investigate more and get back to you.

**Comment by hensmi-amazon** [comment] 2022-02-28 19:25
Thanks for the report @dathacky , we have narrowed this down to a backend change for an unrelated Firefox fix which split up send/recv video RTP extension negotiation and had a side effect of not putting extensions in inactive sections. libwebrtc responds a bit unfortunately here even though the section is inactive (likely due to removing 'mid') and disables simulcast for all future negotiations. We are deploying a fix now (we should also probably stop trying to reuse local send transceivers...) and it should be deployed if all goes well by tomorrow. We will update that ticket when complete.

**Comment by hensmi-amazon** [comment] 2022-03-01 17:33
Fix has been deployed and I have confirmed fix using our demo. Closing now, sorry for the inconvenience!

**Closed by hensmi-amazon** 2022-03-01 17:33 UTC
Labels: video
