### ISSUE TITLE
Zoomed in effect when Simulcast is enabled

### ISSUE THREAD

**Issue by zepedr0** [aws/amazon-chime-sdk-js#2844] opened 2024-02-19 16:07 UTC
### What happened and what did you expect to happen?

If I set `enableSimulcastForUnifiedPlanChromiumBasedBrowsers` as true in the `MeetingSessionConfiguration`, my camera loads with a zoomed in effect.

### Have you reviewed our existing documentation?

- [X] GitHub [issues](https://github.com/aws/amazon-chime-sdk-js/issues)
- [X] FAQs [page](https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html)
- [X] README [page](https://github.com/aws/amazon-chime-sdk-js#amazon-chime-sdk-for-javascript)
- [X] Feature-specific [guides](https://github.com/aws/amazon-chime-sdk-js#guides)

### Reproduction steps

This is possible to reproduce in the demo application, but I think it is only happening with M2 macbooks. Make sure to set `configuration.enableSimulcastForUnifiedPlanChromiumBasedBrowsers = true` (if simulcast is enabled in the frontend options it does not work, it should be hardcoded as true), and that your camera is not active anywhere else (green light is turned off). After joining the meeting and turning on the camera the image should start zoomed in (if it doesn't, turn the video off, wait for the green light to turn off, and the start the video on again).

Issue seems related to the Facetime camera recording in a vertical mode:
 
<img width="310" alt="Screenshot 2024-02-19 at 16 49 27" src="https://github.com/aws/amazon-chime-sdk-js/assets/44657095/c3a79620-5b94-4421-856b-7b35e5eae946">

Instead of the standard horizontal mode:

<img width="302" alt="Screenshot 2024-02-19 at 16 50 23" src="https://github.com/aws/amazon-chime-sdk-js/assets/44657095/8283d486-e2a8-4553-87d2-a8d0934abb2e">

### Amazon Chime SDK for JavaScript version

amazon-chime-sdk-js@3.20.0

### What browsers are you seeing the problem on?

Chrome

### Browser version

Version 121.0.6167.160 (Official Build) (arm64)

### Browser console logs

[localhost-1708358470439.log](https://github.com/aws/amazon-chime-sdk-js/files/14334538/localhost-1708358470439.log)

**Comment by hensmi-amazon** [comment] 2024-02-20 20:13
Thanks for the report! I was able to reproduce this with an M2 laptop, seems to be some unwanted interaction with the built in camera when we set media constraints. I will have a fix in the next release, but given that will not be too soon, you can mitigate this issue with code like the following:
```
    if (new DefaultBrowserBehavior().hasChromiumWebRTC()) {
        configuration.videoUplinkBandwidthPolicy = new DefaultSimulcastUplinkPolicy(
            configuration.credentials.attendeeId,
            this.meetingLogger
          );
        configuration.videoUplinkBandwidthPolicy.chooseMediaTrackConstraints = (): MediaTrackConstraints => {
            const trackConstraint: MediaTrackConstraints = {
              width: { ideal: 1280 },
              height: { ideal: 720 },
              frameRate: { ideal: 15 },
            };
            return trackConstraint;
          }
      }

      this.meetingSession = new DefaultMeetingSession(
         configuration,
         this.meetingLogger,
         this.deviceController,
         new DefaultEventController(configuration, this.meetingLogger, this.eventReporter)
     );
```

**Comment by zepedr0** [comment] 2024-02-21 12:09
Thank you for looking into this so fast! That workaround seems to have fixed our issue for now 🙌

**Comment by hensmi-amazon** [comment] 2024-04-02 19:13
Latest version is released, closing

**Closed by hensmi-amazon** 2024-04-02 19:13 UTC
Labels: video
