### ISSUE TITLE
 AWS.Chime is not a constructor

### ISSUE THREAD

**Issue by aalvarezcoco** [aws/amazon-chime-sdk-js#303] opened 2020-04-23 17:05 UTC
**Important:** Please attach INFO-level logs with timestamps to the report from *before* the session started up until the point at which the unexpected behavior occured. For multi-participant calls, attach a log file for each participant if possible.

**Meeting and attendee IDs:**
List the meeting and attendee IDs that the attached logs apply to.

**Timeline**
Outline the main actions the user performed and when:

* <timestamp> <action>
* <timestamp> <action>

**Describe the bug**
 const uuid = require('uuid/v4');
    const AWS = require('aws-sdk');
    const chime = new AWS.Chime({ region: 'us-east-1' });

ResizeObserverEntry.ts:12 Uncaught TypeError: AWS.Chime is not a constructor
    at Module../node_modules/babel-loader/lib/index.js?!./node_modules/vue-loader/lib/index.js?!./resources/js/components/ExampleComponent.vue?vue&type=script&lang=js& (ResizeObserverEntry.ts:12)
    at __webpack_require__ (ResizeObserverEntry.ts:12)
    at Module../resources/js/components/ExampleComponent.vue?vue&type=script&lang=js& (ResizeObserverEntry.ts:12)
    at __webpack_require__ (ResizeObserverEntry.ts:12)
    at Module../resources/js/components/ExampleComponent.vue (ResizeObserverEntry.ts:12)
    at __webpack_require__ (ResizeObserverEntry.ts:12)
    at Object../resources/js/app.js (ResizeObserverEntry.ts:12)
    at __webpack_require__ (ResizeObserverEntry.ts:12)
    at Object.0 (ResizeObserverEntry.ts:12)
    at __webpack_require__ (ResizeObserverEntry.ts:12)
**Screenshots**
If applicable, add screenshots to help explain the problem.

**Platform**
 - OS: Linux ubuntu
 - Browser: Chrome
 - Browser Version: 
 - Amazon Chime SDK GitHub Commit:  Vuejs Api SDK amazon chime JS

**Comment by simmkyu** [comment] 2020-04-23 17:15
From https://github.com/aws/amazon-chime-sdk-js#getting-responses-from-your-server-application

The following code should be ran on your server-side Node.js application. Could you make sure you have installed `uuid` and `aws-sdk` dependencies in your Node.js project?

```
const uuid = require('uuid/v4');
const AWS = require('aws-sdk');
const chime = new AWS.Chime({ region: 'us-east-1' });
```

**Comment by aalvarezcoco** [comment] 2020-04-23 18:08
"dependencies": {
        "amazon-chime-sdk-js": "^1.3.0",
        "aws-sdk": "^2.656.0"
    },

**Comment by aalvarezcoco** [comment] 2020-04-23 18:17
const AWS = require('aws-sdk');
I print console.log(AWS) shows all the services except the Chime service

**Comment by simmkyu** [comment] 2020-04-23 18:18
```
"dependencies": {
  "amazon-chime-sdk-js": "^1.3.0",  // <-- A browser 
  "aws-sdk": "^2.656.0" // <-- It should be included in your server-side application
},
```

Here's a high-level flow:
1. A user joins your browser app and asks your server application to create or join a meeting.
2. Your server application creates a meeting and an attendee using AWS SDK (e.g. `aws-sdk` in Node.js). The server application returns responses back to your browser app
3. In your browser app, a user starts the 'amazon-chime-sdk-js' session using responses from your server.

https://github.com/aws/amazon-chime-sdk-js#getting-responses-from-your-server-application

**Comment by aalvarezcoco** [comment] 2020-04-23 18:49
I can use as backend php and not a node js and use the sdk aws php v3??

**Comment by simmkyu** [comment] 2020-04-23 19:07
Node.js is not required in your backend. Yes, you can use *AWS SDK for PHP*:
https://docs.aws.amazon.com/aws-sdk-php/v3/api/api-chime-2018-05-01.html

Or AWS SDK in other programming languages:
https://aws.amazon.com/tools

**Comment by simmkyu** [comment] 2020-04-27 16:51
I'll close this issue as it's not a bug in SDK. Please try using AWS SDK in your server application, and `amazon-chime-sdk-js` (Chime SDK for JavaScript) in your client application.

**Closed by simmkyu** 2020-04-27 16:51 UTC
Labels: bug
