### ISSUE TITLE
Set Audio Device infinite cycle

### ISSUE THREAD

**Issue by tylerlot** [aws/amazon-chime-sdk-js#1272] opened 2021-05-10 18:57 UTC
**Important:** _Available Upon Request_

**Meeting and attendee IDs:**
_Available Upon Request_

**Timeline**
We successfully created the Chime meeting object, get device lists for each type (audioInput, audioOutput, videoInput) however, when we set our first device (audioInput) it seems to have begun an infinite loop infinite loop in the promise trying to get/set the device, log sample below. Our logs show we never get past the await on setting the audio input device
- API/DefaultAudioVideoFacade/REDACTED/REDACTED/chooseAudioInputDevice "default" (triggered, only appears once)

Then a cycle of below starts...
- requesting new audio device with constraint {CONSTRAINTS}
- got audio device for constraints {CONSTRAINTS}
- stopping audio track
- checking whether existing audio device can be reused

**Describe the bug**
Logs available upon request, seems setAudioInputDevice was able to get into an infinite loop.

This is the first time we have seen the issue, have had hundreds of successful calls

**Screenshots**
Log count occurrences
![Screen Shot 2021-05-10 at 11 50 40 AM](https://user-images.githubusercontent.com/64169537/117709756-276b2780-b186-11eb-9cd7-164170142560.png)

**Platform**
 - OS: Mac
 - Browser: Chrome 
 - Browser Version: (89.0.4389) 
 - Amazon Chime SDK GitHub Commit: version 1.6.4

**Comment by tylerlot** [comment] 2021-05-11 16:58
Yes, all devices were listed audio input / output / video input are fetched before we try to set any devices

**Comment by ltrung** [comment] 2021-05-11 18:31
If it is from 2.6.0 and later, there are several issue about this: #1136, #1201, and #1225. Could you take a look and see whether anything there can apply to your case?
The usual cause of this is that this check for reusing existing input failed https://github.com/aws/amazon-chime-sdk-js/blob/master/src/devicecontroller/DefaultDeviceController.ts#L1335 which can be either:
- `listAudioInput` is not called beforehand and thus, the device cache inside `DefaultDeviceController` is empty.
- deviceId is not passed in correctly.

Since you mention that you already call `listAudioInput`, could you let us know what is the input you passed in to `chooseAudioInput`

**Comment by tylerlot** [comment] 2021-05-14 16:41
Thanks for following up, we pass in the deviceId. 

The symptoms sound the same to #1136, we never get past trying to set the audioInputDevice. I see the logs getting to the call to set `chooseAudioInputDevice`, and then the chime-sdk's INFO level logs I sent the counts of repeating until our user ended the call.

Prior to attempting to set any of our devices, we populate the device lists using the `listAudioInputDevices` method so it doesn't match #1201 or #1225

**Comment by ltrung** [comment] 2021-05-14 17:18
Just to clarify, the deviceId you passed in is string correct?
Can you edit the screenshot to show the full message of `got audio device for constraints {"audio": ...`? We would like to know the constraints that were used.
It would be great if you could send us the console.log too.

**Comment by tylerlot** [comment] 2021-05-14 17:21
Yes deviceId is a string from one of the devices listed out. 

`{"audio":{"echoCancellation":true,"googEchoCancellation":true,"googEchoCancellation2":true,"googAutoGainControl":true,"googAutoGainControl2":true,"googNoiseSuppression":true,"googNoiseSuppression2":true,"googHighpassFilter":true,"deviceId":{"exact":"default"}}}`

**Comment by chuckntaylor** [comment] 2021-05-28 05:50
While moving my project to TypeScript, I am back to having this issue yet again. This time while initially calling `chooseAudioInputDevice` on the `DefaultDeviceController`.
Trying to resolve it, I tested calling `listAudioInputDevices` immediately before calling `chooseAudioInputDevice`

```js
const newDevices = await this.deviceController.listAudioInputDevices()
console.log(newDevices) // I can see a list of devices
await this.deviceController.chooseAudioInputDevice(newDevices[0].deviceId) // just cannot get out of this
```

No luck. I am on v2.10.0 of amazon-chime-sdk-js

**Comment by ltrung** [comment] 2021-06-01 22:01
@tylerlot Sorry for the late reply. I added more logging in #1329. Could you check out that PR and changes the log level to debug and give us the console log?

**Comment by michhyun1** [comment] 2021-06-10 21:07
@tylerlot if you could provide a snippet of those debug logs when the infinite loop occurs that would be helpful. 

Also, I have a slight suspicion that it might have something to do with the device cache that we maintain in the demo. Perhaps you can try this:

https://github.com/aws/amazon-chime-sdk-js/blob/5a68c57387b79c5c9361270d8a0878f6ede1ad2b/src/devicecontroller/DeviceController.ts#L57

When you call listAudioInputDevice, pass in a 'true' boolean to force update the device cache. If you see any errors still, please attach the corresponding debug logs. Thanks

**Comment by tylerlot** [comment] 2021-06-10 22:01
@michhyun1 sounds good, in the meantime should I just update the boolean for listing out the devices to be true (even before we confirm if the deviceCache is the root of the issue?)

**Comment by michhyun1** [comment] 2021-06-10 22:37
@tylerlot yeah, you can try that for now - I've been trying to reproduce this a couple times now but I haven't been able to. Is there any specific repro steps that could help me reproduce this? Debug logs would be very helpful otherwise.

**Comment by jing-chen1** [comment] 2021-07-15 18:49
Closing the issue for now. Feel free to reopen it if you still have problems.

**Closed by jing-chen1** 2021-07-15 18:49 UTC
Labels: Needs More Information, device
