### ISSUE TITLE
Video file sharing remains black for recipients when send in Chrome 88 and Edge 88

### ISSUE THREAD

**Issue by ReneS1991** [aws/amazon-chime-sdk-js#1031] opened 2021-01-27 09:27 UTC
**What's happening**
In both our Amazon Chime implementation AND the Chime demo (meetingV2) sharing a video-file in Chrome 88 and Edge 88 doesn't work properly anymore. When sharing the video-file from Chrome or Edge, the sender sees the video playing fine but all recipients see a black-screen, see attached screenshot. When sharing from Firefox it all works as it should, see attached screenshot 2.

As it was working a few days ago I thought it could be the Chrome version that was causing it so I tested Chrome 87 and there it all works again. I have no idea if this is something that needs fixing in the Chime SDK or in Chrome. Any help is more than welcome if anyone knows how to solve this.

NOTE: I tested this more with Chrome than with Edge, but for Edge 88 it doesn't work anymore either. I haven't checked if it was working in Edge 87, I only know it used to work in Edge so I don't exactly know from which version on it stopped working.

EDIT: I tested Chrome 90 (Canary) and it isn't fixed there yet.

**Screenshots**
Left: Chrome that is sharing the video
Right: Edge that is receiving the video
![image](https://user-images.githubusercontent.com/17007821/105969908-0ecc7b00-6089-11eb-91e3-4beff18c76aa.png)

Left: Chrome (88) that is receiving the video
Right: Firefox that is sharing the video
![image](https://user-images.githubusercontent.com/17007821/105970496-ba75cb00-6089-11eb-9ea3-47aa449c27a4.png)

**Platform**
 - OS: MacOS
 - Browser: Chrome
 - Browser Version: 88.0.4324.96
 - Amazon Chime SDK GitHub Commit: https://github.com/aws/amazon-chime-sdk-js/commit/9f3eaa1c1615e0d12115d4f56b4d722beedbbf99

**Comment by simmkyu** [comment] 2021-01-28 20:12
The content-share API in Chime SDK for JavaScript uses the `HTMLMediaElement.captureStream` API to stream a video file. Since specific builds of Chrome 88 on macOS and Windows, the "captureStream()" had a problem sending data.
https://bugs.chromium.org/p/chromium/issues/detail?id=1156408

The bug also occurs in the official WebRTC demo. Open the following link and click the Play button on the right video element. You will see the black screen. The expected behavior is that you see the same video in both left and right elements.
https://webrtc.github.io/samples/src/content/capture/video-pc

As a workaround, the [Chromium bug report](https://bugs.chromium.org/p/chromium/issues/detail?id=1156408) suggests turning off the hardware acceleration option. Try the following steps:
1. Open Chrome and click the vertical ellipsis at the top-right corner.
2. Click Settings.
3. In the "Search settings" field, search "Use hardware". 
4. Disable "Use hardware acceleration when available" and click "Relaunch."
5. Try both the Chime SDK for JavaScript and the official WebRTC demo:
  a. Join the meeting on Chrome and share the file video. Others should see the file video from this Chrome presenter.
  b. Join the [official WebRTC demo](https://webrtc.github.io/samples/src/content/capture/video-pc) and click the play button in the right video element. You should see the same content in both video elements.

**Comment by ReneS1991** [comment] 2021-01-29 10:17
Thank you for your extensive & informative reply @simmkyu ! At least we have a workaround now to offer our clients, thank you 😄

**Comment by simmkyu** [comment] 2021-02-02 01:09
We just confirmed that the workaround causes another video issue in macOS Chrome 88 due to the following Chromium bug.
- [Disabling hardware acceleration silently fails to encode camera frames in WebRTC on macOS](https://bugs.chromium.org/p/chromium/issues/detail?id=1168948)

After disabling the "Use hardware acceleration when available" option, other Chime SDK attendees cannot view the normal video from the Chrome user. They can only see the file video shared by the Chrome user. We will keep this issue updated as we learn more.

**Comment by karthikarul20** [comment] 2021-02-02 03:18
Same here. When the hardware acceleration is disabled, other attendees cannot view my video. When I turn on the "Use hardware acceleration when available" option, the video works.

My MacOS version.
![image](https://user-images.githubusercontent.com/5412806/106547499-45523c00-6548-11eb-9e5d-1a5bae06950f.png)

My Chrome version.
![image](https://user-images.githubusercontent.com/5412806/106547556-63b83780-6548-11eb-85bb-8ed6b6ba22f7.png)

**Comment by simmkyu** [comment] 2021-02-03 01:39
In the new macOS Chrome build (`88.0.4324.146`), the video bug does not occur anymore when you disable hardware acceleration. Other attendees can see your video. According to [Chrome Releases](https://chromereleases.googleblog.com/2021/02/stable-channel-update-for-desktop.html), the Chrome version `88.0.4324.146` will roll out over the coming days/weeks.

Note that video file sharing still does not work in this new Chrome build if hardware acceleration is enabled.
- https://bugs.chromium.org/p/chromium/issues/detail?id=1156408
- https://bugs.chromium.org/p/chromium/issues/detail?id=1171581

**Comment by simmkyu** [comment] 2021-02-08 18:39
The Chrome version 88.0.4324.146 is now available. Other attendees can see the video (not file sharing) from Chrome 88.0.4324.146 with the disabled "Use hardware acceleration when available" option. ([This Chromium issue](https://bugs.chromium.org/p/chromium/issues/detail?id=1168948) does not occur anymore.)

The video file sharing still does not work on 88.0.4324.146 when hardware acceleration is turned on.
- https://bugs.chromium.org/p/chromium/issues/detail?id=1156408
- https://bugs.chromium.org/p/chromium/issues/detail?id=1171581

**Comment by bldcaveman** [comment] 2021-02-12 16:23
We are experiencing this issue too and can confirm turning off hardware acceleration works.

Guess we wait for Chrome to sort it out.

**Comment by michhyun1** [comment] 2021-07-08 17:39
Closing this issue - tracking it in https://github.com/aws/amazon-chime-sdk-js/issues/1059

**Closed by michhyun1** 2021-07-08 17:39 UTC
Labels: Browser Bug

**Comment by ivanpetrushev** [comment] 2021-07-09 05:25
There are multiple browser/device issues, isn't it better to track them in their original tickets?

It is good to have one compiled index ticket, but every issue will have its own status, progress and discussion. 

Putting all in one will create a mess.
